/*
 * compressed_vector_test.cpp - Tests for CompressedVectorNode and Reader/Writer
 *
 * Copyright (c) 2024 openE57 Contributors
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN

#include "test_utils.h"

#include <cstdint>

using namespace e57;
using e57::test::TempFile;

TEST_SUITE("CompressedVectorNode Tests")
{
  TEST_CASE("CompressedVectorNode construction with prototype")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    StructureNode proto(imf);
    proto.set("x", ScaledIntegerNode(imf, 0, -10000, 10000, 0.001, 0.0));
    proto.set("y", ScaledIntegerNode(imf, 0, -10000, 10000, 0.001, 0.0));
    proto.set("z", ScaledIntegerNode(imf, 0, -10000, 10000, 0.001, 0.0));

    VectorNode codecs(imf, true); // Empty codecs = default compression

    CompressedVectorNode cv(imf, proto, codecs);

    REQUIRE_EQ(E57_COMPRESSED_VECTOR, Node(cv).type());

    imf.close();
  }

  TEST_CASE("CompressedVectorNode prototype access")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    StructureNode proto(imf);
    proto.set("value", IntegerNode(imf, 0, 0, 1000));

    VectorNode codecs(imf, true);

    CompressedVectorNode cv(imf, proto, codecs);

    StructureNode retrievedProto(cv.prototype());
    REQUIRE(retrievedProto.isDefined("value"));

    imf.close();
  }

  TEST_CASE("CompressedVectorNode codecs access")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    StructureNode proto(imf);
    proto.set("x", IntegerNode(imf, 0));

    VectorNode codecs(imf, true);

    CompressedVectorNode cv(imf, proto, codecs);

    VectorNode retrievedCodecs = cv.codecs();
    REQUIRE_EQ(0, retrievedCodecs.childCount());

    imf.close();
  }

  TEST_CASE("CompressedVectorNode childCount initially zero")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    StructureNode proto(imf);
    proto.set("value", IntegerNode(imf, 0));

    VectorNode codecs(imf, true);

    CompressedVectorNode cv(imf, proto, codecs);

    REQUIRE_EQ(0, cv.childCount());

    imf.close();
  }
}

TEST_SUITE("CompressedVectorWriter Tests")
{
  TEST_CASE("CompressedVectorWriter write basic data")
  {
    TempFile tempFile;

    const size_t N       = 10;
    int64_t      data[N] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9};

    {
      ImageFile     imf(tempFile.c_str(), "w");
      StructureNode root = imf.root();
      root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
      root.set("guid", StringNode(imf, "{00000000-0000-0000-0000-000000000100}"));

      StructureNode proto(imf);
      proto.set("value", IntegerNode(imf, 0, 0, 100));

      VectorNode codecs(imf, true);

      CompressedVectorNode cv(imf, proto, codecs);
      root.set("data", cv);

      SourceDestBuffer              sdb(imf, "value", data, N, true, true);
      std::vector<SourceDestBuffer> buffers;
      buffers.push_back(sdb);

      CompressedVectorWriter writer = cv.writer(buffers);
      writer.write(N);
      writer.close();

      imf.close();
    }

    REQUIRE(std::filesystem::exists(tempFile.string()));
  }

  TEST_CASE("CompressedVectorWriter write multiple fields")
  {
    TempFile tempFile;

    const size_t N    = 5;
    double       x[N] = {1.0, 2.0, 3.0, 4.0, 5.0};
    double       y[N] = {1.1, 2.1, 3.1, 4.1, 5.1};
    double       z[N] = {1.2, 2.2, 3.2, 4.2, 5.2};

    {
      ImageFile     imf(tempFile.c_str(), "w");
      StructureNode root = imf.root();
      root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
      root.set("guid", StringNode(imf, "{00000000-0000-0000-0000-000000000101}"));

      StructureNode proto(imf);
      proto.set("x", FloatNode(imf, 0.0));
      proto.set("y", FloatNode(imf, 0.0));
      proto.set("z", FloatNode(imf, 0.0));

      VectorNode codecs(imf, true);

      CompressedVectorNode cv(imf, proto, codecs);
      root.set("points", cv);

      std::vector<SourceDestBuffer> buffers;
      buffers.push_back(SourceDestBuffer(imf, "x", x, N, true, true));
      buffers.push_back(SourceDestBuffer(imf, "y", y, N, true, true));
      buffers.push_back(SourceDestBuffer(imf, "z", z, N, true, true));

      CompressedVectorWriter writer = cv.writer(buffers);
      writer.write(N);
      writer.close();

      imf.close();
    }

    REQUIRE(std::filesystem::exists(tempFile.string()));
  }

  TEST_CASE("CompressedVectorWriter isOpen")
  {
    TempFile      tempFile;
    ImageFile     imf(tempFile.c_str(), "w");
    StructureNode root = imf.root();
    root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
    root.set("guid", StringNode(imf, "{00000000-0000-0000-0000-000000000102}"));

    StructureNode proto(imf);
    proto.set("value", IntegerNode(imf, 0));

    VectorNode codecs(imf, true);

    CompressedVectorNode cv(imf, proto, codecs);
    root.set("data", cv);

    int64_t                       data[5] = {1, 2, 3, 4, 5};
    std::vector<SourceDestBuffer> buffers;
    buffers.push_back(SourceDestBuffer(imf, "value", data, 5, true, true));

    CompressedVectorWriter writer = cv.writer(buffers);

    REQUIRE(writer.isOpen());

    writer.close();

    REQUIRE(!writer.isOpen());

    imf.close();
  }

  TEST_CASE("CompressedVectorWriter compressedVectorNode")
  {
    TempFile      tempFile;
    ImageFile     imf(tempFile.c_str(), "w");
    StructureNode root = imf.root();
    root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
    root.set("guid", StringNode(imf, "{00000000-0000-0000-0000-000000000201}"));

    StructureNode proto(imf);
    proto.set("value", IntegerNode(imf, 0));

    VectorNode codecs(imf, true);

    CompressedVectorNode cv(imf, proto, codecs);
    root.set("data", cv);

    int64_t                       data[3] = {1, 2, 3};
    std::vector<SourceDestBuffer> buffers;
    buffers.push_back(SourceDestBuffer(imf, "value", data, 3, true, true));

    CompressedVectorWriter writer = cv.writer(buffers);

    CompressedVectorNode retrieved = writer.compressedVectorNode();
    REQUIRE_EQ(Node(cv), Node(retrieved));

    writer.close();
    imf.close();
  }

  TEST_CASE("CompressedVectorWriter dump")
  {
    TempFile      tempFile;
    ImageFile     imf(tempFile.c_str(), "w");
    StructureNode root = imf.root();
    root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
    root.set("guid", StringNode(imf, "{00000000-0000-0000-0000-000000000202}"));

    StructureNode proto(imf);
    proto.set("value", IntegerNode(imf, 0));

    VectorNode codecs(imf, true);

    CompressedVectorNode cv(imf, proto, codecs);
    root.set("data", cv);

    int64_t                       data[3] = {1, 2, 3};
    std::vector<SourceDestBuffer> buffers;
    buffers.push_back(SourceDestBuffer(imf, "value", data, 3, true, true));

    CompressedVectorWriter writer = cv.writer(buffers);

    std::stringstream ss;
    writer.dump(0, ss);

    std::string output = ss.str();
    REQUIRE(!output.empty());

    writer.close();
    imf.close();
  }
}

TEST_SUITE("CompressedVectorReader Tests")
{
  TEST_CASE("CompressedVectorReader read basic data")
  {
    TempFile tempFile;

    const size_t N            = 10;
    int64_t      writeData[N] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
    int64_t      readData[N]  = {0};

    // Write
    {
      ImageFile     imf(tempFile.c_str(), "w");
      StructureNode root = imf.root();
      root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
      root.set("guid", StringNode(imf, "{00000000-0000-0000-0000-000000000103}"));

      StructureNode proto(imf);
      proto.set("value", IntegerNode(imf, 0, 0, 100));

      VectorNode codecs(imf, true);

      CompressedVectorNode cv(imf, proto, codecs);
      root.set("data", cv);

      std::vector<SourceDestBuffer> buffers;
      buffers.push_back(SourceDestBuffer(imf, "value", writeData, N, true, true));

      CompressedVectorWriter writer = cv.writer(buffers);
      writer.write(N);
      writer.close();

      imf.close();
    }

    // Read
    {
      ImageFile     imf(tempFile.c_str(), "r");
      StructureNode root = imf.root();

      CompressedVectorNode cv(root.get("data"));

      std::vector<SourceDestBuffer> buffers;
      buffers.push_back(SourceDestBuffer(imf, "value", readData, N, true, true));

      CompressedVectorReader reader = cv.reader(buffers);
      unsigned               count  = reader.read();
      reader.close();

      REQUIRE_EQ(N, count);

      for (size_t i = 0; i < N; ++i)
      {
        REQUIRE_EQ(writeData[i], readData[i]);
      }

      imf.close();
    }
  }

  TEST_CASE("CompressedVectorReader read multiple fields")
  {
    TempFile tempFile;

    const size_t N         = 5;
    double       writeX[N] = {1.0, 2.0, 3.0, 4.0, 5.0};
    double       writeY[N] = {1.1, 2.1, 3.1, 4.1, 5.1};
    double       writeZ[N] = {1.2, 2.2, 3.2, 4.2, 5.2};
    double       readX[N]  = {0};
    double       readY[N]  = {0};
    double       readZ[N]  = {0};

    // Write
    {
      ImageFile     imf(tempFile.c_str(), "w");
      StructureNode root = imf.root();
      root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
      root.set("guid", StringNode(imf, "{00000000-0000-0000-0000-000000000104}"));

      StructureNode proto(imf);
      proto.set("x", FloatNode(imf, 0.0));
      proto.set("y", FloatNode(imf, 0.0));
      proto.set("z", FloatNode(imf, 0.0));

      VectorNode codecs(imf, true);

      CompressedVectorNode cv(imf, proto, codecs);
      root.set("points", cv);

      std::vector<SourceDestBuffer> buffers;
      buffers.push_back(SourceDestBuffer(imf, "x", writeX, N, true, true));
      buffers.push_back(SourceDestBuffer(imf, "y", writeY, N, true, true));
      buffers.push_back(SourceDestBuffer(imf, "z", writeZ, N, true, true));

      CompressedVectorWriter writer = cv.writer(buffers);
      writer.write(N);
      writer.close();

      imf.close();
    }

    // Read
    {
      ImageFile     imf(tempFile.c_str(), "r");
      StructureNode root = imf.root();

      CompressedVectorNode cv(root.get("points"));

      std::vector<SourceDestBuffer> buffers;
      buffers.push_back(SourceDestBuffer(imf, "x", readX, N, true, true));
      buffers.push_back(SourceDestBuffer(imf, "y", readY, N, true, true));
      buffers.push_back(SourceDestBuffer(imf, "z", readZ, N, true, true));

      CompressedVectorReader reader = cv.reader(buffers);
      unsigned               count  = reader.read();
      reader.close();

      REQUIRE_EQ(N, count);

      for (size_t i = 0; i < N; ++i)
      {
        REQUIRE(std::abs(writeX[i] - readX[i]) < 1e-10);
        REQUIRE(std::abs(writeY[i] - readY[i]) < 1e-10);
        REQUIRE(std::abs(writeZ[i] - readZ[i]) < 1e-10);
      }

      imf.close();
    }
  }

  TEST_CASE("CompressedVectorReader isOpen")
  {
    TempFile tempFile;

    // Write file first
    {
      ImageFile     imf(tempFile.c_str(), "w");
      StructureNode root = imf.root();
      root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
      root.set("guid", StringNode(imf, "{00000000-0000-0000-0000-000000000105}"));

      StructureNode proto(imf);
      proto.set("value", IntegerNode(imf, 0));

      VectorNode codecs(imf, true);

      CompressedVectorNode cv(imf, proto, codecs);
      root.set("data", cv);

      int64_t                       data[3] = {1, 2, 3};
      std::vector<SourceDestBuffer> buffers;
      buffers.push_back(SourceDestBuffer(imf, "value", data, 3, true, true));

      CompressedVectorWriter writer = cv.writer(buffers);
      writer.write(3);
      writer.close();

      imf.close();
    }

    // Test isOpen
    {
      ImageFile     imf(tempFile.c_str(), "r");
      StructureNode root = imf.root();

      CompressedVectorNode cv(root.get("data"));

      int64_t                       data[3] = {0};
      std::vector<SourceDestBuffer> buffers;
      buffers.push_back(SourceDestBuffer(imf, "value", data, 3, true, true));

      CompressedVectorReader reader = cv.reader(buffers);

      REQUIRE(reader.isOpen());

      reader.close();

      REQUIRE(!reader.isOpen());

      imf.close();
    }
  }

  TEST_CASE("CompressedVectorReader seek throws not-implemented")
  {
    TempFile tempFile;

    const size_t         N = 5;
    std::vector<int64_t> writeData(N);
    for (size_t i = 0; i < N; ++i)
    {
      writeData[i] = static_cast<int64_t>(i * 10);
    }

    {
      ImageFile     imf(tempFile.c_str(), "w");
      StructureNode root = imf.root();
      root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
      root.set("guid", StringNode(imf, "{00000000-0000-0000-0000-000000000106}"));

      StructureNode proto(imf);
      proto.set("value", IntegerNode(imf, 0, 0, 1000));

      VectorNode           codecs(imf, true);
      CompressedVectorNode cv(imf, proto, codecs);
      root.set("data", cv);

      std::vector<SourceDestBuffer> buffers;
      buffers.push_back(SourceDestBuffer(imf, "value", writeData.data(), N, true, true));

      CompressedVectorWriter writer = cv.writer(buffers);
      writer.write(N);
      writer.close();

      imf.close();
    }

    {
      ImageFile     imf(tempFile.c_str(), "r");
      StructureNode root = imf.root();

      CompressedVectorNode cv(root.get("data"));

      int64_t                       readData[5] = {0};
      std::vector<SourceDestBuffer> buffers;
      buffers.push_back(SourceDestBuffer(imf, "value", readData, 5, true, true));

      CompressedVectorReader reader = cv.reader(buffers);
      REQUIRE_THROWS_AS(reader.seek(0), E57Exception);

      reader.close();
      imf.close();
    }
  }
}

TEST_CASE("CompressedVectorReader compressedVectorNode")
{
  TempFile tempFile;

  // Write file first
  {
    ImageFile     imf(tempFile.c_str(), "w");
    StructureNode root = imf.root();
    root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));

    StructureNode proto(imf);
    proto.set("value", IntegerNode(imf, 0));

    VectorNode codecs(imf, true);

    CompressedVectorNode cv(imf, proto, codecs);
    root.set("data", cv);

    int64_t                       data[3] = {1, 2, 3};
    std::vector<SourceDestBuffer> buffers;
    buffers.push_back(SourceDestBuffer(imf, "value", data, 3, true, true));

    CompressedVectorWriter writer = cv.writer(buffers);
    writer.write(3);
    writer.close();

    imf.close();
  }

  // Test compressedVectorNode
  {
    ImageFile     imf(tempFile.c_str(), "r");
    StructureNode root = imf.root();

    CompressedVectorNode cv(root.get("data"));

    int64_t                       data[3] = {0};
    std::vector<SourceDestBuffer> buffers;
    buffers.push_back(SourceDestBuffer(imf, "value", data, 3, true, true));

    CompressedVectorReader reader = cv.reader(buffers);

    CompressedVectorNode retrieved = reader.compressedVectorNode();
    REQUIRE_EQ(Node(cv), Node(retrieved));

    reader.close();
    imf.close();
  }
}

TEST_SUITE("SourceDestBuffer Tests")
{
  TEST_CASE("SourceDestBuffer construction with int64")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    int64_t          data[10] = {0};
    SourceDestBuffer sdb(imf, "testField", data, 10, true, true);

    REQUIRE_EQ("testField", sdb.pathName());
    REQUIRE_EQ(E57_INT64, sdb.memoryRepresentation());
    REQUIRE_EQ(10u, sdb.capacity());
    REQUIRE(sdb.doConversion());
    REQUIRE(sdb.doScaling());

    imf.close();
  }

  TEST_CASE("SourceDestBuffer construction with double")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    double           data[10] = {0.0};
    SourceDestBuffer sdb(imf, "floatField", data, 10, true, false);

    REQUIRE_EQ("floatField", sdb.pathName());
    REQUIRE_EQ(E57_REAL64, sdb.memoryRepresentation());
    REQUIRE_EQ(10u, sdb.capacity());
    REQUIRE(sdb.doConversion());
    REQUIRE(!sdb.doScaling());

    imf.close();
  }

  TEST_CASE("SourceDestBuffer construction with float")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    float            data[10] = {0.0f};
    SourceDestBuffer sdb(imf, "singleField", data, 10, true, true);

    REQUIRE_EQ(E57_REAL32, sdb.memoryRepresentation());

    imf.close();
  }

  TEST_CASE("SourceDestBuffer construction with int32")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    int32_t          data[10] = {0};
    SourceDestBuffer sdb(imf, "int32Field", data, 10, true, true);

    REQUIRE_EQ(E57_INT32, sdb.memoryRepresentation());

    imf.close();
  }

  TEST_CASE("SourceDestBuffer dump")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    int64_t          data[5] = {1, 2, 3, 4, 5};
    SourceDestBuffer sdb(imf, "dumpField", data, 5, true, true);

    std::stringstream ss;
    sdb.dump(0, ss);

    std::string output = ss.str();
    REQUIRE(!output.empty());

    imf.close();
  }

  TEST_CASE("SourceDestBuffer checkInvariant")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    double           data[10] = {0.0};
    SourceDestBuffer sdb(imf, "testField", data, 10, true, true);

    REQUIRE_NOTHROW(sdb.checkInvariant());

    imf.close();
  }
}

TEST_SUITE("CompressedVector Edge Cases")
{
  TEST_CASE("CompressedVector with large dataset")
  {
    TempFile tempFile;

    const size_t         N = 1000;
    std::vector<int64_t> writeData(N);
    std::vector<int64_t> readData(N);

    for (size_t i = 0; i < N; ++i)
    {
      writeData[i] = static_cast<int64_t>(i * 7);
    }

    {
      ImageFile     imf(tempFile.c_str(), "w");
      StructureNode root = imf.root();
      root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
      root.set("guid", StringNode(imf, "{00000000-0000-0000-000000000200}"));

      StructureNode proto(imf);
      proto.set("value", IntegerNode(imf, 0, 0, 10000));

      VectorNode codecs(imf, true);

      CompressedVectorNode cv(imf, proto, codecs);
      root.set("data", cv);

      std::vector<SourceDestBuffer> buffers;
      buffers.push_back(SourceDestBuffer(imf, "value", writeData.data(), N, true, true));

      CompressedVectorWriter writer = cv.writer(buffers);
      writer.write(N);
      writer.close();

      imf.close();
    }

    {
      ImageFile     imf(tempFile.c_str(), "r");
      StructureNode root = imf.root();

      CompressedVectorNode cv(root.get("data"));

      std::vector<SourceDestBuffer> buffers;
      buffers.push_back(SourceDestBuffer(imf, "value", readData.data(), N, true, true));

      CompressedVectorReader reader = cv.reader(buffers);
      unsigned               count  = reader.read();
      reader.close();

      REQUIRE_EQ(N, count);

      for (size_t i = 0; i < N; ++i)
      {
        REQUIRE_EQ(writeData[i], readData[i]);
      }

      imf.close();
    }
  }

  TEST_CASE("CompressedVector with mixed integer sizes")
  {
    TempFile tempFile;

    const size_t         N = 100;
    std::vector<int32_t> writeData(N);
    std::vector<int32_t> readData(N);

    for (size_t i = 0; i < N; ++i)
    {
      writeData[i] = static_cast<int32_t>(i - 50);
    }

    {
      ImageFile     imf(tempFile.c_str(), "w");
      StructureNode root = imf.root();
      root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
      root.set("guid", StringNode(imf, "{00000000-0000-0000-000000000201}"));

      StructureNode proto(imf);
      proto.set("value", IntegerNode(imf, 0, -100, 100));

      VectorNode codecs(imf, true);

      CompressedVectorNode cv(imf, proto, codecs);
      root.set("data", cv);

      std::vector<SourceDestBuffer> buffers;
      buffers.push_back(SourceDestBuffer(imf, "value", writeData.data(), N, true, true));

      CompressedVectorWriter writer = cv.writer(buffers);
      writer.write(N);
      writer.close();

      imf.close();
    }

    {
      ImageFile     imf(tempFile.c_str(), "r");
      StructureNode root = imf.root();

      CompressedVectorNode cv(root.get("data"));

      std::vector<SourceDestBuffer> buffers;
      buffers.push_back(SourceDestBuffer(imf, "value", readData.data(), N, true, true));

      CompressedVectorReader reader = cv.reader(buffers);
      unsigned               count  = reader.read();
      reader.close();

      REQUIRE_EQ(N, count);

      for (size_t i = 0; i < N; ++i)
      {
        REQUIRE_EQ(writeData[i], readData[i]);
      }

      imf.close();
    }
  }

  TEST_CASE("CompressedVector with float precision")
  {
    TempFile tempFile;

    const size_t       N = 50;
    std::vector<float> writeData(N);
    std::vector<float> readData(N);

    for (size_t i = 0; i < N; ++i)
    {
      writeData[i] = static_cast<float>(i) * 0.1f;
    }

    {
      ImageFile     imf(tempFile.c_str(), "w");
      StructureNode root = imf.root();
      root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
      root.set("guid", StringNode(imf, "{00000000-0000-0000-000000000202}"));

      StructureNode proto(imf);
      proto.set("value", FloatNode(imf, 0.0f, E57_SINGLE));

      VectorNode codecs(imf, true);

      CompressedVectorNode cv(imf, proto, codecs);
      root.set("data", cv);

      std::vector<SourceDestBuffer> buffers;
      buffers.push_back(SourceDestBuffer(imf, "value", writeData.data(), N, true, true));

      CompressedVectorWriter writer = cv.writer(buffers);
      writer.write(N);
      writer.close();

      imf.close();
    }

    {
      ImageFile     imf(tempFile.c_str(), "r");
      StructureNode root = imf.root();

      CompressedVectorNode cv(root.get("data"));

      std::vector<SourceDestBuffer> buffers;
      buffers.push_back(SourceDestBuffer(imf, "value", readData.data(), N, true, true));

      CompressedVectorReader reader = cv.reader(buffers);
      unsigned               count  = reader.read();
      reader.close();

      REQUIRE_EQ(N, count);

      for (size_t i = 0; i < N; ++i)
      {
        REQUIRE(std::abs(writeData[i] - readData[i]) < 1e-6f);
      }

      imf.close();
    }
  }

  TEST_CASE("CompressedVector seek throws not-implemented")
  {
    TempFile tempFile;

    const size_t         N = 10;
    std::vector<int64_t> writeData(N);
    for (size_t i = 0; i < N; ++i)
    {
      writeData[i] = static_cast<int64_t>(i);
    }

    {
      ImageFile     imf(tempFile.c_str(), "w");
      StructureNode root = imf.root();
      root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
      root.set("guid", StringNode(imf, "{00000000-0000-0000-0000-000000000203}"));

      StructureNode proto(imf);
      proto.set("value", IntegerNode(imf, 0, 0, 200));

      VectorNode           codecs(imf, true);
      CompressedVectorNode cv(imf, proto, codecs);
      root.set("data", cv);

      std::vector<SourceDestBuffer> buffers;
      buffers.push_back(SourceDestBuffer(imf, "value", writeData.data(), N, true, true));

      CompressedVectorWriter writer = cv.writer(buffers);
      writer.write(N);
      writer.close();

      imf.close();
    }

    {
      ImageFile     imf(tempFile.c_str(), "r");
      StructureNode root = imf.root();

      CompressedVectorNode cv(root.get("data"));

      int64_t                       readData[5] = {0};
      std::vector<SourceDestBuffer> buffers;
      buffers.push_back(SourceDestBuffer(imf, "value", readData, 5, true, true));

      CompressedVectorReader reader = cv.reader(buffers);
      REQUIRE_THROWS_AS(reader.seek(0), E57Exception);

      reader.close();
      imf.close();
    }
  }

  TEST_CASE("CompressedVector multiple writes")
  {
    TempFile tempFile;

    const size_t         N = 30;
    std::vector<int64_t> writeData1(N);
    std::vector<int64_t> writeData2(N);

    for (size_t i = 0; i < N; ++i)
    {
      writeData1[i] = static_cast<int64_t>(i);
      writeData2[i] = static_cast<int64_t>(i + 100);
    }

    {
      ImageFile     imf(tempFile.c_str(), "w");
      StructureNode root = imf.root();
      root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
      root.set("guid", StringNode(imf, "{00000000-0000-0000-000000000204}"));

      StructureNode proto(imf);
      proto.set("value1", IntegerNode(imf, 0));
      proto.set("value2", IntegerNode(imf, 0));

      VectorNode codecs(imf, true);

      CompressedVectorNode cv(imf, proto, codecs);
      root.set("data", cv);

      std::vector<SourceDestBuffer> buffers;
      buffers.push_back(SourceDestBuffer(imf, "value1", writeData1.data(), N, true, true));
      buffers.push_back(SourceDestBuffer(imf, "value2", writeData2.data(), N, true, true));

      CompressedVectorWriter writer = cv.writer(buffers);
      writer.write(N);
      writer.close();

      imf.close();
    }

    {
      ImageFile     imf(tempFile.c_str(), "r");
      StructureNode root = imf.root();

      CompressedVectorNode cv(root.get("data"));

      std::vector<int64_t> readData1(N);
      std::vector<int64_t> readData2(N);

      std::vector<SourceDestBuffer> buffers;
      buffers.push_back(SourceDestBuffer(imf, "value1", readData1.data(), N, true, true));
      buffers.push_back(SourceDestBuffer(imf, "value2", readData2.data(), N, true, true));

      CompressedVectorReader reader = cv.reader(buffers);
      unsigned               count  = reader.read();
      reader.close();

      REQUIRE_EQ(N, count);

      for (size_t i = 0; i < N; ++i)
      {
        REQUIRE_EQ(writeData1[i], readData1[i]);
        REQUIRE_EQ(writeData2[i], readData2[i]);
      }

      imf.close();
    }
  }
}
