/*
 * concurrent_parsing_test.cpp - Tests for thread-safe concurrent E57 file parsing
 *
 * Copyright (c) 2026 openE57 Contributors
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN

#include "test_utils.h"

#include <atomic>
#include <cstdint>
#include <future>
#include <string>
#include <thread>
#include <vector>

using namespace e57;
using e57::test::TempFile;

static void writeE57File(const std::string& path, int threadId)
{
  constexpr size_t N = 20;
  int64_t          writeData[N];
  for (size_t i = 0; i < N; ++i)
    writeData[i] = static_cast<int64_t>(threadId * 1000 + i);

  ImageFile     imf(path, "w");
  StructureNode root = imf.root();
  root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
  root.set("guid", StringNode(imf, "{00000000-0000-0000-0000-" + std::to_string(threadId) + "}"));

  StructureNode proto(imf);
  proto.set("value", IntegerNode(imf, 0, 0, 100000));

  VectorNode         codecs(imf, true);
  CompressedVectorNode cv(imf, proto, codecs);
  root.set("data", cv);

  std::vector<SourceDestBuffer> buffers;
  buffers.push_back(SourceDestBuffer(imf, "value", writeData, N, true, true));

  CompressedVectorWriter writer = cv.writer(buffers);
  writer.write(N);
  writer.close();

  imf.close();
}

static void readAndVerifyE57File(const std::string& path, int threadId)
{
  constexpr size_t   N = 20;
  int64_t            readData[N] = {0};

  ImageFile     imf(path, "r");
  StructureNode root = imf.root();

  CompressedVectorNode cv(root.get("data"));

  std::vector<SourceDestBuffer> buffers;
  buffers.push_back(SourceDestBuffer(imf, "value", readData, N, true, true));

  CompressedVectorReader reader = cv.reader(buffers);
  unsigned               count  = reader.read();
  reader.close();

  REQUIRE_EQ(N, count);

  for (size_t i = 0; i < N; ++i)
  {
    int64_t expected = static_cast<int64_t>(threadId * 1000 + i);
    REQUIRE_EQ(expected, readData[i]);
  }

  imf.close();
}

TEST_SUITE("Concurrent Parsing Tests")
{
  TEST_CASE("Multiple threads parse separate files concurrently")
  {
    constexpr int NUM_THREADS = 8;

    std::vector<TempFile>                      tempFiles;
    std::vector<std::future<void>>             futures;
    std::atomic<int>                           errorCount{0};
    std::vector<std::string>                   errorMessages(NUM_THREADS);

    tempFiles.reserve(NUM_THREADS);
    for (int i = 0; i < NUM_THREADS; ++i)
      tempFiles.emplace_back();

    for (int i = 0; i < NUM_THREADS; ++i)
    {
      futures.push_back(std::async(std::launch::async, [&tempFiles, &errorCount, &errorMessages, i]()
      {
        try
        {
          writeE57File(tempFiles[i].string(), i);
          readAndVerifyE57File(tempFiles[i].string(), i);
        }
        catch (const std::exception& e)
        {
          errorCount.fetch_add(1);
          errorMessages[i] = e.what();
        }
      }));
    }

    for (auto& f : futures)
      f.wait();

    for (int i = 0; i < NUM_THREADS; ++i)
    {
      if (!errorMessages[i].empty())
        FAIL("Thread ", i, " failed: ", errorMessages[i]);
    }

    REQUIRE_EQ(0, errorCount.load());
  }

  TEST_CASE("Multiple threads parse the same pre-written file concurrently")
  {
    constexpr int    NUM_THREADS = 8;
    constexpr size_t N           = 20;

    TempFile tempFile;

    {
      int64_t writeData[N];
      for (size_t i = 0; i < N; ++i)
        writeData[i] = static_cast<int64_t>(i * 7);

      ImageFile     imf(tempFile.c_str(), "w");
      StructureNode root = imf.root();
      root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
      root.set("guid", StringNode(imf, "{00000000-0000-0000-0000-000000009999}"));

      StructureNode proto(imf);
      proto.set("value", IntegerNode(imf, 0, 0, 1000));

      VectorNode         codecs(imf, true);
      CompressedVectorNode cv(imf, proto, codecs);
      root.set("data", cv);

      std::vector<SourceDestBuffer> buffers;
      buffers.push_back(SourceDestBuffer(imf, "value", writeData, N, true, true));

      CompressedVectorWriter writer = cv.writer(buffers);
      writer.write(N);
      writer.close();
      imf.close();
    }

    std::vector<std::future<void>> futures;
    std::atomic<int>               errorCount{0};
    std::vector<std::string>       errorMessages(NUM_THREADS);

    for (int i = 0; i < NUM_THREADS; ++i)
    {
      futures.push_back(std::async(std::launch::async, [&tempFile, &errorCount, &errorMessages, i]()
      {
        try
        {
          int64_t            readData[N] = {0};

          ImageFile     imf(tempFile.c_str(), "r");
          StructureNode root = imf.root();

          CompressedVectorNode cv(root.get("data"));

          std::vector<SourceDestBuffer> buffers;
          buffers.push_back(SourceDestBuffer(imf, "value", readData, N, true, true));

          CompressedVectorReader reader = cv.reader(buffers);
          unsigned               count  = reader.read();
          reader.close();

          if (count != N)
          {
            errorCount.fetch_add(1);
            errorMessages[i] = "count mismatch: expected " + std::to_string(N) + " got " + std::to_string(count);
            imf.close();
            return;
          }

          for (size_t j = 0; j < N; ++j)
          {
            int64_t expected = static_cast<int64_t>(j * 7);
            if (readData[j] != expected)
            {
              errorCount.fetch_add(1);
              errorMessages[i] = "data mismatch at index " + std::to_string(j) + ": expected " + std::to_string(expected) + " got " + std::to_string(readData[j]);
              break;
            }
          }

          imf.close();
        }
        catch (const std::exception& e)
        {
          errorCount.fetch_add(1);
          errorMessages[i] = e.what();
        }
      }));
    }

    for (auto& f : futures)
      f.wait();

    for (int i = 0; i < NUM_THREADS; ++i)
    {
      if (!errorMessages[i].empty())
        FAIL("Thread ", i, " failed: ", errorMessages[i]);
    }

    REQUIRE_EQ(0, errorCount.load());
  }

  TEST_CASE("Sequential open-parse-close across multiple threads")
  {
    constexpr int ITERATIONS = 20;

    TempFile tempFile;

    {
      constexpr size_t N = 5;
      int64_t          writeData[N] = {10, 20, 30, 40, 50};

      ImageFile     imf(tempFile.c_str(), "w");
      StructureNode root = imf.root();
      root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
      root.set("guid", StringNode(imf, "{00000000-0000-0000-0000-000000008888}"));

      StructureNode proto(imf);
      proto.set("value", IntegerNode(imf, 0, 0, 100));

      VectorNode         codecs(imf, true);
      CompressedVectorNode cv(imf, proto, codecs);
      root.set("data", cv);

      std::vector<SourceDestBuffer> buffers;
      buffers.push_back(SourceDestBuffer(imf, "value", writeData, N, true, true));

      CompressedVectorWriter writer = cv.writer(buffers);
      writer.write(N);
      writer.close();
      imf.close();
    }

    auto worker = [&tempFile]() -> bool
    {
      try
      {
        for (int i = 0; i < ITERATIONS; ++i)
        {
          constexpr size_t N = 5;
          int64_t          readData[N] = {0};

          ImageFile     imf(tempFile.c_str(), "r");
          StructureNode root = imf.root();
          CompressedVectorNode cv(root.get("data"));

          std::vector<SourceDestBuffer> buffers;
          buffers.push_back(SourceDestBuffer(imf, "value", readData, N, true, true));

          CompressedVectorReader reader = cv.reader(buffers);
          reader.read();
          reader.close();
          imf.close();

          int64_t expected[N] = {10, 20, 30, 40, 50};
          for (size_t j = 0; j < N; ++j)
          {
            if (readData[j] != expected[j])
              return false;
          }
        }
        return true;
      }
      catch (...)
      {
        return false;
      }
    };

    constexpr int        NUM_THREADS = 4;
    std::vector<std::future<bool>> futures;
    for (int i = 0; i < NUM_THREADS; ++i)
      futures.push_back(std::async(std::launch::async, worker));

    for (auto& f : futures)
      REQUIRE(f.get());
  }
}
