/*
 * datetime_utilities_test.cpp - Tests for DateTime utility functions
 *
 * Copyright (c) 2024 openE57 Contributors
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to do
 * so, all subject to the following:
 *
 * The above copyright notice in this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must be
 * included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works
 * are solely in the form of machine-executable object code generated by a
 * source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR
 * ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN

#include <doctest/doctest.h>
#include <openE57/openE57Simple.h>

#include <cmath>

using namespace e57;

TEST_SUITE("DateTime Utilities Tests")
{
  TEST_CASE("DateTime default construction")
  {
    DateTime dt;
    REQUIRE_EQ(0.0, dt.dateTimeValue);
    REQUIRE_EQ(0, dt.isAtomicClockReferenced);
  }

  TEST_CASE("DateTime SetCurrentGPSTime")
  {
    DateTime dt;
    dt.SetCurrentGPSTime();

    REQUIRE_GT(dt.dateTimeValue, 0.0);
    REQUIRE_EQ(0, dt.isAtomicClockReferenced);
  }

  TEST_CASE("DateTime SetUTCDateTime and GetUTCDateTime round-trip")
  {
    DateTime dt;

    int   year    = 2024;
    int   month   = 2; // 0-based: March
    int   day     = 5;
    int   hour    = 14;
    int   minute  = 30;
    float seconds = 45.5f;

    dt.SetUTCDateTime(year, month, day, hour, minute, seconds);

    REQUIRE_GT(dt.dateTimeValue, 0.0);

    int   read_year, read_month, read_day, read_hour, read_minute;
    float read_seconds;

    dt.GetUTCDateTime(read_year, read_month, read_day, read_hour, read_minute, read_seconds);

    REQUIRE_EQ(year, read_year);
    REQUIRE_EQ(month, read_month);
    REQUIRE_EQ(day, read_day);
    REQUIRE_EQ(hour, read_hour);
    REQUIRE_EQ(minute, read_minute);
    REQUIRE_EQ(seconds, doctest::Approx(read_seconds).epsilon(0.01));
  }

  TEST_CASE("DateTime with different dates")
  {
    DateTime dt1;
    dt1.SetUTCDateTime(2020, 0, 1, 0, 0, 0.0f);

    DateTime dt2;
    dt2.SetUTCDateTime(2024, 11, 31, 23, 59, 59.999f);

    REQUIRE_LT(dt1.dateTimeValue, dt2.dateTimeValue);
  }

  TEST_CASE("DateTime leap year handling")
  {
    DateTime dt;
    dt.SetUTCDateTime(2024, 1, 29, 12, 0, 0.0f);

    int   year, month, day, hour, minute;
    float seconds;
    dt.GetUTCDateTime(year, month, day, hour, minute, seconds);

    REQUIRE_EQ(2024, year);
    REQUIRE_EQ(1, month);
    REQUIRE_EQ(29, day);
    REQUIRE_EQ(12, hour);
    REQUIRE_EQ(0, minute);
  }

  TEST_CASE("DateTime boundary values")
  {
    DateTime dt1;
    dt1.SetUTCDateTime(1980, 0, 7, 0, 0, 0.0f);
    REQUIRE_GT(dt1.dateTimeValue, 0.0);

    DateTime dt2;
    dt2.SetUTCDateTime(2024, 11, 31, 23, 59, 59.999f);
    REQUIRE_GT(dt2.dateTimeValue, 0.0);
  }
}
