/*
 * e57_golden_test.cpp - End-to-end golden hash test for E57 write determinism
 *
 * Writes a fixed, fully deterministic E57 file using the Foundation API
 * (no auto-generated UUIDs, no timestamps), hashes the resulting bytes
 * with FNV-1a-64, and compares against a known expected value.  Any
 * regression in the binary layout will be caught here.
 *
 * Copyright (c) 2024 openE57 Contributors
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN

#include "test_utils.h"

#include <cstdint>
#include <fstream>
#include <iomanip>
#include <sstream>
#include <vector>

using namespace e57;
using e57::test::TempFile;

namespace
{

static constexpr size_t NUM_POINTS = 10;

// clang-format off
static constexpr double POINTS_X[NUM_POINTS] = {  0.0,  1.0,  0.0,  0.0,  1.0,  1.0,  0.0,  1.0,  0.5, -1.0 };
static constexpr double POINTS_Y[NUM_POINTS] = {  0.0,  0.0,  1.0,  0.0,  1.0,  0.0,  1.0,  1.0,  0.5, -1.0 };
static constexpr double POINTS_Z[NUM_POINTS] = {  0.0,  0.0,  0.0,  1.0,  0.0,  1.0,  1.0,  1.0,  0.5, -1.0 };
// clang-format on

static constexpr char FILE_GUID[] = "{FACE0001-BEEF-CAFE-DEAD-000000000001}";
static constexpr char SCAN_GUID[] = "{FACE0001-BEEF-CAFE-DEAD-000000000002}";

// No timestamps, no random UUIDs — every byte of the output is deterministic.
void writeDeterministicE57(const std::string& path)
{
  double x[NUM_POINTS];
  double y[NUM_POINTS];
  double z[NUM_POINTS];
  for (size_t i = 0; i < NUM_POINTS; ++i)
  {
    x[i] = POINTS_X[i];
    y[i] = POINTS_Y[i];
    z[i] = POINTS_Z[i];
  }

  ImageFile     imf(path.c_str(), "w");
  StructureNode root = imf.root();

  root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
  root.set("guid", StringNode(imf, FILE_GUID));

  StructureNode proto(imf);
  proto.set("cartesianX", FloatNode(imf, 0.0, FloatPrecision::E57_DOUBLE));
  proto.set("cartesianY", FloatNode(imf, 0.0, FloatPrecision::E57_DOUBLE));
  proto.set("cartesianZ", FloatNode(imf, 0.0, FloatPrecision::E57_DOUBLE));

  VectorNode           codecs(imf, true);
  CompressedVectorNode points(imf, proto, codecs);

  VectorNode    data3D(imf, true);
  StructureNode scan(imf);
  scan.set("guid", StringNode(imf, SCAN_GUID));
  scan.set("points", points);
  data3D.append(scan);
  root.set("data3D", data3D);

  std::vector<SourceDestBuffer> bufs;
  bufs.push_back(SourceDestBuffer(imf, "cartesianX", x, NUM_POINTS, true, true));
  bufs.push_back(SourceDestBuffer(imf, "cartesianY", y, NUM_POINTS, true, true));
  bufs.push_back(SourceDestBuffer(imf, "cartesianZ", z, NUM_POINTS, true, true));

  CompressedVectorWriter writer = points.writer(bufs);
  writer.write(NUM_POINTS);
  writer.close();

  imf.close();
}

// FNV-1a 64-bit: offset_basis=14695981039346656037, prime=1099511628211
uint64_t fnv1a64(const std::vector<uint8_t>& data)
{
  uint64_t hash = 14695981039346656037ULL;
  for (uint8_t byte : data)
  {
    hash ^= static_cast<uint64_t>(byte);
    hash *= 1099511628211ULL;
  }
  return hash;
}

std::vector<uint8_t> readFileBytes(const std::string& path)
{
  std::ifstream file(path, std::ios::binary | std::ios::ate);
  REQUIRE(file.is_open());
  const std::streamsize size = file.tellg();
  file.seekg(0);
  std::vector<uint8_t> buf(static_cast<size_t>(size));
  file.read(reinterpret_cast<char*>(buf.data()), size);
  return buf;
}

} // namespace

TEST_SUITE("E57 Golden File Tests")
{
  // To regenerate EXPECTED_HASH after an intentional format change:
  //   1. Set EXPECTED_HASH = 0x0 and rebuild.
  //   2. Run: ./e57_golden_test-d --test-case="*hash*"
  //   3. Copy the printed hash into EXPECTED_HASH and rebuild.
  TEST_CASE("Deterministic XYZ point cloud matches known file hash")
  {
    static constexpr uint64_t EXPECTED_HASH = 0x8E230DA0FE209BCCULL;

    TempFile tempFile;
    REQUIRE_NOTHROW(writeDeterministicE57(tempFile.string()));
    REQUIRE(tempFile.exists());

    const std::vector<uint8_t> bytes  = readFileBytes(tempFile.string());
    const uint64_t             actual = fnv1a64(bytes);

    std::ostringstream oss;
    oss << "0x" << std::uppercase << std::hex << std::setw(16) << std::setfill('0') << actual;
    INFO("Actual hash: ", oss.str());

    if (EXPECTED_HASH == 0x0)
    {
      MESSAGE("EXPECTED_HASH not set. Computed hash: ", oss.str());
      MESSAGE("Set EXPECTED_HASH in e57_golden_test.cpp to lock in this value.");
    }
    else
    {
      CHECK_EQ(actual, EXPECTED_HASH);
    }
  }

  TEST_CASE("Deterministic XYZ point cloud survives write-read round-trip")
  {
    TempFile tempFile;
    REQUIRE_NOTHROW(writeDeterministicE57(tempFile.string()));
    REQUIRE(tempFile.exists());

    double readX[NUM_POINTS] = {};
    double readY[NUM_POINTS] = {};
    double readZ[NUM_POINTS] = {};

    {
      ImageFile imf(tempFile.c_str(), "r");

      VectorNode    data3D(imf.root().get("data3D"));
      StructureNode scan(data3D.get(0));

      CompressedVectorNode points(scan.get("points"));
      REQUIRE_EQ(static_cast<int64_t>(NUM_POINTS), points.childCount());

      std::vector<SourceDestBuffer> bufs;
      bufs.push_back(SourceDestBuffer(imf, "cartesianX", readX, NUM_POINTS, true, true));
      bufs.push_back(SourceDestBuffer(imf, "cartesianY", readY, NUM_POINTS, true, true));
      bufs.push_back(SourceDestBuffer(imf, "cartesianZ", readZ, NUM_POINTS, true, true));

      CompressedVectorReader reader = points.reader(bufs);
      const unsigned         count  = reader.read();
      reader.close();

      REQUIRE_EQ(NUM_POINTS, count);
      imf.close();
    }

    for (size_t i = 0; i < NUM_POINTS; ++i)
    {
      REQUIRE_EQ(POINTS_X[i], readX[i]);
      REQUIRE_EQ(POINTS_Y[i], readY[i]);
      REQUIRE_EQ(POINTS_Z[i], readZ[i]);
    }
  }

  TEST_CASE("Deterministic E57 file preserves metadata fields")
  {
    TempFile tempFile;
    REQUIRE_NOTHROW(writeDeterministicE57(tempFile.string()));

    ImageFile     imf(tempFile.c_str(), "r");
    StructureNode root = imf.root();

    REQUIRE(root.isDefined("formatName"));
    REQUIRE_EQ(std::string(FILE_GUID), StringNode(root.get("guid")).value());

    VectorNode    data3D(root.get("data3D"));
    StructureNode scan(data3D.get(0));
    REQUIRE_EQ(std::string(SCAN_GUID), StringNode(scan.get("guid")).value());

    imf.close();
  }
}
