/*
 * error_handling_test.cpp - Tests for error handling and file corruption scenarios
 *
 * Copyright (c) 2024 openE57 Contributors
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The above copyright notice in this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must be
 * included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works
 * are solely in the form of machine-executable object code generated by a
 * source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN

#include "test_utils.h"

#include <cstdint>
#include <vector>

using namespace e57;
using e57::test::TempFile;

TEST_SUITE("File Corruption Tests")
{
  TEST_CASE("Reading non-existent file throws exception")
  {
    REQUIRE_THROWS_AS(ImageFile("/nonexistent/path/file.e57", "r"), E57Exception);
  }

  TEST_CASE("Opening corrupted file throws exception")
  {
    TempFile tempFile;
    e57::test::corruptBinaryFile(tempFile.string());

    REQUIRE_THROWS_AS(ImageFile(tempFile.c_str(), "r"), E57Exception);
  }

  TEST_CASE("Writing to invalid path throws exception")
  {
    REQUIRE_THROWS_AS(ImageFile("/invalid/path/that/does/not/exist/file.e57", "w"), E57Exception);
  }

  TEST_CASE("Opening file with invalid mode throws exception")
  {
    TempFile tempFile;

    REQUIRE_THROWS_AS(ImageFile(tempFile.c_str(), "x"), E57Exception);
  }

  TEST_CASE("Reading from file opened in write mode throws exception")
  {
    TempFile tempFile;

    ImageFile     imf(tempFile.c_str(), "w");
    StructureNode root = imf.root();
    root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
    root.set("guid", StringNode(imf, "{00000000-0000-0000-000000000001}"));

    REQUIRE_THROWS_AS(CompressedVectorNode(root.get("data")), E57Exception);

    imf.close();
  }

  TEST_CASE("Accessing nodes after file close throws exception")
  {
    TempFile tempFile;

    ImageFile imf(tempFile.c_str(), "w");
    imf.close();

    REQUIRE_THROWS_AS(imf.root(), E57Exception);
  }
}

TEST_SUITE("Invalid Node Operations")
{
  TEST_CASE("Setting duplicate field names throws exception")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    StructureNode s(imf);
    s.set("field", IntegerNode(imf, 1));

    REQUIRE_THROWS_AS(s.set("field", IntegerNode(imf, 2)), E57Exception);

    imf.close();
  }

  TEST_CASE("Accessing non-existent field throws exception")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    StructureNode s(imf);
    s.set("field1", IntegerNode(imf, 1));

    REQUIRE_THROWS_AS(s.get("nonexistent"), E57Exception);

    imf.close();
  }

  TEST_CASE("Adding incompatible type to homogeneous vector throws exception")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    VectorNode v(imf, false);
    v.append(IntegerNode(imf, 1));

    REQUIRE_THROWS_AS(v.append(FloatNode(imf, 1.0)), E57Exception);

    imf.close();
  }

  TEST_CASE("Accessing out-of-bounds vector element throws exception")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    VectorNode v(imf, false);
    v.append(IntegerNode(imf, 1));

    REQUIRE_THROWS_AS(v.get(1), E57Exception);
    REQUIRE_THROWS_AS(v.get(-1), E57Exception);

    imf.close();
  }

  TEST_CASE("Reading from CompressedVector with mismatched buffer throws exception")
  {
    TempFile tempFile;

    {
      ImageFile     imf(tempFile.c_str(), "w");
      StructureNode root = imf.root();
      root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
      root.set("guid", StringNode(imf, "{00000000-0000-0000-000000000002}"));

      StructureNode proto(imf);
      proto.set("x", IntegerNode(imf, 0));

      VectorNode codecs(imf, true);

      CompressedVectorNode cv(imf, proto, codecs);
      root.set("data", cv);

      imf.close();
    }

    ImageFile     imf(tempFile.c_str(), "r");
    StructureNode root = imf.root();

    CompressedVectorNode cv(root.get("data"));

    int64_t                       data[10] = {0};
    std::vector<SourceDestBuffer> buffers;
    buffers.push_back(SourceDestBuffer(imf, "y", data, 10, true, true));

    REQUIRE_THROWS_AS(cv.reader(buffers), E57Exception);

    imf.close();
  }
}

TEST_SUITE("Buffer Management Errors")
{
  TEST_CASE("Writing with invalid buffer size throws exception")
  {
    TempFile tempFile;

    ImageFile     imf(tempFile.c_str(), "w");
    StructureNode root = imf.root();
    root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
    root.set("guid", StringNode(imf, "{00000000-0000-0000-000000000003}"));

    StructureNode proto(imf);
    proto.set("value", IntegerNode(imf, 0));

    VectorNode codecs(imf, true);

    CompressedVectorNode cv(imf, proto, codecs);
    root.set("data", cv);

    int64_t                       data[5] = {1, 2, 3, 4, 5};
    std::vector<SourceDestBuffer> buffers;
    buffers.push_back(SourceDestBuffer(imf, "value", data, 5, true, true));

    CompressedVectorWriter writer = cv.writer(buffers);
    writer.write(5);

    REQUIRE_THROWS_AS(writer.write(1000), E57Exception);

    writer.close();
    imf.close();
  }

  TEST_CASE("Reading after writer close throws exception")
  {
    TempFile tempFile;

    {
      ImageFile     imf(tempFile.c_str(), "w");
      StructureNode root = imf.root();
      root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
      root.set("guid", StringNode(imf, "{00000000-0000-0000-000000000004}"));

      StructureNode proto(imf);
      proto.set("value", IntegerNode(imf, 0));

      VectorNode codecs(imf, true);

      CompressedVectorNode cv(imf, proto, codecs);
      root.set("data", cv);

      int64_t                       data[5] = {1, 2, 3, 4, 5};
      std::vector<SourceDestBuffer> buffers;
      buffers.push_back(SourceDestBuffer(imf, "value", data, 5, true, true));

      CompressedVectorWriter writer = cv.writer(buffers);
      writer.write(5);
      writer.close();

      REQUIRE_THROWS_AS(writer.write(1), E57Exception);

      imf.close();
    }
  }

  TEST_CASE("Seeking to invalid position throws exception")
  {
    TempFile tempFile;

    {
      ImageFile     imf(tempFile.c_str(), "w");
      StructureNode root = imf.root();
      root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
      root.set("guid", StringNode(imf, "{00000000-0000-0000-000000000005}"));

      StructureNode proto(imf);
      proto.set("value", IntegerNode(imf, 0));

      VectorNode codecs(imf, true);

      CompressedVectorNode cv(imf, proto, codecs);
      root.set("data", cv);

      int64_t                       data[5] = {1, 2, 3, 4, 5};
      std::vector<SourceDestBuffer> buffers;
      buffers.push_back(SourceDestBuffer(imf, "value", data, 5, true, true));

      CompressedVectorWriter writer = cv.writer(buffers);
      writer.write(5);
      writer.close();

      imf.close();
    }

    ImageFile     imf(tempFile.c_str(), "r");
    StructureNode root = imf.root();

    CompressedVectorNode cv(root.get("data"));

    int64_t                       data[5] = {0};
    std::vector<SourceDestBuffer> buffers;
    buffers.push_back(SourceDestBuffer(imf, "value", data, 5, true, true));

    CompressedVectorReader reader = cv.reader(buffers);

    REQUIRE_THROWS_AS(reader.seek(1000), E57Exception);

    reader.close();
    imf.close();
  }
}

TEST_SUITE("Integer Overflow Tests")
{
  TEST_CASE("IntegerNode with value outside bounds throws exception")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    REQUIRE_NOTHROW(IntegerNode(imf, 50, 0, 100));
    REQUIRE_THROWS_AS(IntegerNode(imf, 150, 0, 100), E57Exception);
    REQUIRE_THROWS_AS(IntegerNode(imf, -50, 0, 100), E57Exception);

    imf.close();
  }

  TEST_CASE("ScaledIntegerNode with value outside bounds throws exception")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    REQUIRE_NOTHROW(ScaledIntegerNode(imf, static_cast<int64_t>(50), static_cast<int64_t>(0), static_cast<int64_t>(100), 0.01, 0.0));
    REQUIRE_THROWS_AS(ScaledIntegerNode(imf, static_cast<int64_t>(150), static_cast<int64_t>(0), static_cast<int64_t>(100), 0.01, 0.0), E57Exception);

    imf.close();
  }
}

TEST_SUITE("Blob Operations Errors")
{
  TEST_CASE("Reading beyond blob bounds throws exception")
  {
    TempFile tempFile;

    {
      ImageFile     imf(tempFile.c_str(), "w");
      StructureNode root = imf.root();
      root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
      root.set("guid", StringNode(imf, "{00000000-0000-0000-000000000006}"));

      BlobNode blob(imf, 100);
      root.set("testBlob", blob);

      std::vector<uint8_t> data(100, 0);
      blob.write(data.data(), 0, 100);

      imf.close();
    }

    ImageFile     imf(tempFile.c_str(), "r");
    StructureNode root = imf.root();

    BlobNode blob(root.get("testBlob"));

    std::vector<uint8_t> data(100);

    REQUIRE_THROWS_AS(blob.read(data.data(), 50, 100), E57Exception);
    REQUIRE_THROWS_AS(blob.read(data.data(), 0, 200), E57Exception);

    imf.close();
  }

  TEST_CASE("Writing beyond blob bounds throws exception")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    BlobNode blob(imf, 100);

    std::vector<uint8_t> data(100, 0);

    REQUIRE_THROWS_AS(blob.write(data.data(), 50, 100), E57Exception);
    REQUIRE_THROWS_AS(blob.write(data.data(), 0, 200), E57Exception);

    imf.close();
  }
}
