/*
 * exception_utilities_test.cpp - Tests for E57Exception and E57Utilities
 *
 * Copyright (c) 2024 openE57 Contributors
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN

#include "test_utils.h"

#include <cstdint>

using namespace e57;
using e57::test::TempFile;

TEST_SUITE("E57Exception Tests")
{
  TEST_CASE("E57Exception construction with error code")
  {
    E57Exception ex(E57_ERROR_BAD_API_ARGUMENT, "Test error message");

    REQUIRE_EQ(E57_ERROR_BAD_API_ARGUMENT, ex.errorCode());
  }

  TEST_CASE("E57Exception construction with context")
  {
    std::string  context = "Invalid argument provided";
    E57Exception ex(E57_ERROR_BAD_API_ARGUMENT, context);

    REQUIRE_EQ(context, ex.context());
  }

  TEST_CASE("E57Exception construction with source location")
  {
    E57Exception ex(E57_ERROR_INTERNAL, "Internal error", "test.cpp", 42, "testFunction");

    REQUIRE_EQ("test.cpp", ex.sourceFileName());
    REQUIRE_EQ("testFunction", ex.sourceFunctionName());
    REQUIRE_EQ(42, ex.sourceLineNumber());
  }

  TEST_CASE("E57Exception what returns message")
  {
    E57Exception ex(E57_ERROR_BAD_API_ARGUMENT, "Test error");

    const char* what = ex.what();
    REQUIRE(what != nullptr);
    REQUIRE(std::string(what).length() > 0);
  }

  TEST_CASE("E57Exception report outputs to stream")
  {
    E57Exception ex(E57_ERROR_BAD_API_ARGUMENT, "Test error for report");

    std::stringstream ss;
    ex.report(nullptr, 0, nullptr, ss);

    std::string output = ss.str();
    REQUIRE(!output.empty());
  }

  TEST_CASE("E57Exception caught by std::exception")
  {
    bool caught = false;

    try
    {
      throw E57Exception(E57_ERROR_INTERNAL, "Test");
    }
    catch (const std::exception& e)
    {
      caught = true;
    }

    REQUIRE(caught);
  }

  TEST_CASE("E57Exception error codes are distinct")
  {
    REQUIRE(E57_SUCCESS != E57_ERROR_BAD_API_ARGUMENT);
    REQUIRE(E57_ERROR_BAD_API_ARGUMENT != E57_ERROR_FILE_IS_READ_ONLY);
    REQUIRE(E57_ERROR_OPEN_FAILED != E57_ERROR_CLOSE_FAILED);
  }
}

TEST_SUITE("E57Utilities Tests")
{
  TEST_CASE("E57Utilities getVersions returns valid structure")
  {
    E57Utilities util;
    int          astmMajor = 0;
    int          astmMinor = 0;
    ustring      libraryId;

    util.getVersions(astmMajor, astmMinor, libraryId);

    REQUIRE(astmMajor >= 0);
    REQUIRE(astmMinor >= 0);
    REQUIRE(libraryId.length() > 0);
  }

  TEST_CASE("E57Utilities getVersion returns structure")
  {
    E57Utilities util;
    VersionInfo  versionInfo = util.getVersion();

    REQUIRE(versionInfo.major >= 0);
    REQUIRE(versionInfo.minor >= 0);
    REQUIRE(versionInfo.id.length() > 0);
  }

  TEST_CASE("E57Utilities errorCodeToString for success")
  {
    E57Utilities util;
    std::string  msg = util.errorCodeToString(E57_SUCCESS);

    REQUIRE(!msg.empty());
  }

  TEST_CASE("E57Utilities errorCodeToString for errors")
  {
    E57Utilities util;

    std::string badArg = util.errorCodeToString(E57_ERROR_BAD_API_ARGUMENT);
    REQUIRE(!badArg.empty());

    std::string fileNotFound = util.errorCodeToString(E57_ERROR_OPEN_FAILED);
    REQUIRE(!fileNotFound.empty());

    std::string internalErr = util.errorCodeToString(E57_ERROR_INTERNAL);
    REQUIRE(!internalErr.empty());
  }

  TEST_CASE("E57Utilities errorCodeToString for all error codes")
  {
    E57Utilities util;

    // Test a sample of error codes
    ErrorCode codes[] = {E57_SUCCESS,
                         E57_ERROR_BAD_CV_HEADER,
                         E57_ERROR_BAD_CV_PACKET,
                         E57_ERROR_CHILD_INDEX_OUT_OF_BOUNDS,
                         E57_ERROR_SET_TWICE,
                         E57_ERROR_HOMOGENEOUS_VIOLATION,
                         E57_ERROR_VALUE_NOT_REPRESENTABLE,
                         E57_ERROR_SCALED_VALUE_NOT_REPRESENTABLE,
                         E57_ERROR_REAL64_TOO_LARGE,
                         E57_ERROR_EXPECTING_NUMERIC,
                         E57_ERROR_EXPECTING_USTRING,
                         E57_ERROR_INTERNAL,
                         E57_ERROR_BAD_XML_FORMAT,
                         E57_ERROR_XML_PARSER,
                         E57_ERROR_BAD_API_ARGUMENT,
                         E57_ERROR_FILE_IS_READ_ONLY,
                         E57_ERROR_BAD_CHECKSUM,
                         E57_ERROR_OPEN_FAILED,
                         E57_ERROR_CLOSE_FAILED,
                         E57_ERROR_READ_FAILED,
                         E57_ERROR_WRITE_FAILED,
                         E57_ERROR_LSEEK_FAILED,
                         E57_ERROR_PATH_UNDEFINED,
                         E57_ERROR_BAD_BUFFER,
                         E57_ERROR_NO_BUFFER_FOR_ELEMENT,
                         E57_ERROR_BUFFER_SIZE_MISMATCH,
                         E57_ERROR_BUFFER_DUPLICATE_PATHNAME,
                         E57_ERROR_BAD_FILE_SIGNATURE,
                         E57_ERROR_UNKNOWN_FILE_VERSION,
                         E57_ERROR_BAD_FILE_LENGTH,
                         E57_ERROR_XML_PARSER_INIT,
                         E57_ERROR_DUPLICATE_NAMESPACE_PREFIX,
                         E57_ERROR_DUPLICATE_NAMESPACE_URI,
                         E57_ERROR_BAD_PROTOTYPE,
                         E57_ERROR_BAD_CODECS,
                         E57_ERROR_VALUE_OUT_OF_BOUNDS,
                         E57_ERROR_CONVERSION_REQUIRED,
                         E57_ERROR_BAD_PATH_NAME,
                         E57_ERROR_NOT_IMPLEMENTED,
                         E57_ERROR_BAD_NODE_DOWNCAST,
                         E57_ERROR_WRITER_NOT_OPEN,
                         E57_ERROR_READER_NOT_OPEN,
                         E57_ERROR_NODE_UNATTACHED,
                         E57_ERROR_ALREADY_HAS_PARENT,
                         E57_ERROR_DIFFERENT_DEST_IMAGEFILE,
                         E57_ERROR_IMAGEFILE_NOT_OPEN,
                         E57_ERROR_BUFFERS_NOT_COMPATIBLE,
                         E57_ERROR_TOO_MANY_WRITERS,
                         E57_ERROR_TOO_MANY_READERS,
                         E57_ERROR_BAD_CONFIGURATION,
                         E57_ERROR_INVARIANCE_VIOLATION};

    for (ErrorCode code : codes)
    {
      std::string msg = util.errorCodeToString(code);
      REQUIRE(!msg.empty());
    }
  }
}

TEST_SUITE("Error Handling Integration Tests")
{
  TEST_CASE("Opening non-existent file throws exception")
  {
    REQUIRE_THROWS_AS(ImageFile("/nonexistent/path/file.e57", "r"), E57Exception);
  }

  TEST_CASE("Invalid mode throws exception")
  {
    TempFile tempFile;
    REQUIRE_THROWS_AS(ImageFile(tempFile.c_str(), "invalid_mode"), E57Exception);
  }

  TEST_CASE("Reading from write-only file throws exception")
  {
    TempFile      tempFile;
    ImageFile     imf(tempFile.c_str(), "w");
    StructureNode root = imf.root();

    // Attempt to read from write-only file should throw
    REQUIRE_THROWS_AS(root.get("/nonexistent"), E57Exception);

    imf.close();
  }

  TEST_CASE("CompressedVectorWriter on read-only file throws exception")
  {
    TempFile tempFile;

    {
      ImageFile     imfWrite(tempFile.c_str(), "w");
      StructureNode root = imfWrite.root();
      root.set("formatName", StringNode(imfWrite, "ASTM E57 3D Imaging Data File"));
      root.set("guid", StringNode(imfWrite, "{00000000-0000-0000-0000-000000000200}"));

      StructureNode proto(imfWrite);
      proto.set("value", IntegerNode(imfWrite, 0));
      VectorNode           codecs(imfWrite, true);
      CompressedVectorNode cv(imfWrite, proto, codecs);
      root.set("data", cv);

      int64_t                       dummy[1] = {0};
      std::vector<SourceDestBuffer> bufs;
      bufs.push_back(SourceDestBuffer(imfWrite, "value", dummy, 1));
      CompressedVectorWriter writer = cv.writer(bufs);
      writer.write(0);
      writer.close();

      imfWrite.close();
    }

    ImageFile     imf(tempFile.c_str(), "r");
    StructureNode root = imf.root();

    CompressedVectorNode cv(root.get("data"));

    int64_t                       dummy[1] = {0};
    std::vector<SourceDestBuffer> bufs;
    bufs.push_back(SourceDestBuffer(imf, "value", dummy, 1));

    REQUIRE_THROWS_AS(cv.writer(bufs), E57Exception);

    imf.close();
  }

  TEST_CASE("Accessing undefined field throws exception")
  {
    TempFile      tempFile;
    ImageFile     imf(tempFile.c_str(), "w");
    StructureNode s(imf);

    REQUIRE_THROWS_AS(s.get("undefinedField"), E57Exception);

    imf.close();
  }

  TEST_CASE("VectorNode out of bounds access throws exception")
  {
    TempFile   tempFile;
    ImageFile  imf(tempFile.c_str(), "w");
    VectorNode v(imf, false);
    v.append(IntegerNode(imf, 1));

    REQUIRE_THROWS_AS(v.get(10), E57Exception);

    imf.close();
  }

  TEST_CASE("Type mismatch downcast throws exception")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    StructureNode s(imf);
    s.set("intField", IntegerNode(imf, 42));

    Node n = s.get("intField");

    // Try to cast IntegerNode to FloatNode (should fail)
    REQUIRE_THROWS_AS(FloatNode f(n), E57Exception);

    imf.close();
  }

  TEST_CASE("Homogeneous vector type violation throws exception")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    VectorNode v(imf, false); // homogeneous
    v.append(IntegerNode(imf, 1));

    // Try to add different type to homogeneous vector
    REQUIRE_THROWS_AS(v.append(FloatNode(imf, 2.0)), E57Exception);

    imf.close();
  }

  TEST_CASE("Set twice on same field throws exception")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    StructureNode s(imf);
    s.set("field", IntegerNode(imf, 1));

    // Setting same field twice should throw
    REQUIRE_THROWS_AS(s.set("field", IntegerNode(imf, 2)), E57Exception);

    imf.close();
  }
}

TEST_SUITE("Node Type Tests")
{
  TEST_CASE("NodeType enum values are correct")
  {
    REQUIRE_EQ(1, static_cast<int>(E57_STRUCTURE));
    REQUIRE_EQ(2, static_cast<int>(E57_VECTOR));
    REQUIRE_EQ(3, static_cast<int>(E57_COMPRESSED_VECTOR));
    REQUIRE_EQ(4, static_cast<int>(E57_INTEGER));
    REQUIRE_EQ(5, static_cast<int>(E57_SCALED_INTEGER));
    REQUIRE_EQ(6, static_cast<int>(E57_FLOAT));
    REQUIRE_EQ(7, static_cast<int>(E57_STRING));
    REQUIRE_EQ(8, static_cast<int>(E57_BLOB));
  }

  TEST_CASE("FloatPrecision enum values are correct")
  {
    REQUIRE_EQ(1, static_cast<int>(E57_SINGLE));
    REQUIRE_EQ(2, static_cast<int>(E57_DOUBLE));
  }
}

TEST_SUITE("Node Common Methods Tests")
{
  TEST_CASE("Node type method returns correct type")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    IntegerNode i(imf, 42);
    REQUIRE_EQ(E57_INTEGER, Node(i).type());

    FloatNode f(imf, 3.14);
    REQUIRE_EQ(E57_FLOAT, Node(f).type());

    StringNode s(imf, "test");
    REQUIRE_EQ(E57_STRING, Node(s).type());

    StructureNode st(imf);
    REQUIRE_EQ(E57_STRUCTURE, Node(st).type());

    VectorNode v(imf, true);
    REQUIRE_EQ(E57_VECTOR, Node(v).type());

    imf.close();
  }

  TEST_CASE("Node isRoot returns correct value")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    StructureNode root = imf.root();
    REQUIRE(root.isRoot());

    StructureNode child(imf);
    REQUIRE(child.isRoot());

    root.set("child", child);
    REQUIRE(!child.isRoot());

    imf.close();
  }

  TEST_CASE("Node destImageFile returns correct ImageFile")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    IntegerNode node(imf, 42);
    REQUIRE_EQ(imf, node.destImageFile());

    imf.close();
  }

  TEST_CASE("Node elementName returns correct name when attached")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    StructureNode parent(imf);
    IntegerNode   child(imf, 42);

    parent.set("myElement", child);

    REQUIRE_EQ("myElement", child.elementName());

    imf.close();
  }
}
