/*
 * image2d_io_test.cpp - Comprehensive Image2D I/O tests for Simple API
 *
 * Copyright (c) 2024 openE57 Contributors
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to do
 * so, all subject to the following:
 *
 * The above copyright notice in this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must be
 * included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works
 * are solely in the form of machine-executable object code generated by a
 * source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUT THE SOFTWARE BE LIABLE FOR
 * ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN

#include "test_utils.h"

using namespace e57;
using e57::test::TempFile;

namespace
{

std::vector<uint8_t> createTestJPEG()
{
  return {0xFF, 0xD8, 0xFF, 0xE0, 0x00, 0x10, 0x4A, 0x46, 0x49, 0x46, 0x00, 0x01, 0x01, 0x00, 0x00, 0x01, 0x00, 0x01, 0x00, 0x00, 0xFF, 0xDB, 0x00, 0x43, 0x00,
          0x08, 0x06, 0x06, 0x07, 0x06, 0x05, 0x08, 0x07, 0x07, 0x07, 0x09, 0x09, 0x08, 0x0A, 0x0C, 0x14, 0x0D, 0x0C, 0x0B, 0x0B, 0x0C, 0x19, 0x12, 0x13, 0x0F,
          0x14, 0x1D, 0x1A, 0x1F, 0x1E, 0x1D, 0x1A, 0x1C, 0x1C, 0x20, 0x24, 0x2E, 0x27, 0x20, 0x22, 0x2C, 0x23, 0x1C, 0x1C, 0x28, 0x37, 0x29, 0x2C, 0x30, 0x31,
          0x34, 0x34, 0x34, 0x1F, 0x27, 0x39, 0x3D, 0x38, 0x32, 0x3C, 0x2E, 0x33, 0x34, 0x32, 0xFF, 0xC0, 0x00, 0x0B, 0x08, 0x00, 0x01, 0x00, 0x01, 0x01, 0x01,
          0x11, 0x00, 0xFF, 0xC4, 0x00, 0x1F, 0x00, 0x00, 0x01, 0x05, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01,
          0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0xFF, 0xC4, 0x00, 0xB5, 0x10, 0x00, 0x02, 0x01, 0x03, 0x03, 0x02, 0x04, 0x03, 0x05, 0x05,
          0x04, 0x04, 0x00, 0x00, 0x01, 0x7D, 0x01, 0x02, 0x03, 0x00, 0x04, 0x11, 0x05, 0x12, 0x21, 0x31, 0x41, 0x06, 0x13, 0x51, 0x61, 0x07, 0x22, 0x71, 0x14,
          0x32, 0x81, 0x91, 0xA1, 0x08, 0x23, 0x42, 0xB1, 0xC1, 0x15, 0x52, 0xD1, 0xF0, 0x24, 0x33, 0x62, 0x72, 0x82, 0x09, 0x0A, 0x16, 0x17, 0x18, 0x19, 0x1A,
          0x25, 0x26, 0x27, 0x28, 0x29, 0x2A, 0x34, 0x35, 0x36, 0x37, 0x38, 0x39, 0x3A, 0x43, 0x44, 0x45, 0x46, 0x47, 0x48, 0x49, 0x4A, 0x53, 0x54, 0x55, 0x56,
          0x57, 0x58, 0x59, 0x5A, 0x63, 0x64, 0x65, 0x66, 0x67, 0x68, 0x69, 0x6A, 0x73, 0x74, 0x75, 0x76, 0x77, 0x78, 0x79, 0x7A, 0x83, 0x84, 0x85, 0x86, 0x87,
          0x88, 0x89, 0x8A, 0x92, 0x93, 0x94, 0x95, 0x96, 0x97, 0x98, 0x99, 0x9A, 0xA2, 0xA3, 0xA4, 0xA5, 0xA6, 0xA7, 0xA8, 0xA9, 0xAA, 0xB2, 0xB3, 0xB4, 0xB5,
          0xB6, 0xB7, 0xB8, 0xB9, 0xBA, 0xC2, 0xC3, 0xC4, 0xC5, 0xC6, 0xC7, 0xC8, 0xC9, 0xCA, 0xD2, 0xD3, 0xD4, 0xD5, 0xD6, 0xD7, 0xD8, 0xD9, 0xDA, 0xE1, 0xE2,
          0xE3, 0xE4, 0xE5, 0xE6, 0xE7, 0xE8, 0xE9, 0xEA, 0xF1, 0xF2, 0xF3, 0xF4, 0xF5, 0xF6, 0xF7, 0xF8, 0xF9, 0xFA, 0xFF, 0xDA, 0x00, 0x08, 0x01, 0x01, 0x00,
          0x00, 0x3F, 0x00, 0xFB, 0xD5, 0xDB, 0x20, 0xA8, 0xBA, 0xAE, 0xEB, 0xFF, 0xD9};
}

std::vector<uint8_t> createTestPNG()
{
  return {0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, 0x00, 0x00, 0x00, 0x0D, 0x49, 0x48, 0x44, 0x52, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
          0x01, 0x08, 0x02, 0x00, 0x00, 0x00, 0x90, 0x77, 0x53, 0xDE, 0x00, 0x00, 0x00, 0x0C, 0x49, 0x44, 0x41, 0x54, 0x08, 0xD7, 0x63, 0xF8, 0xFF,
          0xFF, 0xFF, 0x00, 0x05, 0xFE, 0x02, 0xFE, 0xDC, 0xCC, 0x59, 0xE7, 0x00, 0x00, 0x00, 0x00, 0x49, 0x45, 0x4E, 0x44, 0xAE, 0x42, 0x60, 0x82};
}

} // namespace

TEST_SUITE("Image2D I/O Tests")
{
  TEST_CASE("Write and read Image2D with JPEG image")
  {
    TempFile tempFile;

    e57::Writer writer(tempFile.string(), "test profile");

    Image2D image2D;
    image2D.name                 = "Test Camera Image";
    image2D.guid                 = "{12345678-1234-1234-1234-123456789ABC}";
    image2D.description          = "JPEG test image from camera";
    image2D.sensorVendor         = "Test Camera Co.";
    image2D.sensorModel          = "TestCam 1000";
    image2D.sensorSerialNumber   = "SN12345";
    image2D.associatedData3DGuid = "{87654321-4321-4321-4321-CBA987654321}";

    image2D.pose.rotation.w    = 0.707;
    image2D.pose.rotation.x    = 0.0;
    image2D.pose.rotation.y    = 0.707;
    image2D.pose.rotation.z    = 0.0;
    image2D.pose.translation.x = 10.5;
    image2D.pose.translation.y = 20.5;
    image2D.pose.translation.z = 30.5;

    image2D.acquisitionDateTime.dateTimeValue = 1234567890.5;

    auto jpegData = createTestJPEG();

    // Set the pinhole representation size so NewImage2D creates the representation node
    image2D.pinholeRepresentation.jpegImageSize   = jpegData.size();
    image2D.pinholeRepresentation.imageWidth      = 1;
    image2D.pinholeRepresentation.imageHeight     = 1;
    image2D.pinholeRepresentation.focalLength     = 1.0;
    image2D.pinholeRepresentation.pixelWidth      = 1.0;
    image2D.pinholeRepresentation.pixelHeight     = 1.0;
    image2D.pinholeRepresentation.principalPointX = 0.5;
    image2D.pinholeRepresentation.principalPointY = 0.5;

    int64_t imageIndex = writer.NewImage2D(image2D);
    REQUIRE_GE(imageIndex, 0);

    writer.WriteImage2DData(imageIndex, E57_JPEG_IMAGE, E57_PINHOLE, jpegData.data(), 0, jpegData.size());

    writer.Close();

    e57::Reader reader(tempFile.string());

    int64_t imageCount = reader.GetImage2DCount();
    REQUIRE_EQ(1, imageCount);

    Image2D readImage;
    reader.ReadImage2D(imageIndex, readImage);

    REQUIRE_EQ("Test Camera Image", readImage.name);
    REQUIRE_EQ("{12345678-1234-1234-1234-123456789ABC}", readImage.guid);
    REQUIRE_EQ("JPEG test image from camera", readImage.description);
    REQUIRE_EQ("Test Camera Co.", readImage.sensorVendor);
    REQUIRE_EQ("TestCam 1000", readImage.sensorModel);
    REQUIRE_EQ("SN12345", readImage.sensorSerialNumber);
    REQUIRE_EQ("{87654321-4321-4321-4321-CBA987654321}", readImage.associatedData3DGuid);

    REQUIRE_EQ(0.707, doctest::Approx(readImage.pose.rotation.w).epsilon(0.001));
    REQUIRE_EQ(0.0, readImage.pose.rotation.x);
    REQUIRE_EQ(0.707, doctest::Approx(readImage.pose.rotation.y).epsilon(0.001));
    REQUIRE_EQ(0.0, readImage.pose.rotation.z);
    REQUIRE_EQ(10.5, doctest::Approx(readImage.pose.translation.x).epsilon(0.001));
    REQUIRE_EQ(20.5, doctest::Approx(readImage.pose.translation.y).epsilon(0.001));
    REQUIRE_EQ(30.5, doctest::Approx(readImage.pose.translation.z).epsilon(0.001));

    REQUIRE_EQ(1234567890.5, doctest::Approx(readImage.acquisitionDateTime.dateTimeValue).epsilon(0.001));

    std::vector<uint8_t> readData(jpegData.size());
    int64_t              bytesRead = reader.ReadImage2DData(imageIndex, E57_PINHOLE, E57_JPEG_IMAGE, readData.data(), 0, readData.size());
    REQUIRE_EQ(static_cast<int64_t>(jpegData.size()), bytesRead);
    REQUIRE_EQ(jpegData, readData);

    reader.Close();
  }

  TEST_CASE("Write and read Image2D with PNG image")
  {
    TempFile tempFile;

    e57::Writer writer(tempFile.string(), "");

    Image2D image2D;
    image2D.name        = "PNG Test Image";
    image2D.guid        = "{AAAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEEEE}";
    image2D.description = "PNG test image";

    auto pngData = createTestPNG();

    image2D.pinholeRepresentation.pngImageSize    = pngData.size();
    image2D.pinholeRepresentation.imageWidth      = 1;
    image2D.pinholeRepresentation.imageHeight     = 1;
    image2D.pinholeRepresentation.focalLength     = 1.0;
    image2D.pinholeRepresentation.pixelWidth      = 1.0;
    image2D.pinholeRepresentation.pixelHeight     = 1.0;
    image2D.pinholeRepresentation.principalPointX = 0.5;
    image2D.pinholeRepresentation.principalPointY = 0.5;

    int64_t imageIndex = writer.NewImage2D(image2D);
    REQUIRE_GE(imageIndex, 0);

    writer.WriteImage2DData(imageIndex, E57_PNG_IMAGE, E57_PINHOLE, pngData.data(), 0, pngData.size());
    writer.Close();

    e57::Reader reader(tempFile.string());
    REQUIRE_EQ(1, reader.GetImage2DCount());

    Image2D readImage;
    reader.ReadImage2D(0, readImage);
    REQUIRE_EQ("PNG Test Image", readImage.name);

    std::vector<uint8_t> readData(pngData.size());
    int64_t              bytesRead = reader.ReadImage2DData(0, E57_PINHOLE, E57_PNG_IMAGE, readData.data(), 0, readData.size());
    REQUIRE_EQ(static_cast<int64_t>(pngData.size()), bytesRead);
    REQUIRE_EQ(pngData, readData);

    reader.Close();
  }

  TEST_CASE("Write and read multiple Image2D entries")
  {
    TempFile tempFile;

    e57::Writer writer(tempFile.string(), "");

    Image2D image1;
    image1.name                                  = "Image 1";
    image1.guid                                  = "{11111111-1111-1111-1111-111111111111}";
    auto jpegData                                = createTestJPEG();
    image1.pinholeRepresentation.jpegImageSize   = jpegData.size();
    image1.pinholeRepresentation.imageWidth      = 1;
    image1.pinholeRepresentation.imageHeight     = 1;
    image1.pinholeRepresentation.focalLength     = 1.0;
    image1.pinholeRepresentation.pixelWidth      = 1.0;
    image1.pinholeRepresentation.pixelHeight     = 1.0;
    image1.pinholeRepresentation.principalPointX = 0.5;
    image1.pinholeRepresentation.principalPointY = 0.5;
    int64_t idx1                                 = writer.NewImage2D(image1);
    writer.WriteImage2DData(idx1, E57_JPEG_IMAGE, E57_PINHOLE, jpegData.data(), 0, jpegData.size());

    Image2D image2;
    image2.name                                  = "Image 2";
    image2.guid                                  = "{22222222-2222-2222-2222-222222222222}";
    auto pngData                                 = createTestPNG();
    image2.pinholeRepresentation.pngImageSize    = pngData.size();
    image2.pinholeRepresentation.imageWidth      = 1;
    image2.pinholeRepresentation.imageHeight     = 1;
    image2.pinholeRepresentation.focalLength     = 1.0;
    image2.pinholeRepresentation.pixelWidth      = 1.0;
    image2.pinholeRepresentation.pixelHeight     = 1.0;
    image2.pinholeRepresentation.principalPointX = 0.5;
    image2.pinholeRepresentation.principalPointY = 0.5;
    int64_t idx2                                 = writer.NewImage2D(image2);
    writer.WriteImage2DData(idx2, E57_PNG_IMAGE, E57_PINHOLE, pngData.data(), 0, pngData.size());

    Image2D image3;
    image3.name                                  = "Image 3";
    image3.guid                                  = "{33333333-3333-3333-3333-333333333333}";
    image3.pinholeRepresentation.jpegImageSize   = jpegData.size();
    image3.pinholeRepresentation.imageWidth      = 1;
    image3.pinholeRepresentation.imageHeight     = 1;
    image3.pinholeRepresentation.focalLength     = 1.0;
    image3.pinholeRepresentation.pixelWidth      = 1.0;
    image3.pinholeRepresentation.pixelHeight     = 1.0;
    image3.pinholeRepresentation.principalPointX = 0.5;
    image3.pinholeRepresentation.principalPointY = 0.5;
    int64_t idx3                                 = writer.NewImage2D(image3);
    writer.WriteImage2DData(idx3, E57_JPEG_IMAGE, E57_PINHOLE, jpegData.data(), 0, jpegData.size());

    writer.Close();

    e57::Reader reader(tempFile.string());
    REQUIRE_EQ(3, reader.GetImage2DCount());

    Image2D readImage1;
    reader.ReadImage2D(0, readImage1);
    REQUIRE_EQ("Image 1", readImage1.name);
    REQUIRE_EQ("{11111111-1111-1111-1111-111111111111}", readImage1.guid);

    Image2D readImage2;
    reader.ReadImage2D(1, readImage2);
    REQUIRE_EQ("Image 2", readImage2.name);
    REQUIRE_EQ("{22222222-2222-2222-2222-222222222222}", readImage2.guid);

    Image2D readImage3;
    reader.ReadImage2D(2, readImage3);
    REQUIRE_EQ("Image 3", readImage3.name);
    REQUIRE_EQ("{33333333-3333-3333-3333-333333333333}", readImage3.guid);

    reader.Close();
  }

  TEST_CASE("Image2D with different projections")
  {
    TempFile tempFile;

    e57::Writer writer(tempFile.string(), "");

    auto jpegData = createTestJPEG();

    std::vector<Image2DProjection> projections = {E57_PINHOLE, E57_SPHERICAL, E57_CYLINDRICAL};

    int idx = 0;
    for (auto proj : projections)
    {
      Image2D image;
      image.name = "Projection Test " + std::to_string(idx);
      image.guid = "{" + std::to_string(idx) + "}";

      if (proj == E57_PINHOLE)
      {
        image.pinholeRepresentation.jpegImageSize   = jpegData.size();
        image.pinholeRepresentation.imageWidth      = 1;
        image.pinholeRepresentation.imageHeight     = 1;
        image.pinholeRepresentation.focalLength     = 1.0;
        image.pinholeRepresentation.pixelWidth      = 1.0;
        image.pinholeRepresentation.pixelHeight     = 1.0;
        image.pinholeRepresentation.principalPointX = 0.5;
        image.pinholeRepresentation.principalPointY = 0.5;
      }
      else if (proj == E57_SPHERICAL)
      {
        image.sphericalRepresentation.jpegImageSize = jpegData.size();
        image.sphericalRepresentation.imageWidth    = 1;
        image.sphericalRepresentation.imageHeight   = 1;
        image.sphericalRepresentation.pixelWidth    = 1.0;
        image.sphericalRepresentation.pixelHeight   = 1.0;
      }
      else if (proj == E57_CYLINDRICAL)
      {
        image.cylindricalRepresentation.jpegImageSize   = jpegData.size();
        image.cylindricalRepresentation.imageWidth      = 1;
        image.cylindricalRepresentation.imageHeight     = 1;
        image.cylindricalRepresentation.pixelWidth      = 1.0;
        image.cylindricalRepresentation.pixelHeight     = 1.0;
        image.cylindricalRepresentation.principalPointY = 0.5;
        image.cylindricalRepresentation.radius          = 1.0;
      }

      int64_t imageIndex = writer.NewImage2D(image);
      writer.WriteImage2DData(imageIndex, E57_JPEG_IMAGE, proj, jpegData.data(), 0, jpegData.size());
      idx++;
    }

    writer.Close();

    e57::Reader reader(tempFile.string());
    REQUIRE_EQ(projections.size(), reader.GetImage2DCount());

    for (size_t i = 0; i < projections.size(); ++i)
    {
      Image2DProjection proj;
      Image2DType       type;
      int64_t           width, height, size;
      Image2DType       maskType, visualType;

      bool success = reader.GetImage2DSizes(i, proj, type, width, height, size, maskType, visualType);
      REQUIRE(success);
      REQUIRE_EQ(projections[i], proj);
    }

    reader.Close();
  }

  TEST_CASE("Image2D with minimal metadata")
  {
    TempFile tempFile;

    e57::Writer writer(tempFile.string(), "");

    Image2D image2D;
    image2D.guid = "{MINIMAL-TEST-GUID}";

    auto jpegData = createTestJPEG();

    int64_t imageIndex = writer.NewImage2D(image2D);
    REQUIRE_GE(imageIndex, 0);

    writer.WriteImage2DData(imageIndex, E57_JPEG_IMAGE, E57_PINHOLE, jpegData.data(), 0, jpegData.size());
    writer.Close();

    e57::Reader reader(tempFile.string());
    Image2D     readImage;
    reader.ReadImage2D(0, readImage);

    REQUIRE_EQ("{MINIMAL-TEST-GUID}", readImage.guid);

    reader.Close();
  }
}
