/*
 * image2d_test.cpp - Tests for Simple API Image2D operations
 *
 * Copyright (c) 2024 openE57 Contributors
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the * Software, and to permit third-parties to whom the Software is furnished to do
 * so, all subject to the following:
 *
 * The above copyright notice in this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must be
 * included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works
 * are solely in the form of machine-executable object code generated by a
 * source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUT THE SOFTWARE BE LIABLE FOR
 * ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN

#include "test_utils.h"

using namespace e57;
using e57::test::TempFile;

TEST_SUITE("Image2D Tests")
{
  TEST_CASE("Image2D default initialization")
  {
    Image2D image2D;

    REQUIRE_EQ("", image2D.name);
    REQUIRE_EQ("", image2D.guid);
  }

  TEST_CASE("Image2D with basic fields")
  {
    Image2D image2D;
    image2D.name        = "Test Image";
    image2D.guid        = "{00000000-0000-0000-000000000000}";
    image2D.description = "Test camera image";

    REQUIRE_EQ("Test Image", image2D.name);
    REQUIRE_EQ("{00000000-0000-0000-000000000000}", image2D.guid);
    REQUIRE_EQ("Test camera image", image2D.description);
  }

  TEST_CASE("Image2D with pose information")
  {
    Image2D image2D;
    image2D.pose.rotation.w    = 1.0;
    image2D.pose.rotation.x    = 0.0;
    image2D.pose.rotation.y    = 0.0;
    image2D.pose.rotation.z    = 0.0;
    image2D.pose.translation.x = 100.0;
    image2D.pose.translation.y = 200.0;
    image2D.pose.translation.z = 300.0;

    REQUIRE_EQ(1.0, image2D.pose.rotation.w);
    REQUIRE_EQ(0.0, image2D.pose.rotation.x);
    REQUIRE_EQ(0.0, image2D.pose.rotation.y);
    REQUIRE_EQ(0.0, image2D.pose.rotation.z);
    REQUIRE_EQ(100.0, image2D.pose.translation.x);
    REQUIRE_EQ(200.0, image2D.pose.translation.y);
    REQUIRE_EQ(300.0, image2D.pose.translation.z);
  }
}
