/*
 * imagefile_test.cpp - Tests for E57 Foundation API ImageFile class
 *
 * Copyright (c) 2024 openE57 Contributors
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN

#include "test_utils.h"

using namespace e57;
using e57::test::TempFile;

TEST_SUITE("ImageFile Tests")
{
  TEST_CASE("ImageFile constructor creates writable file")
  {
    TempFile tempFile;

    ImageFile imf(tempFile.c_str(), "w");

    REQUIRE(imf.isOpen());
    REQUIRE(imf.isWritable());
    REQUIRE_EQ(tempFile.string(), imf.fileName());

    imf.close();
    REQUIRE(!imf.isOpen());
  }

  TEST_CASE("ImageFile constructor creates readable file")
  {
    // First create a file to read
    TempFile tempFile;
    {
      ImageFile     imfWrite(tempFile.c_str(), "w");
      StructureNode root = imfWrite.root();
      root.set("formatName", StringNode(imfWrite, "ASTM E57 3D Imaging Data File"));
      root.set("guid", StringNode(imfWrite, "{00000000-0000-0000-0000-000000000001}"));
      imfWrite.close();
    }

    // Now test reading
    ImageFile imf(tempFile.c_str(), "r");

    REQUIRE(imf.isOpen());
    REQUIRE(!imf.isWritable());
    REQUIRE_EQ(tempFile.string(), imf.fileName());

    imf.close();
    REQUIRE(!imf.isOpen());
  }

  TEST_CASE("ImageFile root returns StructureNode")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    StructureNode root = imf.root();

    REQUIRE_EQ(Node(root).type(), E57_STRUCTURE);
    REQUIRE(root.isRoot());

    imf.close();
  }

  TEST_CASE("ImageFile close terminates file access")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    REQUIRE(imf.isOpen());

    imf.close();

    REQUIRE(!imf.isOpen());
  }

  TEST_CASE("ImageFile cancel aborts changes")
  {
    TempFile tempFile;
    {
      ImageFile     imf(tempFile.c_str(), "w");
      StructureNode root = imf.root();
      root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
      root.set("testField", StringNode(imf, "test value"));

      imf.cancel();
      REQUIRE(!imf.isOpen());
    }

    // File should not exist after cancel
    REQUIRE(!tempFile.exists());
  }

  TEST_CASE("ImageFile supports reader/writer counting")
  {
    TempFile tempFile;

    // Create file
    {
      ImageFile     imfWrite(tempFile.c_str(), "w");
      StructureNode root = imfWrite.root();
      root.set("formatName", StringNode(imfWrite, "ASTM E57 3D Imaging Data File"));
      root.set("guid", StringNode(imfWrite, "{00000000-0000-0000-0000-000000000002}"));
      imfWrite.close();
    }

    ImageFile imf(tempFile.c_str(), "r");

    REQUIRE_EQ(0, imf.writerCount());
    REQUIRE_EQ(0, imf.readerCount());

    imf.close();
  }

  TEST_CASE("ImageFile throws exception for non-existent file")
  {
    REQUIRE_THROWS_AS(ImageFile("/nonexistent/path/file.e57", "r"), E57Exception);
  }

  TEST_CASE("ImageFile extensions management")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    // Add extension
    imf.extensionsAdd("test", "http://example.com/test");

    REQUIRE_EQ(1, imf.extensionsCount());

    // Lookup prefix
    ustring uri;
    REQUIRE(imf.extensionsLookupPrefix("test", uri));
    REQUIRE_EQ("http://example.com/test", uri);

    // Lookup URI
    ustring prefix;
    REQUIRE(imf.extensionsLookupUri("http://example.com/test", prefix));
    REQUIRE_EQ("test", prefix);

    // Get extension by index
    REQUIRE_EQ("test", imf.extensionsPrefix(0));
    REQUIRE_EQ("http://example.com/test", imf.extensionsUri(0));

    imf.close();
  }

  TEST_CASE("ImageFile element name parsing")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    ustring prefix, localName;
    imf.elementNameParse("test:customField", prefix, localName);

    REQUIRE_EQ("test", prefix);
    REQUIRE_EQ("customField", localName);

    imf.close();
  }

  TEST_CASE("ImageFile isElementNameExtended")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    REQUIRE(!imf.isElementNameExtended("simpleName"));
    REQUIRE(imf.isElementNameExtended("prefix:extendedName"));

    imf.close();
  }

  TEST_CASE("ImageFile multiple close calls are safe")
  {
    TempFile      tempFile;
    ImageFile     imf(tempFile.c_str(), "w");
    StructureNode root = imf.root();
    root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));

    imf.close();
    REQUIRE(!imf.isOpen());

    // Second close should be safe (no exception)
    imf.close();
    REQUIRE(!imf.isOpen());
  }

  TEST_CASE("ImageFile handles special characters in filename")
  {
    std::stringstream ss;
    ss << "test_file_with_underscores_" << std::hex << std::random_device{}() << ".e57";
    auto path = std::filesystem::temp_directory_path() / ss.str();

    {
      ImageFile     imf(path.string().c_str(), "w");
      StructureNode root = imf.root();
      root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
      root.set("guid", StringNode(imf, "{00000000-0000-0000-0000-000000000003}"));
      imf.close();
    }

    REQUIRE(std::filesystem::exists(path));

    {
      ImageFile imf(path.string().c_str(), "r");
      REQUIRE(imf.isOpen());
      imf.close();
    }

    std::filesystem::remove(path);
  }

  TEST_CASE("ImageFile dump produces output")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    StructureNode root = imf.root();
    root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
    root.set("guid", StringNode(imf, "{00000000-0000-0000-0000-000000000004}"));
    root.set("testInt", IntegerNode(imf, 42));

    std::stringstream ss;
    imf.dump(0, ss);

    std::string output = ss.str();
    REQUIRE(!output.empty());
    REQUIRE(output.find("formatName") != std::string::npos);
    REQUIRE(output.find("testInt") != std::string::npos);

    imf.close();
  }

  TEST_CASE("ImageFile checkInvariant validates state")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    // Should not throw if invariant is valid
    REQUIRE_NOTHROW(imf.checkInvariant());

    imf.close();

    // Should still be valid after close
    REQUIRE_NOTHROW(imf.checkInvariant());
  }

  TEST_CASE("ImageFile comparison operators DISABLED")
  {
    TempFile  tempFile1;
    TempFile  tempFile2;
    ImageFile imf1(tempFile1.c_str(), "w");
    ImageFile imf2(tempFile2.c_str(), "w");

    REQUIRE_EQ(imf1, imf1);
    REQUIRE_EQ(imf2, imf2);

    REQUIRE(imf1 != imf2);

    imf1.close();
    imf2.close();
  }
}
