/*
 * impl_paths_test.cpp - Tests for internal implementation paths in openE57Impl.cpp
 *
 * Copyright (c) 2024 openE57 Contributors
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The above copyright notice in this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must be
 * included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works
 * are solely in the form of machine-executable object code generated by a
 * source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN

#include "test_utils.h"

#include <cstdint>
#include <vector>

using namespace e57;
using e57::test::TempFile;

TEST_SUITE("Node Hierarchy Tests")
{
  TEST_CASE("Nested structure depth")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    StructureNode root = imf.root();
    StructureNode level1(imf);
    StructureNode level2(imf);
    StructureNode level3(imf);
    StructureNode level4(imf);

    level4.set("deepValue", IntegerNode(imf, 999));
    level3.set("level4", level4);
    level2.set("level3", level3);
    level1.set("level2", level2);
    root.set("level1", level1);

    REQUIRE(root.isDefined("level1"));
    REQUIRE(level1.isDefined("level2"));
    REQUIRE(level2.isDefined("level3"));
    REQUIRE(level3.isDefined("level4"));

    imf.close();
  }

  TEST_CASE("Mixed node types in heterogeneous vector")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    VectorNode v(imf, true);

    v.append(IntegerNode(imf, 42));
    v.append(FloatNode(imf, 3.14));
    v.append(StringNode(imf, "test"));
    v.append(ScaledIntegerNode(imf, static_cast<int64_t>(100), static_cast<int64_t>(0), static_cast<int64_t>(1000), 0.1, 0.0));

    REQUIRE_EQ(4, v.childCount());

    imf.close();
  }

  TEST_CASE("Vector of structures")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    VectorNode v(imf, true);

    for (int i = 0; i < 5; ++i)
    {
      StructureNode s(imf);
      s.set("id", IntegerNode(imf, i));
      s.set("name", StringNode(imf, "item" + std::to_string(i)));
      v.append(s);
    }

    REQUIRE_EQ(5, v.childCount());

    for (int i = 0; i < 5; ++i)
    {
      StructureNode s(v.get(i));
      REQUIRE(s.isDefined("id"));
      REQUIRE(s.isDefined("name"));
    }

    imf.close();
  }
}

TEST_SUITE("CompressedVector Advanced Scenarios")
{
  TEST_CASE("Multiple CompressedVectors in same file")
  {
    TempFile tempFile;

    const size_t         N = 100;
    std::vector<int64_t> data1(N);
    std::vector<int64_t> data2(N);

    for (size_t i = 0; i < N; ++i)
    {
      data1[i] = static_cast<int64_t>(i);
      data2[i] = static_cast<int64_t>(i * 10);
    }

    {
      ImageFile     imf(tempFile.c_str(), "w");
      StructureNode root = imf.root();
      root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
      root.set("guid", StringNode(imf, "{00000000-0000-0000-0000-000000000010}"));

      StructureNode proto1(imf);
      proto1.set("value", IntegerNode(imf, 0));

      StructureNode proto2(imf);
      proto2.set("value", IntegerNode(imf, 0));

      VectorNode codecs(imf, true);

      CompressedVectorNode cv1(imf, proto1, codecs);
      CompressedVectorNode cv2(imf, proto2, codecs);

      root.set("data1", cv1);
      root.set("data2", cv2);

      std::vector<SourceDestBuffer> buffers1;
      buffers1.push_back(SourceDestBuffer(imf, "value", data1.data(), N, true, true));

      CompressedVectorWriter writer1 = cv1.writer(buffers1);
      writer1.write(N);
      writer1.close();

      std::vector<SourceDestBuffer> buffers2;
      buffers2.push_back(SourceDestBuffer(imf, "value", data2.data(), N, true, true));

      CompressedVectorWriter writer2 = cv2.writer(buffers2);
      writer2.write(N);
      writer2.close();

      imf.close();
    }

    {
      ImageFile     imf(tempFile.c_str(), "r");
      StructureNode root = imf.root();

      CompressedVectorNode cv1(root.get("data1"));
      CompressedVectorNode cv2(root.get("data2"));

      std::vector<int64_t> read1(N);
      std::vector<int64_t> read2(N);

      std::vector<SourceDestBuffer> buffers1;
      buffers1.push_back(SourceDestBuffer(imf, "value", read1.data(), N, true, true));

      std::vector<SourceDestBuffer> buffers2;
      buffers2.push_back(SourceDestBuffer(imf, "value", read2.data(), N, true, true));

      CompressedVectorReader reader1 = cv1.reader(buffers1);
      unsigned               count1  = reader1.read();
      reader1.close();

      CompressedVectorReader reader2 = cv2.reader(buffers2);
      unsigned               count2  = reader2.read();
      reader2.close();

      REQUIRE_EQ(N, count1);
      REQUIRE_EQ(N, count2);

      for (size_t i = 0; i < N; ++i)
      {
        REQUIRE_EQ(data1[i], read1[i]);
        REQUIRE_EQ(data2[i], read2[i]);
      }

      imf.close();
    }
  }

  TEST_CASE("CompressedVector with nested structure prototype")
  {
    TempFile tempFile;

    const size_t        N = 50;
    std::vector<double> x(N), y(N), z(N);

    for (size_t i = 0; i < N; ++i)
    {
      x[i] = static_cast<double>(i);
      y[i] = static_cast<double>(i + 1);
      z[i] = static_cast<double>(i + 2);
    }

    {
      ImageFile     imf(tempFile.c_str(), "w");
      StructureNode root = imf.root();
      root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
      root.set("guid", StringNode(imf, "{00000000-0000-0000-0000-000000000011}"));

      StructureNode proto(imf);
      StructureNode cartesian(imf);
      cartesian.set("x", FloatNode(imf, 0.0));
      cartesian.set("y", FloatNode(imf, 0.0));
      cartesian.set("z", FloatNode(imf, 0.0));
      proto.set("cartesian", cartesian);

      VectorNode codecs(imf, true);

      CompressedVectorNode cv(imf, proto, codecs);
      root.set("points", cv);

      std::vector<SourceDestBuffer> buffers;
      buffers.push_back(SourceDestBuffer(imf, "cartesian/x", x.data(), N, true, true));
      buffers.push_back(SourceDestBuffer(imf, "cartesian/y", y.data(), N, true, true));
      buffers.push_back(SourceDestBuffer(imf, "cartesian/z", z.data(), N, true, true));

      CompressedVectorWriter writer = cv.writer(buffers);
      writer.write(N);
      writer.close();

      imf.close();
    }

    {
      ImageFile     imf(tempFile.c_str(), "r");
      StructureNode root = imf.root();

      CompressedVectorNode cv(root.get("points"));

      std::vector<double> rx(N), ry(N), rz(N);

      std::vector<SourceDestBuffer> buffers;
      buffers.push_back(SourceDestBuffer(imf, "cartesian/x", rx.data(), N, true, true));
      buffers.push_back(SourceDestBuffer(imf, "cartesian/y", ry.data(), N, true, true));
      buffers.push_back(SourceDestBuffer(imf, "cartesian/z", rz.data(), N, true, true));

      CompressedVectorReader reader = cv.reader(buffers);
      unsigned               count  = reader.read();
      reader.close();

      REQUIRE_EQ(N, count);

      for (size_t i = 0; i < N; ++i)
      {
        REQUIRE(std::abs(x[i] - rx[i]) < 1e-10);
        REQUIRE(std::abs(y[i] - ry[i]) < 1e-10);
        REQUIRE(std::abs(z[i] - rz[i]) < 1e-10);
      }

      imf.close();
    }
  }
}

TEST_SUITE("File Operations Edge Cases")
{
  TEST_CASE("File with minimal required fields")
  {
    TempFile tempFile;

    {
      ImageFile     imf(tempFile.c_str(), "w");
      StructureNode root = imf.root();
      root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
      root.set("guid", StringNode(imf, "{00000000-0000-0000-000000000012}"));
      imf.close();
    }

    REQUIRE(tempFile.exists());

    {
      ImageFile     imf(tempFile.c_str(), "r");
      StructureNode root = imf.root();

      REQUIRE(root.isDefined("formatName"));
      REQUIRE(root.isDefined("guid"));

      imf.close();
    }
  }

  TEST_CASE("File with many extensions")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    imf.extensionsAdd("ext1", "http://example.com/ext1");
    imf.extensionsAdd("ext2", "http://example.com/ext2");
    imf.extensionsAdd("ext3", "http://example.com/ext3");

    REQUIRE_EQ(3, imf.extensionsCount());

    imf.close();
  }

  TEST_CASE("File reopen and modify")
  {
    TempFile tempFile;

    {
      ImageFile     imf(tempFile.c_str(), "w");
      StructureNode root = imf.root();
      root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
      root.set("guid", StringNode(imf, "{00000000-0000-0000-000000000013}"));
      root.set("version", StringNode(imf, "1.0"));
      imf.close();
    }

    {
      ImageFile     imf(tempFile.c_str(), "r");
      StructureNode root = imf.root();

      REQUIRE(root.isDefined("version"));

      imf.close();
    }
  }
}

TEST_SUITE("Data Type Boundary Tests")
{
  TEST_CASE("IntegerNode with extreme values")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    IntegerNode maxInt(imf, INT64_MAX);
    IntegerNode minInt(imf, INT64_MIN);
    IntegerNode zero(imf, 0);

    REQUIRE_EQ(INT64_MAX, maxInt.value());
    REQUIRE_EQ(INT64_MIN, minInt.value());
    REQUIRE_EQ(0, zero.value());

    imf.close();
  }

  TEST_CASE("FloatNode with extreme values")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    FloatNode maxDouble(imf, DBL_MAX, E57_DOUBLE);
    FloatNode minDouble(imf, DBL_MIN, E57_DOUBLE);
    FloatNode epsilon(imf, DBL_EPSILON, E57_DOUBLE);

    REQUIRE(std::abs(maxDouble.value() - DBL_MAX) < 1e-290);
    REQUIRE(std::abs(minDouble.value() - DBL_MIN) < 1e-320);

    imf.close();
  }

  TEST_CASE("ScaledIntegerNode with extreme scale")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    ScaledIntegerNode tinyScale(imf, static_cast<int64_t>(1234567890), static_cast<int64_t>(0), static_cast<int64_t>(2000000000), 1e-9, 0.0);
    ScaledIntegerNode hugeScale(imf, static_cast<int64_t>(100), static_cast<int64_t>(0), static_cast<int64_t>(1000), 1e9, 0.0);

    REQUIRE(std::abs(tinyScale.scaledValue() - 1.23456789) < 1e-12);
    REQUIRE(std::abs(hugeScale.scaledValue() - 1e11) < 1e5);

    imf.close();
  }

  TEST_CASE("StringNode with special characters")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    StringNode special(imf, "Special chars: \t\n\r\\\"\'");
    StringNode unicode(imf, "Unicode: \u4e2d\u6587");
    StringNode empty(imf, "");

    REQUIRE_EQ("Special chars: \t\n\r\\\"\'", special.value());
    REQUIRE_EQ("Unicode: \u4e2d\u6587", unicode.value());
    REQUIRE_EQ("", empty.value());

    imf.close();
  }
}

TEST_SUITE("CompressedVector Stress Tests")
{
  TEST_CASE("CompressedVector with many small writes")
  {
    TempFile tempFile;

    const size_t totalPoints = 1000;
    const size_t chunkSize   = 10;

    {
      ImageFile     imf(tempFile.c_str(), "w");
      StructureNode root = imf.root();
      root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
      root.set("guid", StringNode(imf, "{00000000-0000-0000-000000000014}"));

      StructureNode proto(imf);
      proto.set("value", IntegerNode(imf, 0));

      VectorNode codecs(imf, true);

      CompressedVectorNode cv(imf, proto, codecs);
      root.set("data", cv);

      int64_t                       chunk[chunkSize];
      std::vector<SourceDestBuffer> buffers;
      buffers.push_back(SourceDestBuffer(imf, "value", chunk, chunkSize, true, true));

      CompressedVectorWriter writer = cv.writer(buffers);

      for (size_t i = 0; i < totalPoints; i += chunkSize)
      {
        for (size_t j = 0; j < chunkSize; ++j)
        {
          chunk[j] = static_cast<int64_t>(i + j);
        }
        writer.write(chunkSize);
      }

      writer.close();
      imf.close();
    }

    {
      ImageFile     imf(tempFile.c_str(), "r");
      StructureNode root = imf.root();

      CompressedVectorNode cv(root.get("data"));

      int64_t                       chunk[chunkSize];
      std::vector<SourceDestBuffer> buffers;
      buffers.push_back(SourceDestBuffer(imf, "value", chunk, chunkSize, true, true));

      CompressedVectorReader reader = cv.reader(buffers);

      size_t totalRead = 0;
      while (true)
      {
        unsigned count = reader.read();
        if (count == 0)
          break;
        totalRead += count;
      }

      reader.close();

      REQUIRE_EQ(totalPoints, totalRead);

      imf.close();
    }
  }

  TEST_CASE("CompressedVectorReader seek throws not-implemented")
  {
    TempFile tempFile;

    const size_t         N = 10;
    std::vector<int64_t> data(N);
    for (size_t i = 0; i < N; ++i)
    {
      data[i] = static_cast<int64_t>(i);
    }

    {
      ImageFile     imf(tempFile.c_str(), "w");
      StructureNode root = imf.root();
      root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
      root.set("guid", StringNode(imf, "{00000000-0000-0000-0000-000000000015}"));

      StructureNode proto(imf);
      proto.set("value", IntegerNode(imf, 0));

      VectorNode           codecs(imf, true);
      CompressedVectorNode cv(imf, proto, codecs);
      root.set("data", cv);

      std::vector<SourceDestBuffer> buffers;
      buffers.push_back(SourceDestBuffer(imf, "value", data.data(), N, true, true));

      CompressedVectorWriter writer = cv.writer(buffers);
      writer.write(N);
      writer.close();

      imf.close();
    }

    {
      ImageFile     imf(tempFile.c_str(), "r");
      StructureNode root = imf.root();

      CompressedVectorNode cv(root.get("data"));

      int64_t                       readData[10];
      std::vector<SourceDestBuffer> buffers;
      buffers.push_back(SourceDestBuffer(imf, "value", readData, 10, true, true));

      CompressedVectorReader reader = cv.reader(buffers);
      REQUIRE_THROWS_AS(reader.seek(0), E57Exception);

      reader.close();
      imf.close();
    }
  }
}
