/*
 * modern_api_test.cpp - Tests for Modern API core structures
 *
 * Copyright (c) 2024 openE57 Contributors
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN

#include <doctest/doctest.h>
#include <openE57/api.h>

#include <cmath>

using namespace e57;

TEST_SUITE("Core Translation Tests")
{
  TEST_CASE("Translation default construction")
  {
    core::Translation t;

    REQUIRE_EQ(0.0, t.x);
    REQUIRE_EQ(0.0, t.y);
    REQUIRE_EQ(0.0, t.z);
  }

  TEST_CASE("Translation with values")
  {
    core::Translation t{1.0, 2.0, 3.0};

    REQUIRE_EQ(1.0, t.x);
    REQUIRE_EQ(2.0, t.y);
    REQUIRE_EQ(3.0, t.z);
  }

  TEST_CASE("Translation negative values")
  {
    core::Translation t{-10.5, -20.5, -30.5};

    REQUIRE_EQ(-10.5, t.x);
    REQUIRE_EQ(-20.5, t.y);
    REQUIRE_EQ(-30.5, t.z);
  }
}

TEST_SUITE("Core Quaternion Tests")
{
  TEST_CASE("Quaternion default construction")
  {
    core::Quaternion q;

    REQUIRE_EQ(0.0, q.w);
    REQUIRE_EQ(0.0, q.x);
    REQUIRE_EQ(0.0, q.y);
    REQUIRE_EQ(0.0, q.z);
  }

  TEST_CASE("Quaternion with values")
  {
    core::Quaternion q{1.0, 0.0, 0.0, 0.0};

    REQUIRE_EQ(1.0, q.w);
    REQUIRE_EQ(0.0, q.x);
    REQUIRE_EQ(0.0, q.y);
    REQUIRE_EQ(0.0, q.z);
  }

  TEST_CASE("Quaternion identity rotation")
  {
    // Identity quaternion (no rotation)
    core::Quaternion identity{1.0, 0.0, 0.0, 0.0};

    double magnitude = std::sqrt(identity.w * identity.w + identity.x * identity.x + identity.y * identity.y + identity.z * identity.z);
    REQUIRE(std::abs(magnitude - 1.0) < 1e-10);
  }

  TEST_CASE("Quaternion 90 degree rotation around Z")
  {
    // 90 degree rotation around Z axis
    double           angle = 3.14159265358979323846 / 2.0; // PI/2
    core::Quaternion q{std::cos(angle / 2.0), 0.0, 0.0, std::sin(angle / 2.0)};

    double magnitude = std::sqrt(q.w * q.w + q.x * q.x + q.y * q.y + q.z * q.z);
    REQUIRE(std::abs(magnitude - 1.0) < 1e-10);
  }
}

TEST_SUITE("Core RigidBodyTransform Tests")
{
  TEST_CASE("RigidBodyTransform default construction")
  {
    core::RigidBodyTransform rbt;

    REQUIRE_EQ(0.0, rbt.rotation.w);
    REQUIRE_EQ(0.0, rbt.translation.x);
  }

  TEST_CASE("RigidBodyTransform with rotation and translation")
  {
    core::RigidBodyTransform rbt;

    rbt.rotation    = {1.0, 0.0, 0.0, 0.0};
    rbt.translation = {10.0, 20.0, 30.0};

    REQUIRE_EQ(1.0, rbt.rotation.w);
    REQUIRE_EQ(10.0, rbt.translation.x);
    REQUIRE_EQ(20.0, rbt.translation.y);
    REQUIRE_EQ(30.0, rbt.translation.z);
  }
}

TEST_SUITE("Core CartesianBounds Tests")
{
  TEST_CASE("CartesianBounds default construction")
  {
    core::CartesianBounds bounds;

    REQUIRE_EQ(0.0, bounds.xMinimum);
    REQUIRE_EQ(0.0, bounds.xMaximum);
    REQUIRE_EQ(0.0, bounds.yMinimum);
    REQUIRE_EQ(0.0, bounds.yMaximum);
    REQUIRE_EQ(0.0, bounds.zMinimum);
    REQUIRE_EQ(0.0, bounds.zMaximum);
  }

  TEST_CASE("CartesianBounds with values")
  {
    core::CartesianBounds bounds{-100.0, 100.0, -50.0, 50.0, 0.0, 200.0};

    REQUIRE_EQ(-100.0, bounds.xMinimum);
    REQUIRE_EQ(100.0, bounds.xMaximum);
    REQUIRE_EQ(-50.0, bounds.yMinimum);
    REQUIRE_EQ(50.0, bounds.yMaximum);
    REQUIRE_EQ(0.0, bounds.zMinimum);
    REQUIRE_EQ(200.0, bounds.zMaximum);
  }
}

TEST_SUITE("Core SphericalBounds Tests")
{
  TEST_CASE("SphericalBounds default construction")
  {
    core::SphericalBounds bounds;

    REQUIRE_EQ(0.0, bounds.rangeMinimum);
    REQUIRE_EQ(0.0, bounds.rangeMaximum);
    REQUIRE_EQ(0.0, bounds.elevationMinimum);
    REQUIRE_EQ(0.0, bounds.elevationMaximum);
    REQUIRE_EQ(0.0, bounds.azimuthStart);
    REQUIRE_EQ(0.0, bounds.azimuthEnd);
  }

  TEST_CASE("SphericalBounds with values")
  {
    core::SphericalBounds bounds{0.0, 100.0, -0.5, 0.5, 0.0, 6.28318530717958647692};

    REQUIRE_EQ(0.0, bounds.rangeMinimum);
    REQUIRE_EQ(100.0, bounds.rangeMaximum);
  }
}

TEST_SUITE("Core IndexBounds Tests")
{
  TEST_CASE("IndexBounds default construction")
  {
    core::IndexBounds bounds;

    REQUIRE_EQ(0, bounds.rowMinimum);
    REQUIRE_EQ(0, bounds.rowMaximum);
    REQUIRE_EQ(0, bounds.columnMinimum);
    REQUIRE_EQ(0, bounds.columnMaximum);
    REQUIRE_EQ(0, bounds.returnMinimum);
    REQUIRE_EQ(0, bounds.returnMaximum);
  }

  TEST_CASE("IndexBounds with values")
  {
    core::IndexBounds bounds{0, 1000, 0, 2000, 0, 3};

    REQUIRE_EQ(0, bounds.rowMinimum);
    REQUIRE_EQ(1000, bounds.rowMaximum);
    REQUIRE_EQ(0, bounds.columnMinimum);
    REQUIRE_EQ(2000, bounds.columnMaximum);
    REQUIRE_EQ(0, bounds.returnMinimum);
    REQUIRE_EQ(3, bounds.returnMaximum);
  }
}

TEST_SUITE("Core IntensityLimits Tests")
{
  TEST_CASE("IntensityLimits default construction")
  {
    core::IntensityLimits limits;

    REQUIRE_EQ(0.0, limits.intensityMinimum);
    REQUIRE_EQ(0.0, limits.intensityMaximum);
  }

  TEST_CASE("IntensityLimits with values")
  {
    core::IntensityLimits limits{0.0, 1.0};

    REQUIRE_EQ(0.0, limits.intensityMinimum);
    REQUIRE_EQ(1.0, limits.intensityMaximum);
  }
}

TEST_SUITE("Core ColorLimits Tests")
{
  TEST_CASE("ColorLimits default construction")
  {
    core::ColorLimits limits;

    REQUIRE_EQ(0.0, limits.colorRedMinimum);
    REQUIRE_EQ(0.0, limits.colorRedMaximum);
    REQUIRE_EQ(0.0, limits.colorGreenMinimum);
    REQUIRE_EQ(0.0, limits.colorGreenMaximum);
    REQUIRE_EQ(0.0, limits.colorBlueMinimum);
    REQUIRE_EQ(0.0, limits.colorBlueMaximum);
  }

  TEST_CASE("ColorLimits with values")
  {
    core::ColorLimits limits{0.0, 255.0, 0.0, 255.0, 0.0, 255.0};

    REQUIRE_EQ(0.0, limits.colorRedMinimum);
    REQUIRE_EQ(255.0, limits.colorRedMaximum);
    REQUIRE_EQ(0.0, limits.colorGreenMinimum);
    REQUIRE_EQ(255.0, limits.colorGreenMaximum);
    REQUIRE_EQ(0.0, limits.colorBlueMinimum);
    REQUIRE_EQ(255.0, limits.colorBlueMaximum);
  }
}

TEST_SUITE("Core UtcTime Tests")
{
  TEST_CASE("UtcTime default construction")
  {
    core::UtcTime time;

    REQUIRE_EQ(1970u, time.year);
    REQUIRE_EQ(1u, time.month);
    REQUIRE_EQ(1u, time.day);
    REQUIRE_EQ(0u, time.hour);
    REQUIRE_EQ(0u, time.minute);
    REQUIRE_EQ(0.0f, time.seconds);
  }

  TEST_CASE("UtcTime with values")
  {
    core::UtcTime time{2024u, 3u, 15u, 14u, 30u, 45.5f};

    REQUIRE_EQ(2024u, time.year);
    REQUIRE_EQ(3u, time.month);
    REQUIRE_EQ(15u, time.day);
    REQUIRE_EQ(14u, time.hour);
    REQUIRE_EQ(30u, time.minute);
    REQUIRE_EQ(45.5f, time.seconds);
  }
}

TEST_SUITE("Core GpsTime Tests")
{
  TEST_CASE("GpsTime default construction")
  {
    core::GpsTime time;

    REQUIRE_EQ(0u, time.week);
    REQUIRE_EQ(0.0, time.tow);
    REQUIRE_EQ(0.0, time.time);
  }

  TEST_CASE("GpsTime from week and tow")
  {
    core::GpsTime time(2191, 15.0);

    REQUIRE_EQ(2191u, time.week);
    REQUIRE_EQ(15.0, time.tow);
    REQUIRE(time.time > 0.0);
  }

  TEST_CASE("GpsTime from time value")
  {
    double        gpsTimeValue = 1325116815.0;
    core::GpsTime time(gpsTimeValue);

    REQUIRE_EQ(2191u, time.week);
    REQUIRE_EQ(15.0, time.tow);
    REQUIRE_EQ(gpsTimeValue, time.time);
  }
}

TEST_SUITE("Utils Time Functions Tests")
{
  TEST_CASE("current_gps_time returns valid time")
  {
    core::GpsTime time = utils::current_gps_time();

    REQUIRE(time.week >= 0);
    REQUIRE(time.tow >= 0.0);
    REQUIRE(time.time > 0.0);
  }

  TEST_CASE("current_utc_time returns valid time")
  {
    core::UtcTime time = utils::current_utc_time();

    REQUIRE(time.year >= 2020);
    REQUIRE(time.month >= 1);
    REQUIRE(time.month <= 12);
    REQUIRE(time.day >= 1);
    REQUIRE(time.day <= 31);
    REQUIRE(time.hour <= 23);
    REQUIRE(time.minute <= 59);
    REQUIRE(time.seconds >= 0.0f);
    REQUIRE(time.seconds < 60.0f);
  }

  TEST_CASE("utc_time_from_gps_time conversion")
  {
    core::GpsTime gpsTime(2191, 15.0);
    core::UtcTime utcTime = utils::utc_time_from_gps_time(gpsTime);

    REQUIRE_EQ(2022u, utcTime.year);
    REQUIRE_EQ(1u, utcTime.month);
    REQUIRE_EQ(2u, utcTime.day);
    REQUIRE_EQ(0u, utcTime.hour);
    REQUIRE_EQ(0u, utcTime.minute);
  }
}
