/*
 * node_advanced_test.cpp - Tests for previously uncovered Node API methods:
 *   Node::parent(), Node::pathName(), StructureNode::get(int64_t index),
 *   and E57Utilities::rawXmlLength() / rawXmlRead().
 *
 * Copyright (c) 2024 openE57 Contributors
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "test_utils.h"

using namespace e57;
using namespace e57::test;

TEST_SUITE("Node::parent Tests")
{
  TEST_CASE("Node parent returns correct parent for top-level child")
  {
    TempFile      tempFile;
    ImageFile     imf(tempFile.c_str(), "w");
    StructureNode root = imf.root();
    root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
    root.set("guid", StringNode(imf, "{00000000-0000-0000-0000-000000000300}"));

    IntegerNode child(imf, 42);
    root.set("myInt", child);

    Node parentNode = child.parent();
    REQUIRE_EQ(E57_STRUCTURE, parentNode.type());

    StructureNode parentStruct(parentNode);
    REQUIRE(parentStruct.isDefined("myInt"));

    imf.close();
  }

  TEST_CASE("StructureNode parent returns correct parent")
  {
    TempFile      tempFile;
    ImageFile     imf(tempFile.c_str(), "w");
    StructureNode root = imf.root();
    root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
    root.set("guid", StringNode(imf, "{00000000-0000-0000-0000-000000000301}"));

    StructureNode child(imf);
    child.set("value", IntegerNode(imf, 99));
    root.set("nested", child);

    Node parentOfNested = child.parent();
    REQUIRE(parentOfNested.isRoot());

    imf.close();
  }

  TEST_CASE("VectorNode parent returns correct parent")
  {
    TempFile      tempFile;
    ImageFile     imf(tempFile.c_str(), "w");
    StructureNode root = imf.root();
    root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
    root.set("guid", StringNode(imf, "{00000000-0000-0000-0000-000000000302}"));

    VectorNode v(imf, true);
    v.append(IntegerNode(imf, 10));
    root.set("myVec", v);

    Node element      = v.get(static_cast<int64_t>(0));
    Node parentOfElem = element.parent();
    REQUIRE_EQ(E57_VECTOR, parentOfElem.type());

    imf.close();
  }
}

TEST_SUITE("Node::pathName Tests")
{
  TEST_CASE("Root node has empty pathName")
  {
    TempFile      tempFile;
    ImageFile     imf(tempFile.c_str(), "w");
    StructureNode root = imf.root();

    REQUIRE_EQ("/", root.pathName());

    imf.close();
  }

  TEST_CASE("Top-level child has correct pathName")
  {
    TempFile      tempFile;
    ImageFile     imf(tempFile.c_str(), "w");
    StructureNode root = imf.root();
    root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
    root.set("guid", StringNode(imf, "{00000000-0000-0000-0000-000000000310}"));

    IntegerNode child(imf, 7);
    root.set("myField", child);

    REQUIRE_EQ("/myField", child.pathName());

    imf.close();
  }

  TEST_CASE("Nested child has correct deep pathName")
  {
    TempFile      tempFile;
    ImageFile     imf(tempFile.c_str(), "w");
    StructureNode root = imf.root();
    root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
    root.set("guid", StringNode(imf, "{00000000-0000-0000-0000-000000000311}"));

    StructureNode outer(imf);
    StructureNode inner(imf);
    FloatNode     leaf(imf, 3.14);
    inner.set("val", leaf);
    outer.set("inner", inner);
    root.set("outer", outer);

    REQUIRE_EQ("/outer/inner/val", leaf.pathName());

    imf.close();
  }

  TEST_CASE("VectorNode element has index-based pathName")
  {
    TempFile      tempFile;
    ImageFile     imf(tempFile.c_str(), "w");
    StructureNode root = imf.root();
    root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
    root.set("guid", StringNode(imf, "{00000000-0000-0000-0000-000000000312}"));

    VectorNode v(imf, false);
    v.append(IntegerNode(imf, 0));
    v.append(IntegerNode(imf, 1));
    root.set("items", v);

    Node first  = v.get(static_cast<int64_t>(0));
    Node second = v.get(static_cast<int64_t>(1));

    REQUIRE_EQ("/items/0", first.pathName());
    REQUIRE_EQ("/items/1", second.pathName());

    imf.close();
  }

  TEST_CASE("StringNode pathName matches elementName")
  {
    TempFile      tempFile;
    ImageFile     imf(tempFile.c_str(), "w");
    StructureNode root = imf.root();
    root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
    root.set("guid", StringNode(imf, "{00000000-0000-0000-0000-000000000313}"));

    StringNode s(imf, "hello");
    root.set("greeting", s);

    REQUIRE_EQ("/greeting", s.pathName());
    REQUIRE_EQ("greeting", s.elementName());

    imf.close();
  }
}

TEST_SUITE("StructureNode::get(int64_t index) Tests")
{
  TEST_CASE("StructureNode get by index returns correct child")
  {
    TempFile      tempFile;
    ImageFile     imf(tempFile.c_str(), "w");
    StructureNode root = imf.root();
    root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
    root.set("guid", StringNode(imf, "{00000000-0000-0000-0000-000000000320}"));

    StructureNode s(imf);
    s.set("alpha", IntegerNode(imf, 1));
    s.set("beta", IntegerNode(imf, 2));
    s.set("gamma", IntegerNode(imf, 3));
    root.set("struct", s);

    REQUIRE_EQ(3, s.childCount());

    Node first  = s.get(static_cast<int64_t>(0));
    Node second = s.get(static_cast<int64_t>(1));
    Node third  = s.get(static_cast<int64_t>(2));

    REQUIRE_EQ(E57_INTEGER, first.type());
    REQUIRE_EQ(E57_INTEGER, second.type());
    REQUIRE_EQ(E57_INTEGER, third.type());

    REQUIRE_EQ(1, IntegerNode(first).value());
    REQUIRE_EQ(2, IntegerNode(second).value());
    REQUIRE_EQ(3, IntegerNode(third).value());

    imf.close();
  }

  TEST_CASE("StructureNode get by index and get by name return same node")
  {
    TempFile      tempFile;
    ImageFile     imf(tempFile.c_str(), "w");
    StructureNode root = imf.root();
    root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
    root.set("guid", StringNode(imf, "{00000000-0000-0000-0000-000000000321}"));

    StructureNode s(imf);
    s.set("x", FloatNode(imf, 1.0));
    s.set("y", FloatNode(imf, 2.0));
    root.set("coords", s);

    Node byIndex = s.get(static_cast<int64_t>(0));
    Node byName  = s.get("x");

    REQUIRE_EQ(byIndex.pathName(), byName.pathName());
    REQUIRE_EQ(FloatNode(byIndex).value(), FloatNode(byName).value());

    imf.close();
  }

  TEST_CASE("StructureNode get by index throws on out of bounds")
  {
    TempFile      tempFile;
    ImageFile     imf(tempFile.c_str(), "w");
    StructureNode root = imf.root();

    StructureNode s(imf);
    s.set("only", IntegerNode(imf, 0));

    REQUIRE_THROWS_AS(s.get(static_cast<int64_t>(1)), E57Exception);
    REQUIRE_THROWS_AS(s.get(static_cast<int64_t>(-1)), E57Exception);

    imf.close();
  }

  TEST_CASE("StructureNode get by index on root returns expected fields")
  {
    TempFile      tempFile;
    ImageFile     imf(tempFile.c_str(), "w");
    StructureNode root = imf.root();
    root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
    root.set("guid", StringNode(imf, "{00000000-0000-0000-0000-000000000322}"));

    REQUIRE_EQ(2, root.childCount());

    Node first  = root.get(static_cast<int64_t>(0));
    Node second = root.get(static_cast<int64_t>(1));

    REQUIRE_EQ(E57_STRING, first.type());
    REQUIRE_EQ(E57_STRING, second.type());

    imf.close();
  }
}

TEST_SUITE("E57Utilities::rawXml Tests")
{
  TEST_CASE("rawXmlLength returns positive value for valid E57 file")
  {
    TempFile tempFile;

    {
      ImageFile     imf(tempFile.c_str(), "w");
      StructureNode root = imf.root();
      root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
      root.set("guid", StringNode(imf, "{00000000-0000-0000-0000-000000000330}"));
      imf.close();
    }

    E57Utilities utils;
    int64_t      xmlLen = utils.rawXmlLength(tempFile.string());

    REQUIRE_GT(xmlLen, 0);
  }

  TEST_CASE("rawXmlRead retrieves well-formed XML containing formatName")
  {
    TempFile tempFile;

    {
      ImageFile     imf(tempFile.c_str(), "w");
      StructureNode root = imf.root();
      root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
      root.set("guid", StringNode(imf, "{00000000-0000-0000-0000-000000000331}"));
      imf.close();
    }

    E57Utilities utils;
    int64_t      xmlLen = utils.rawXmlLength(tempFile.string());
    REQUIRE_GT(xmlLen, 0);

    std::vector<uint8_t> buf(static_cast<size_t>(xmlLen));
    utils.rawXmlRead(tempFile.string(), buf.data(), 0, static_cast<size_t>(xmlLen));

    std::string xmlStr(buf.begin(), buf.end());
    REQUIRE(xmlStr.find("formatName") != std::string::npos);
    REQUIRE(xmlStr.find("ASTM E57") != std::string::npos);
  }

  TEST_CASE("rawXmlRead partial read returns subset of XML")
  {
    TempFile tempFile;

    {
      ImageFile     imf(tempFile.c_str(), "w");
      StructureNode root = imf.root();
      root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
      root.set("guid", StringNode(imf, "{00000000-0000-0000-0000-000000000332}"));
      imf.close();
    }

    E57Utilities utils;
    int64_t      xmlLen = utils.rawXmlLength(tempFile.string());
    REQUIRE_GT(xmlLen, 10);

    std::vector<uint8_t> partial(10);
    utils.rawXmlRead(tempFile.string(), partial.data(), 0, 10);

    REQUIRE(!partial.empty());
  }

  TEST_CASE("rawXmlLength throws for non-existent file")
  {
    E57Utilities utils;
    REQUIRE_THROWS(utils.rawXmlLength("/nonexistent/path/to/file.e57"));
  }

  TEST_CASE("rawXmlRead throws for non-existent file")
  {
    E57Utilities utils;
    uint8_t      buf[10] = {0};
    REQUIRE_THROWS(utils.rawXmlRead("/nonexistent/path/to/file.e57", buf, 0, 10));
  }
}
