/*
 * scaled_integer_blob_test.cpp - Tests for ScaledIntegerNode and BlobNode
 *
 * Copyright (c) 2024 openE57 Contributors
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN

#include "test_utils.h"

#include <cstring>

using namespace e57;
using e57::test::TempFile;

TEST_SUITE("ScaledIntegerNode Tests")
{
  TEST_CASE("ScaledIntegerNode constructor with basic parameters")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    int64_t rawValue = 12345;
    int64_t minimum  = 0;
    int64_t maximum  = 20000;
    double  scale    = 0.001;
    double  offset   = 0.0;

    ScaledIntegerNode node(imf, rawValue, minimum, maximum, scale, offset);

    REQUIRE_EQ(rawValue, node.rawValue());
    REQUIRE(std::abs(node.scaledValue() - 12.345) < 1e-10);
    REQUIRE(std::abs(node.scale() - scale) < 1e-15);
    REQUIRE(std::abs(node.offset() - offset) < 1e-15);

    imf.close();
  }

  TEST_CASE("ScaledIntegerNode with bounds")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    int64_t rawValue = 500;
    int64_t minimum  = 0;
    int64_t maximum  = 1000;
    double  scale    = 0.01;
    double  offset   = -10.0;

    ScaledIntegerNode node(imf, rawValue, minimum, maximum, scale, offset);

    REQUIRE_EQ(rawValue, node.rawValue());
    REQUIRE(std::abs(node.scaledValue() - (-5.0)) < 1e-10);
    REQUIRE_EQ(minimum, node.minimum());
    REQUIRE_EQ(maximum, node.maximum());
    REQUIRE(std::abs(node.scaledMinimum() - (-10.0)) < 1e-10);
    REQUIRE(std::abs(node.scaledMaximum() - (0.0)) < 1e-10);

    imf.close();
  }

  TEST_CASE("ScaledIntegerNode scaling formula: scaled = raw * scale + offset")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    ScaledIntegerNode node1(imf, static_cast<int64_t>(100), static_cast<int64_t>(0), static_cast<int64_t>(200), 0.5, 10.0);
    REQUIRE(std::abs(node1.scaledValue() - 60.0) < 1e-10);

    ScaledIntegerNode node2(imf, static_cast<int64_t>(0), static_cast<int64_t>(-100), static_cast<int64_t>(100), 2.0, -5.0);
    REQUIRE(std::abs(node2.scaledValue() - (-5.0)) < 1e-10);

    ScaledIntegerNode node3(imf, static_cast<int64_t>(-50), static_cast<int64_t>(-100), static_cast<int64_t>(100), 0.1, 100.0);
    REQUIRE(std::abs(node3.scaledValue() - 95.0) < 1e-10);

    imf.close();
  }

  TEST_CASE("ScaledIntegerNode handles typical coordinate scaling")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    // Typical use case: store millimeter coordinates as integers
    // scale=0.001, offset=0.0
    int64_t           coordinate_mm = 1234567; // 1234.567 meters
    ScaledIntegerNode node(imf, coordinate_mm, static_cast<int64_t>(-10000000), static_cast<int64_t>(10000000), 0.001, 0.0);

    REQUIRE(std::abs(node.scaledValue() - 1234.567) < 1e-6);
    REQUIRE_EQ(coordinate_mm, node.rawValue());

    imf.close();
  }

  TEST_CASE("ScaledIntegerNode is attached to ImageFile")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    ScaledIntegerNode node(imf, static_cast<int64_t>(42), static_cast<int64_t>(0), static_cast<int64_t>(100), 0.1, 0.0);

    REQUIRE(!node.isAttached());
    REQUIRE_EQ(imf, node.destImageFile());

    imf.close();
  }

  TEST_CASE("ScaledIntegerNode dump produces output")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    ScaledIntegerNode node(imf, 123, 0, 1000, 0.01, 0.0);

    std::stringstream ss;
    node.dump(0, ss);

    std::string output = ss.str();
    REQUIRE(!output.empty());

    imf.close();
  }

  TEST_CASE("ScaledIntegerNode checkInvariant")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    ScaledIntegerNode node(imf, 50, -100, 100, 0.5, 10.0);

    REQUIRE_NOTHROW(node.checkInvariant());

    imf.close();
  }
}

TEST_SUITE("BlobNode Tests")
{
  TEST_CASE("BlobNode constructor with size")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    int64_t  byteCount = 1024;
    BlobNode node(imf, byteCount);

    REQUIRE_EQ(byteCount, node.byteCount());

    imf.close();
  }

  TEST_CASE("BlobNode write and read data")
  {
    TempFile tempFile;

    // Create test data
    std::vector<uint8_t> writeData = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};

    {
      ImageFile     imf(tempFile.c_str(), "w");
      StructureNode root = imf.root();
      root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
      root.set("guid", StringNode(imf, "{00000000-0000-0000-0000-000000000010}"));

      BlobNode blob(imf, static_cast<int64_t>(writeData.size()));
      root.set("testBlob", blob);
      blob.write(writeData.data(), 0, writeData.size());

      imf.close();
    }

    // Read back
    {
      ImageFile     imf(tempFile.c_str(), "r");
      StructureNode root = imf.root();

      BlobNode blob(root.get("testBlob"));
      REQUIRE_EQ(static_cast<int64_t>(writeData.size()), blob.byteCount());

      std::vector<uint8_t> readData(writeData.size());
      blob.read(readData.data(), 0, writeData.size());

      for (size_t i = 0; i < writeData.size(); ++i)
      {
        REQUIRE_EQ(writeData[i], readData[i]);
      }

      imf.close();
    }
  }

  TEST_CASE("BlobNode partial read and write")
  {
    TempFile tempFile;

    std::vector<uint8_t> fullData(100);
    for (size_t i = 0; i < fullData.size(); ++i)
    {
      fullData[i] = static_cast<uint8_t>(i);
    }

    {
      ImageFile     imf(tempFile.c_str(), "w");
      StructureNode root = imf.root();
      root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
      root.set("guid", StringNode(imf, "{00000000-0000-0000-0000-000000000011}"));

      BlobNode blob(imf, static_cast<int64_t>(fullData.size()));
      root.set("partialBlob", blob);
      blob.write(fullData.data(), 0, fullData.size());

      imf.close();
    }

    {
      ImageFile     imf(tempFile.c_str(), "r");
      StructureNode root = imf.root();

      BlobNode blob(root.get("partialBlob"));

      // Read only middle portion
      std::vector<uint8_t> partialData(20);
      int64_t              start = 40;
      blob.read(partialData.data(), start, partialData.size());

      for (size_t i = 0; i < partialData.size(); ++i)
      {
        REQUIRE_EQ(fullData[start + i], partialData[i]);
      }

      imf.close();
    }
  }

  TEST_CASE("BlobNode empty blob")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    BlobNode node(imf, 0);

    REQUIRE_EQ(0, node.byteCount());

    imf.close();
  }

  TEST_CASE("BlobNode is attached to ImageFile")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    BlobNode node(imf, 100);

    REQUIRE(!node.isAttached());
    REQUIRE_EQ(imf, node.destImageFile());

    imf.close();
  }

  TEST_CASE("BlobNode dump produces output")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    BlobNode node(imf, 256);

    std::stringstream ss;
    node.dump(0, ss);

    std::string output = ss.str();
    REQUIRE(!output.empty());

    imf.close();
  }

  TEST_CASE("BlobNode checkInvariant")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    BlobNode node(imf, 512);

    REQUIRE_NOTHROW(node.checkInvariant());

    imf.close();
  }
}
