/*
 * simple_api_advanced_test.cpp - Tests for Simple API methods not previously covered:
 *   Reader::GetData3DSizes(), Reader::ReadData3DGroupsData(),
 *   Writer::WriteData3DGroupsData(), Writer::SetUpData3DPointsData() with optional
 *   buffers (intensity, color, timestamps, spherical), and Reset() on E57Root /
 *   Data3D / Image2D, plus untested ScaledIntegerNode constructors.
 *
 * Copyright (c) 2024 openE57 Contributors
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "test_utils.h"

#include <cstdint>
#include <cstring>

using namespace e57;
using e57::test::TempFile;

namespace
{

void writeScanXYZ(const std::string& path, const std::string& guid, int64_t N)
{
  Writer writer(path, "");

  Data3D scan;
  scan.guid                          = guid;
  scan.pointFields.cartesianXField   = true;
  scan.pointFields.cartesianYField   = true;
  scan.pointFields.cartesianZField   = true;
  scan.pointFields.pointRangeMinimum = -1000.0;
  scan.pointFields.pointRangeMaximum = 1000.0;

  int32_t idx = writer.NewData3D(scan);

  std::vector<double> X(static_cast<size_t>(N));
  std::vector<double> Y(static_cast<size_t>(N));
  std::vector<double> Z(static_cast<size_t>(N));
  for (int64_t i = 0; i < N; ++i)
  {
    X[static_cast<size_t>(i)] = static_cast<double>(i);
    Y[static_cast<size_t>(i)] = static_cast<double>(i) * 0.1;
    Z[static_cast<size_t>(i)] = static_cast<double>(i) * 0.01;
  }

  CompressedVectorWriter cvWriter = writer.SetUpData3DPointsData(idx, N, X.data(), Y.data(), Z.data());
  cvWriter.write(static_cast<size_t>(N));
  cvWriter.close();

  writer.Close();
}

} // namespace

TEST_SUITE("Reader::GetData3DSizes Tests")
{
  TEST_CASE("GetData3DSizes returns correct point count for a scan")
  {
    TempFile      tempFile;
    const int64_t N = 20;
    writeScanXYZ(tempFile.string(), "{00000000-0000-0000-0000-000000000500}", N);

    Reader  reader(tempFile.string());
    int64_t rowMax, columnMax, pointsSize, groupsSize, countSize;
    bool    bColumnIndex;

    bool ok = reader.GetData3DSizes(0, rowMax, columnMax, pointsSize, groupsSize, countSize, bColumnIndex);

    REQUIRE(ok);
    REQUIRE_EQ(N, pointsSize);

    reader.Close();
  }

  TEST_CASE("GetData3DSizes returns false for out-of-range index")
  {
    TempFile tempFile;
    writeScanXYZ(tempFile.string(), "{00000000-0000-0000-0000-000000000501}", 5);

    Reader  reader(tempFile.string());
    int64_t rowMax, columnMax, pointsSize, groupsSize, countSize;
    bool    bColumnIndex;

    bool ok = reader.GetData3DSizes(99, rowMax, columnMax, pointsSize, groupsSize, countSize, bColumnIndex);
    REQUIRE(!ok);

    reader.Close();
  }
}

TEST_SUITE("SetUpData3DPointsData with optional fields Tests")
{
  TEST_CASE("Writer and Reader round-trip with intensity field")
  {
    TempFile     tempFile;
    const size_t N            = 5;
    double       X[N]         = {1, 2, 3, 4, 5};
    double       Y[N]         = {0, 0, 0, 0, 0};
    double       Z[N]         = {0, 0, 0, 0, 0};
    double       intensity[N] = {0.1, 0.2, 0.3, 0.4, 0.5};
    double       readX[N]     = {0};
    double       readY[N]     = {0};
    double       readZ[N]     = {0};
    double       readI[N]     = {0};

    {
      Writer writer(tempFile.string(), "");

      Data3D scan;
      scan.guid                               = "{00000000-0000-0000-0000-000000000510}";
      scan.pointFields.cartesianXField        = true;
      scan.pointFields.cartesianYField        = true;
      scan.pointFields.cartesianZField        = true;
      scan.pointFields.intensityField         = true;
      scan.pointFields.pointRangeMinimum      = -1000.0;
      scan.pointFields.pointRangeMaximum      = 1000.0;
      scan.pointFields.intensityScaledInteger = E57_NOT_SCALED_USE_FLOAT;
      scan.intensityLimits.intensityMinimum   = 0.0;
      scan.intensityLimits.intensityMaximum   = 1.0;

      int32_t                idx      = writer.NewData3D(scan);
      CompressedVectorWriter cvWriter = writer.SetUpData3DPointsData(idx, static_cast<int64_t>(N), X, Y, Z, nullptr, intensity);
      cvWriter.write(N);
      cvWriter.close();
      writer.Close();
    }

    {
      Reader reader(tempFile.string());

      CompressedVectorReader cvReader = reader.SetUpData3DPointsData(0, static_cast<int64_t>(N), readX, readY, readZ, nullptr, readI);
      unsigned               count    = cvReader.read();
      cvReader.close();

      REQUIRE_EQ(N, count);
      for (size_t i = 0; i < N; ++i)
      {
        REQUIRE(e57::test::approxEqual(intensity[i], readI[i], 1e-4));
      }

      reader.Close();
    }
  }

  TEST_CASE("Writer and Reader round-trip with color fields")
  {
    TempFile     tempFile;
    const size_t N         = 4;
    double       X[N]      = {0, 1, 2, 3};
    double       Y[N]      = {0, 0, 0, 0};
    double       Z[N]      = {0, 0, 0, 0};
    uint16_t     colorR[N] = {255, 0, 0, 128};
    uint16_t     colorG[N] = {0, 255, 0, 128};
    uint16_t     colorB[N] = {0, 0, 255, 128};
    double       readX[N]  = {0};
    double       readY[N]  = {0};
    double       readZ[N]  = {0};
    uint16_t     readR[N]  = {0};
    uint16_t     readG[N]  = {0};
    uint16_t     readB[N]  = {0};

    {
      Writer writer(tempFile.string(), "");

      Data3D scan;
      scan.guid                          = "{00000000-0000-0000-0000-000000000511}";
      scan.pointFields.cartesianXField   = true;
      scan.pointFields.cartesianYField   = true;
      scan.pointFields.cartesianZField   = true;
      scan.pointFields.colorRedField     = true;
      scan.pointFields.colorGreenField   = true;
      scan.pointFields.colorBlueField    = true;
      scan.pointFields.pointRangeMinimum = -1000.0;
      scan.pointFields.pointRangeMaximum = 1000.0;
      scan.colorLimits.colorRedMinimum   = 0.0;
      scan.colorLimits.colorRedMaximum   = 65535.0;
      scan.colorLimits.colorGreenMinimum = 0.0;
      scan.colorLimits.colorGreenMaximum = 65535.0;
      scan.colorLimits.colorBlueMinimum  = 0.0;
      scan.colorLimits.colorBlueMaximum  = 65535.0;

      int32_t idx = writer.NewData3D(scan);

      CompressedVectorWriter cvWriter = writer.SetUpData3DPointsData(idx, static_cast<int64_t>(N), X, Y, Z, nullptr, nullptr, nullptr, colorR, colorG, colorB);
      cvWriter.write(N);
      cvWriter.close();
      writer.Close();
    }

    {
      Reader reader(tempFile.string());

      CompressedVectorReader cvReader
        = reader.SetUpData3DPointsData(0, static_cast<int64_t>(N), readX, readY, readZ, nullptr, nullptr, nullptr, readR, readG, readB);
      unsigned count = cvReader.read();
      cvReader.close();

      REQUIRE_EQ(N, count);
      for (size_t i = 0; i < N; ++i)
      {
        REQUIRE_EQ(colorR[i], readR[i]);
        REQUIRE_EQ(colorG[i], readG[i]);
        REQUIRE_EQ(colorB[i], readB[i]);
      }

      reader.Close();
    }
  }

  TEST_CASE("Writer and Reader round-trip with timeStamp field")
  {
    TempFile     tempFile;
    const size_t N         = 3;
    double       X[N]      = {0, 1, 2};
    double       Y[N]      = {0, 0, 0};
    double       Z[N]      = {0, 0, 0};
    double       ts[N]     = {0.0, 0.5, 1.0};
    double       readX[N]  = {0};
    double       readY[N]  = {0};
    double       readZ[N]  = {0};
    double       readTs[N] = {0};

    {
      Writer writer(tempFile.string(), "");

      Data3D scan;
      scan.guid                          = "{00000000-0000-0000-0000-000000000512}";
      scan.pointFields.cartesianXField   = true;
      scan.pointFields.cartesianYField   = true;
      scan.pointFields.cartesianZField   = true;
      scan.pointFields.timeStampField    = true;
      scan.pointFields.pointRangeMinimum = -1000.0;
      scan.pointFields.pointRangeMaximum = 1000.0;

      int32_t idx = writer.NewData3D(scan);

      CompressedVectorWriter cvWriter
        = writer.SetUpData3DPointsData(idx, static_cast<int64_t>(N), X, Y, Z, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr,
                                       nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, ts);
      cvWriter.write(N);
      cvWriter.close();
      writer.Close();
    }

    {
      Reader reader(tempFile.string());

      CompressedVectorReader cvReader
        = reader.SetUpData3DPointsData(0, static_cast<int64_t>(N), readX, readY, readZ, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr,
                                       nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, nullptr, readTs);
      unsigned count = cvReader.read();
      cvReader.close();

      REQUIRE_EQ(N, count);
      for (size_t i = 0; i < N; ++i)
      {
        REQUIRE(e57::test::approxEqual(ts[i], readTs[i], 1e-6));
      }

      reader.Close();
    }
  }
}

TEST_SUITE("Reset() Methods Tests")
{
  TEST_CASE("E57Root::Reset resets numeric fields to defaults")
  {
    E57Root root;
    root.versionMajor = 99;
    root.versionMinor = 99;
    root.data3DSize   = 5;
    root.images2DSize = 3;

    root.Reset();

    REQUIRE_EQ(1u, root.versionMajor);
    REQUIRE_EQ(0u, root.versionMinor);
    REQUIRE_EQ(0, root.data3DSize);
    REQUIRE_EQ(0, root.images2DSize);
    REQUIRE_EQ(0.0, root.creationDateTime.dateTimeValue);
  }

  TEST_CASE("Data3D::Reset resets numeric and bool fields to defaults")
  {
    Data3D scan;
    scan.pointsSize                  = 1000;
    scan.temperature                 = 25.0f;
    scan.relativeHumidity            = 50.0f;
    scan.atmosphericPressure         = 101000.0f;
    scan.pointFields.cartesianXField = true;
    scan.pointFields.cartesianYField = true;
    scan.pointFields.intensityField  = true;

    scan.Reset();

    REQUIRE_EQ(0, scan.pointsSize);
    REQUIRE(!scan.pointFields.cartesianXField);
    REQUIRE(!scan.pointFields.cartesianYField);
    REQUIRE(!scan.pointFields.intensityField);
    REQUIRE_EQ(0.0, scan.acquisitionStart.dateTimeValue);
    REQUIRE_EQ(0.0, scan.acquisitionEnd.dateTimeValue);
  }

  TEST_CASE("Image2D::Reset resets numeric fields to defaults")
  {
    Image2D img;
    img.acquisitionDateTime.dateTimeValue           = 12345.0;
    img.acquisitionDateTime.isAtomicClockReferenced = 1;
    img.pose.rotation.w                             = 0.5;
    img.pose.translation.x                          = 100.0;

    img.Reset();

    REQUIRE_EQ(0.0, img.acquisitionDateTime.dateTimeValue);
    REQUIRE_EQ(0, img.acquisitionDateTime.isAtomicClockReferenced);
    REQUIRE_EQ(1.0, img.pose.rotation.w);
    REQUIRE_EQ(0.0, img.pose.translation.x);
  }
}

TEST_SUITE("ScaledIntegerNode Additional Constructors Tests")
{
  TEST_CASE("ScaledIntegerNode(imf, int, int64_t, int64_t) constructor")
  {
    TempFile      tempFile;
    ImageFile     imf(tempFile.c_str(), "w");
    StructureNode root = imf.root();
    root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
    root.set("guid", StringNode(imf, "{00000000-0000-0000-0000-000000000520}"));

    ScaledIntegerNode si(imf, static_cast<int>(5), static_cast<int64_t>(-100), static_cast<int64_t>(100), 0.01, 0.0);
    root.set("field", si);

    REQUIRE_EQ(5, si.rawValue());
    REQUIRE_EQ(-100, si.minimum());
    REQUIRE_EQ(100, si.maximum());
    REQUIRE(e57::test::approxEqual(0.01, si.scale(), 1e-9));
    REQUIRE(e57::test::approxEqual(0.0, si.offset(), 1e-9));

    imf.close();
  }

  TEST_CASE("ScaledIntegerNode(imf, int, int, int) constructor")
  {
    TempFile      tempFile;
    ImageFile     imf(tempFile.c_str(), "w");
    StructureNode root = imf.root();
    root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
    root.set("guid", StringNode(imf, "{00000000-0000-0000-0000-000000000521}"));

    ScaledIntegerNode si(imf, static_cast<int>(3), static_cast<int>(-50), static_cast<int>(50), 0.1, 0.0);
    root.set("field", si);

    REQUIRE_EQ(3, si.rawValue());
    REQUIRE_EQ(-50, si.minimum());
    REQUIRE_EQ(50, si.maximum());

    imf.close();
  }

  TEST_CASE("ScaledIntegerNode(imf, double, double, double) scaledValue constructor")
  {
    TempFile      tempFile;
    ImageFile     imf(tempFile.c_str(), "w");
    StructureNode root = imf.root();
    root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
    root.set("guid", StringNode(imf, "{00000000-0000-0000-0000-000000000522}"));

    const double scale  = 0.001;
    const double rawVal = 750.0;

    ScaledIntegerNode si(imf, rawVal * scale, -1.0, 1.0, scale, 0.0);
    root.set("field", si);

    REQUIRE(e57::test::approxEqual(rawVal * scale, si.scaledValue(), 1e-9));
    REQUIRE(e57::test::approxEqual(-1.0, si.scaledMinimum(), 1e-9));
    REQUIRE(e57::test::approxEqual(1.0, si.scaledMaximum(), 1e-9));

    imf.close();
  }
}
