/*
 * source_dest_buffer_types_test.cpp - Tests for SourceDestBuffer constructors and
 *   methods that were not previously exercised: int8_t, uint8_t, int16_t, uint16_t,
 *   uint32_t, bool, ustring vector variants, stride(), and the vector-overload of
 *   CompressedVectorReader::read() / CompressedVectorWriter::write().
 *
 * Copyright (c) 2024 openE57 Contributors
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN
#include "test_utils.h"

#include <cstdint>

using namespace e57;
using e57::test::TempFile;

TEST_SUITE("SourceDestBuffer Type Tests")
{
  TEST_CASE("int8_t buffer has E57_INT8 representation and correct stride")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    int8_t           buf[4] = {0};
    SourceDestBuffer sdb(imf, "field", buf, 4);

    REQUIRE_EQ(E57_INT8, sdb.memoryRepresentation());
    REQUIRE_EQ(4u, sdb.capacity());
    REQUIRE_EQ(sizeof(int8_t), sdb.stride());

    imf.close();
  }

  TEST_CASE("uint8_t buffer has E57_UINT8 representation and correct stride")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    uint8_t          buf[4] = {0};
    SourceDestBuffer sdb(imf, "field", buf, 4);

    REQUIRE_EQ(E57_UINT8, sdb.memoryRepresentation());
    REQUIRE_EQ(sizeof(uint8_t), sdb.stride());

    imf.close();
  }

  TEST_CASE("int16_t buffer has E57_INT16 representation and correct stride")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    int16_t          buf[4] = {0};
    SourceDestBuffer sdb(imf, "field", buf, 4);

    REQUIRE_EQ(E57_INT16, sdb.memoryRepresentation());
    REQUIRE_EQ(sizeof(int16_t), sdb.stride());

    imf.close();
  }

  TEST_CASE("uint16_t buffer has E57_UINT16 representation and correct stride")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    uint16_t         buf[4] = {0};
    SourceDestBuffer sdb(imf, "field", buf, 4);

    REQUIRE_EQ(E57_UINT16, sdb.memoryRepresentation());
    REQUIRE_EQ(sizeof(uint16_t), sdb.stride());

    imf.close();
  }

  TEST_CASE("uint32_t buffer has E57_UINT32 representation and correct stride")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    uint32_t         buf[4] = {0};
    SourceDestBuffer sdb(imf, "field", buf, 4);

    REQUIRE_EQ(E57_UINT32, sdb.memoryRepresentation());
    REQUIRE_EQ(sizeof(uint32_t), sdb.stride());

    imf.close();
  }

  TEST_CASE("bool buffer has E57_BOOL representation and correct stride")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    bool             buf[4] = {false};
    SourceDestBuffer sdb(imf, "field", buf, 4);

    REQUIRE_EQ(E57_BOOL, sdb.memoryRepresentation());
    REQUIRE_EQ(sizeof(bool), sdb.stride());

    imf.close();
  }

  TEST_CASE("ustring vector buffer has E57_USTRING representation")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    std::vector<ustring> buf;
    SourceDestBuffer     sdb(imf, "field", &buf);

    REQUIRE_EQ(E57_USTRING, sdb.memoryRepresentation());

    imf.close();
  }

  TEST_CASE("stride() reflects custom stride value")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    int64_t          buf[4]       = {0};
    const size_t     customStride = sizeof(int64_t) * 2;
    SourceDestBuffer sdb(imf, "field", buf, 4, false, false, customStride);

    REQUIRE_EQ(customStride, sdb.stride());

    imf.close();
  }

  TEST_CASE("doConversion and doScaling flags are stored correctly")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    int32_t          buf[4] = {0};
    SourceDestBuffer sdbDefault(imf, "field", buf, 4);
    REQUIRE(!sdbDefault.doConversion());
    REQUIRE(!sdbDefault.doScaling());

    SourceDestBuffer sdbBoth(imf, "field", buf, 4, true, true);
    REQUIRE(sdbBoth.doConversion());
    REQUIRE(sdbBoth.doScaling());

    imf.close();
  }
}

TEST_SUITE("CompressedVectorWriter vector-overload Tests")
{
  TEST_CASE("write(vector<SourceDestBuffer>, count) writes data successfully")
  {
    TempFile tempFile;

    const size_t N       = 5;
    int64_t      data[N] = {10, 20, 30, 40, 50};

    {
      ImageFile     imf(tempFile.c_str(), "w");
      StructureNode root = imf.root();
      root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
      root.set("guid", StringNode(imf, "{00000000-0000-0000-0000-000000000400}"));

      StructureNode proto(imf);
      proto.set("value", IntegerNode(imf, 0, 0, 100));

      VectorNode           codecs(imf, true);
      CompressedVectorNode cv(imf, proto, codecs);
      root.set("data", cv);

      std::vector<SourceDestBuffer> bufs;
      bufs.push_back(SourceDestBuffer(imf, "value", data, N, true, true));

      CompressedVectorWriter writer = cv.writer(bufs);
      writer.write(bufs, N);
      writer.close();

      imf.close();
    }

    REQUIRE(std::filesystem::exists(tempFile.string()));
  }
}

TEST_SUITE("CompressedVectorReader vector-overload Tests")
{
  TEST_CASE("read(vector<SourceDestBuffer>) reads back written data")
  {
    TempFile tempFile;

    const size_t N            = 8;
    int64_t      writeData[N] = {1, 2, 3, 4, 5, 6, 7, 8};
    int64_t      readData[N]  = {0};

    {
      ImageFile     imf(tempFile.c_str(), "w");
      StructureNode root = imf.root();
      root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
      root.set("guid", StringNode(imf, "{00000000-0000-0000-0000-000000000401}"));

      StructureNode proto(imf);
      proto.set("value", IntegerNode(imf, 0, 0, 100));

      VectorNode           codecs(imf, true);
      CompressedVectorNode cv(imf, proto, codecs);
      root.set("data", cv);

      std::vector<SourceDestBuffer> bufs;
      bufs.push_back(SourceDestBuffer(imf, "value", writeData, N, true, true));

      CompressedVectorWriter writer = cv.writer(bufs);
      writer.write(N);
      writer.close();

      imf.close();
    }

    {
      ImageFile            imf(tempFile.c_str(), "r");
      StructureNode        root = imf.root();
      CompressedVectorNode cv(root.get("data"));

      std::vector<SourceDestBuffer> dbufs;
      dbufs.push_back(SourceDestBuffer(imf, "value", readData, N, true, true));

      CompressedVectorReader reader = cv.reader(dbufs);
      unsigned               count  = reader.read(dbufs);
      reader.close();

      REQUIRE_EQ(N, count);
      for (size_t i = 0; i < N; ++i)
      {
        REQUIRE_EQ(writeData[i], readData[i]);
      }

      imf.close();
    }
  }

  TEST_CASE("uint16_t round-trip via CompressedVectorNode")
  {
    TempFile tempFile;

    const size_t N         = 6;
    uint16_t     writeR[N] = {100, 200, 300, 400, 500, 600};
    uint16_t     writeG[N] = {10, 20, 30, 40, 50, 60};
    uint16_t     writeB[N] = {1, 2, 3, 4, 5, 6};
    uint16_t     readR[N]  = {0};
    uint16_t     readG[N]  = {0};
    uint16_t     readB[N]  = {0};

    {
      ImageFile     imf(tempFile.c_str(), "w");
      StructureNode root = imf.root();
      root.set("formatName", StringNode(imf, "ASTM E57 3D Imaging Data File"));
      root.set("guid", StringNode(imf, "{00000000-0000-0000-0000-000000000402}"));

      StructureNode proto(imf);
      proto.set("r", IntegerNode(imf, 0, 0, 65535));
      proto.set("g", IntegerNode(imf, 0, 0, 65535));
      proto.set("b", IntegerNode(imf, 0, 0, 65535));

      VectorNode           codecs(imf, true);
      CompressedVectorNode cv(imf, proto, codecs);
      root.set("colors", cv);

      std::vector<SourceDestBuffer> bufs;
      bufs.push_back(SourceDestBuffer(imf, "r", writeR, N, true, true));
      bufs.push_back(SourceDestBuffer(imf, "g", writeG, N, true, true));
      bufs.push_back(SourceDestBuffer(imf, "b", writeB, N, true, true));

      CompressedVectorWriter writer = cv.writer(bufs);
      writer.write(N);
      writer.close();

      imf.close();
    }

    {
      ImageFile            imf(tempFile.c_str(), "r");
      StructureNode        root = imf.root();
      CompressedVectorNode cv(root.get("colors"));

      std::vector<SourceDestBuffer> dbufs;
      dbufs.push_back(SourceDestBuffer(imf, "r", readR, N, true, true));
      dbufs.push_back(SourceDestBuffer(imf, "g", readG, N, true, true));
      dbufs.push_back(SourceDestBuffer(imf, "b", readB, N, true, true));

      CompressedVectorReader reader = cv.reader(dbufs);
      unsigned               count  = reader.read(dbufs);
      reader.close();

      REQUIRE_EQ(N, count);
      for (size_t i = 0; i < N; ++i)
      {
        REQUIRE_EQ(writeR[i], readR[i]);
        REQUIRE_EQ(writeG[i], readG[i]);
        REQUIRE_EQ(writeB[i], readB[i]);
      }

      imf.close();
    }
  }
}
