/*
 * structure_vector_test.cpp - Tests for StructureNode and VectorNode
 *
 * Copyright (c) 2024 openE57 Contributors
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties whom the Software is furnished
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN

#include "test_utils.h"

using namespace e57;
using e57::test::TempFile;

TEST_SUITE("StructureNode Tests")
{
  TEST_CASE("StructureNode default construction")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    StructureNode s(imf);

    REQUIRE_EQ(E57_STRUCTURE, Node(s).type());
    REQUIRE_EQ(0, s.childCount());

    imf.close();
  }

  TEST_CASE("StructureNode set and get integer")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    StructureNode s(imf);
    s.set("intField", IntegerNode(imf, 42));

    REQUIRE(s.isDefined("intField"));
    REQUIRE_EQ(1, s.childCount());

    IntegerNode intNode(s.get("intField"));
    REQUIRE_EQ(42, intNode.value());

    imf.close();
  }

  TEST_CASE("StructureNode set and get float")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    StructureNode s(imf);
    s.set("floatField", FloatNode(imf, 3.14159));

    REQUIRE(s.isDefined("floatField"));

    FloatNode floatNode(s.get("floatField"));
    REQUIRE(std::abs(floatNode.value() - 3.14159) < 1e-10);

    imf.close();
  }

  TEST_CASE("StructureNode set and get string")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    StructureNode s(imf);
    s.set("stringField", StringNode(imf, "hello world"));

    REQUIRE(s.isDefined("stringField"));

    StringNode stringNode(s.get("stringField"));
    REQUIRE_EQ("hello world", stringNode.value());

    imf.close();
  }

  TEST_CASE("StructureNode set multiple fields")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    StructureNode s(imf);
    s.set("intField", IntegerNode(imf, 100));
    s.set("floatField", FloatNode(imf, 2.71828));
    s.set("stringField", StringNode(imf, "test"));

    REQUIRE_EQ(3, s.childCount());
    REQUIRE(s.isDefined("intField"));
    REQUIRE(s.isDefined("floatField"));
    REQUIRE(s.isDefined("stringField"));
    REQUIRE(!s.isDefined("nonexistent"));

    imf.close();
  }

  TEST_CASE("StructureNode nested structures")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    StructureNode outer(imf);
    StructureNode inner(imf);

    inner.set("value", IntegerNode(imf, 999));
    outer.set("nested", inner);

    REQUIRE(outer.isDefined("nested"));

    StructureNode retrieved(outer.get("nested"));
    REQUIRE(retrieved.isDefined("value"));

    IntegerNode valueNode(retrieved.get("value"));
    REQUIRE_EQ(999, valueNode.value());

    imf.close();
  }

  TEST_CASE("StructureNode isDefined returns false for missing fields")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    StructureNode s(imf);
    s.set("existing", IntegerNode(imf, 1));

    REQUIRE(s.isDefined("existing"));
    REQUIRE(!s.isDefined("missing"));

    imf.close();
  }

  TEST_CASE("StructureNode with vector child")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    StructureNode s(imf);
    VectorNode    v(imf, true);
    v.append(IntegerNode(imf, 1));
    v.append(IntegerNode(imf, 2));
    v.append(IntegerNode(imf, 3));

    s.set("vectorField", v);

    REQUIRE(s.isDefined("vectorField"));

    VectorNode retrieved(s.get("vectorField"));
    REQUIRE_EQ(3, retrieved.childCount());

    imf.close();
  }

  TEST_CASE("StructureNode isAttached when added to attached parent")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    // Get the root which is attached when file is opened for writing
    StructureNode root = imf.root();

    // Create parent and add to attached root
    StructureNode parent(imf);
    root.set("parent", parent);

    // Now parent is attached, so any child added to it should be attached too
    StructureNode child(imf);
    REQUIRE(!child.isAttached());

    parent.set("child", child);

    REQUIRE(child.isAttached());

    imf.close();
  }

  TEST_CASE("StructureNode dump produces output")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    StructureNode s(imf);
    s.set("field1", IntegerNode(imf, 42));
    s.set("field2", StringNode(imf, "test"));

    std::stringstream ss;
    s.dump(0, ss);

    std::string output = ss.str();
    REQUIRE(!output.empty());

    imf.close();
  }

  TEST_CASE("StructureNode checkInvariant")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    StructureNode s(imf);
    s.set("test", IntegerNode(imf, 123));

    REQUIRE_NOTHROW(s.checkInvariant());

    imf.close();
  }

  TEST_CASE("StructureNode prevents duplicate field names")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    StructureNode s(imf);
    s.set("field", IntegerNode(imf, 1));

    // Setting the same field twice should throw or overwrite
    // Depending on implementation
    REQUIRE_THROWS_AS(s.set("field", IntegerNode(imf, 2)), E57Exception);

    imf.close();
  }
}

TEST_SUITE("VectorNode Tests")
{
  TEST_CASE("VectorNode homogeneous construction")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    VectorNode v(imf, false); // homogeneous

    REQUIRE_EQ(E57_VECTOR, Node(v).type());
    REQUIRE(!v.allowHeteroChildren());
    REQUIRE_EQ(0, v.childCount());

    imf.close();
  }

  TEST_CASE("VectorNode heterogeneous construction")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    VectorNode v(imf, true); // heterogeneous

    REQUIRE(v.allowHeteroChildren());

    imf.close();
  }

  TEST_CASE("VectorNode append and get")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    VectorNode v(imf, false);
    v.append(IntegerNode(imf, 10));
    v.append(IntegerNode(imf, 20));
    v.append(IntegerNode(imf, 30));

    REQUIRE_EQ(3, v.childCount());

    IntegerNode n0(v.get(0));
    IntegerNode n1(v.get(1));
    IntegerNode n2(v.get(2));

    REQUIRE_EQ(10, n0.value());
    REQUIRE_EQ(20, n1.value());
    REQUIRE_EQ(30, n2.value());

    imf.close();
  }

  TEST_CASE("VectorNode isDefined with string path")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    VectorNode v(imf, false);
    v.append(IntegerNode(imf, 1));
    v.append(IntegerNode(imf, 2));

    REQUIRE(v.isDefined("0"));
    REQUIRE(v.isDefined("1"));
    REQUIRE(!v.isDefined("2"));
    REQUIRE(!v.isDefined("100"));

    imf.close();
  }

  TEST_CASE("VectorNode heterogeneous with different types")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    VectorNode v(imf, true); // heterogeneous
    v.append(IntegerNode(imf, 42));
    v.append(FloatNode(imf, 3.14));
    v.append(StringNode(imf, "test"));

    REQUIRE_EQ(3, v.childCount());

    IntegerNode i(v.get(0));
    FloatNode   f(v.get(1));
    StringNode  s(v.get(2));

    REQUIRE_EQ(42, i.value());
    REQUIRE(std::abs(f.value() - 3.14) < 1e-10);
    REQUIRE_EQ("test", s.value());

    imf.close();
  }

  TEST_CASE("VectorNode homogeneous enforces same type")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    VectorNode v(imf, false); // homogeneous
    v.append(IntegerNode(imf, 1));

    // Should throw when adding different type to homogeneous vector
    REQUIRE_THROWS_AS(v.append(FloatNode(imf, 2.0)), E57Exception);

    imf.close();
  }

  TEST_CASE("VectorNode large number of elements")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    VectorNode v(imf, false);

    const int N = 1000;
    for (int i = 0; i < N; ++i)
    {
      v.append(IntegerNode(imf, i));
    }

    REQUIRE_EQ(N, v.childCount());

    // Verify first and last elements
    IntegerNode first(v.get(0));
    IntegerNode last(v.get(N - 1));

    REQUIRE_EQ(0, first.value());
    REQUIRE_EQ(N - 1, last.value());

    imf.close();
  }

  TEST_CASE("VectorNode nested vectors")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    VectorNode outer(imf, true);

    VectorNode inner1(imf, false);
    inner1.append(IntegerNode(imf, 1));
    inner1.append(IntegerNode(imf, 2));

    VectorNode inner2(imf, false);
    inner2.append(IntegerNode(imf, 3));
    inner2.append(IntegerNode(imf, 4));

    outer.append(inner1);
    outer.append(inner2);

    REQUIRE_EQ(2, outer.childCount());

    VectorNode retrieved1(outer.get(0));
    VectorNode retrieved2(outer.get(1));

    REQUIRE_EQ(2, retrieved1.childCount());
    REQUIRE_EQ(2, retrieved2.childCount());

    imf.close();
  }

  TEST_CASE("VectorNode isAttached when added to attached parent")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    StructureNode root = imf.root();
    VectorNode    parent(imf, true);
    root.set("parent", parent);

    VectorNode child(imf, false);
    REQUIRE(!child.isAttached());

    parent.append(child);

    REQUIRE(child.isAttached());

    imf.close();
  }

  TEST_CASE("VectorNode dump produces output")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    VectorNode v(imf, false);
    v.append(IntegerNode(imf, 1));
    v.append(IntegerNode(imf, 2));
    v.append(IntegerNode(imf, 3));

    std::stringstream ss;
    v.dump(0, ss);

    std::string output = ss.str();
    REQUIRE(!output.empty());

    imf.close();
  }

  TEST_CASE("VectorNode checkInvariant")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    VectorNode v(imf, false);
    v.append(IntegerNode(imf, 100));

    REQUIRE_NOTHROW(v.checkInvariant());

    imf.close();
  }

  TEST_CASE("VectorNode get throws on out of bounds")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    VectorNode v(imf, false);
    v.append(IntegerNode(imf, 1));

    REQUIRE_THROWS_AS(v.get(1), E57Exception);  // Index 1 doesn't exist
    REQUIRE_THROWS_AS(v.get(-1), E57Exception); // Negative index

    imf.close();
  }
}
