/*
 * terminal_nodes_test.cpp - Tests for E57 Foundation API terminal node types
 *
 * Copyright (c) 2024 openE57 Contributors
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#define DOCTEST_CONFIG_IMPLEMENT_WITH_MAIN

#include "test_utils.h"

using namespace e57;
using e57::test::TempFile;

TEST_SUITE("IntegerNode Tests")
{
  TEST_CASE("IntegerNode constructor with value")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    IntegerNode node(imf, 42);

    REQUIRE_EQ(42, node.value());

    imf.close();
  }

  TEST_CASE("IntegerNode with minimum and maximum bounds")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    int64_t     minValue = -1000;
    int64_t     maxValue = 1000;
    IntegerNode node(imf, 42, minValue, maxValue);

    REQUIRE_EQ(42, node.value());
    REQUIRE_EQ(minValue, node.minimum());
    REQUIRE_EQ(maxValue, node.maximum());

    imf.close();
  }

  TEST_CASE("IntegerNode is attached to ImageFile")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    IntegerNode node(imf, 123);

    REQUIRE(!node.isAttached());
    REQUIRE_EQ(imf, node.destImageFile());

    imf.close();
  }

  TEST_CASE("IntegerNode dump produces output")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    IntegerNode node(imf, 999, 0, 1000);

    std::stringstream ss;
    node.dump(0, ss);

    std::string output = ss.str();
    REQUIRE(!output.empty());

    imf.close();
  }

  TEST_CASE("IntegerNode checkInvariant")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    IntegerNode node(imf, 42);

    REQUIRE_NOTHROW(node.checkInvariant());

    imf.close();
  }
}

TEST_SUITE("FloatNode Tests")
{
  TEST_CASE("FloatNode constructor with single precision")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    FloatNode node(imf, 3.14f, E57_SINGLE);

    REQUIRE_EQ(E57_SINGLE, node.precision());
    REQUIRE(std::abs(node.value() - 3.14f) < 0.001);

    imf.close();
  }

  TEST_CASE("FloatNode constructor with double precision")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    FloatNode node(imf, 3.141592653589793, E57_DOUBLE);

    REQUIRE_EQ(E57_DOUBLE, node.precision());
    REQUIRE(std::abs(node.value() - 3.141592653589793) < 1e-15);

    imf.close();
  }

  TEST_CASE("FloatNode with minimum and maximum bounds")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    double    minValue = -1000.0;
    double    maxValue = 1000.0;
    FloatNode node(imf, 3.14, E57_DOUBLE, minValue, maxValue);

    REQUIRE(std::abs(node.value() - 3.14) < 1e-10);
    REQUIRE(std::abs(node.minimum() - minValue) < 1e-10);
    REQUIRE(std::abs(node.maximum() - maxValue) < 1e-10);

    imf.close();
  }

  TEST_CASE("FloatNode handles special values")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    FloatNode zeroNode(imf, 0.0, E57_DOUBLE);
    REQUIRE_EQ(0.0, zeroNode.value());

    FloatNode negNode(imf, -123.456, E57_DOUBLE);
    REQUIRE(std::abs(negNode.value() - (-123.456)) < 1e-10);

    FloatNode smallNode(imf, 1e-300, E57_DOUBLE);
    REQUIRE(std::abs(smallNode.value() - 1e-300) < 1e-310);

    FloatNode largeNode(imf, 1e300, E57_DOUBLE);
    REQUIRE(std::abs(largeNode.value() - 1e300) < 1e290);

    imf.close();
  }

  TEST_CASE("FloatNode is attached to ImageFile")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    FloatNode node(imf, 2.71828);

    REQUIRE(!node.isAttached());
    REQUIRE_EQ(imf, node.destImageFile());

    imf.close();
  }

  TEST_CASE("FloatNode dump produces output")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    FloatNode node(imf, 1.41421356, E57_DOUBLE);

    std::stringstream ss;
    node.dump(0, ss);

    std::string output = ss.str();
    REQUIRE(!output.empty());

    imf.close();
  }

  TEST_CASE("FloatNode checkInvariant")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    FloatNode node(imf, 1.23456789);

    REQUIRE_NOTHROW(node.checkInvariant());

    imf.close();
  }
}

TEST_SUITE("StringNode Tests")
{
  TEST_CASE("StringNode constructor with value")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    StringNode node(imf, "Hello, E57!");

    REQUIRE_EQ("Hello, E57!", node.value());

    imf.close();
  }

  TEST_CASE("StringNode with empty string")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    StringNode node(imf, "");

    REQUIRE_EQ("", node.value());

    imf.close();
  }

  TEST_CASE("StringNode is attached to ImageFile")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    StringNode node(imf, "test string");

    REQUIRE(!node.isAttached());
    REQUIRE_EQ(imf, node.destImageFile());

    imf.close();
  }

  TEST_CASE("StringNode dump produces output")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    StringNode node(imf, "test value");

    std::stringstream ss;
    node.dump(0, ss);

    std::string output = ss.str();
    REQUIRE(!output.empty());

    imf.close();
  }

  TEST_CASE("StringNode checkInvariant")
  {
    TempFile  tempFile;
    ImageFile imf(tempFile.c_str(), "w");

    StringNode node(imf, "invariant test");

    REQUIRE_NOTHROW(node.checkInvariant());

    imf.close();
  }
}
