/*
 * test_utils.h - Test utilities and fixtures for openE57 test suite
 *
 * Copyright (c) 2024 openE57 Contributors
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef OPENE57_TEST_UTILS_H
#define OPENE57_TEST_UTILS_H

// NOTE: api.h and openE57Simple.h both define `constexpr double PI` protected
// only by `#ifndef PI` (a macro guard), so they cannot be included together
// without a redefinition error.  Test files that need core:: types (api.h)
// should include it directly; this header only pulls in openE57Simple.h which
// transitively includes openE57.h.
#include <doctest/doctest.h>
#include <openE57/openE57Simple.h>

#include <cmath>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <limits>
#include <memory>
#include <random>
#include <sstream>
#include <string>
#include <vector>

namespace e57
{
namespace test
{

  // ====================================================================
  // Temporary File Management
  // ====================================================================

  /**
   * @brief RAII wrapper for temporary files that automatically cleans up.
   *
   * Accepts an optional extension (default ".e57").  Use TempFile(".las") for
   * LAS files.
   */
  class TempFile
  {
  public:
    explicit TempFile(const std::string& extension = ".e57")
    {
      std::random_device              rd;
      std::mt19937                    gen(rd());
      std::uniform_int_distribution<> dis(0, 999999);

      std::stringstream ss;
      ss << "test_temp_" << dis(gen) << extension;
      path_ = std::filesystem::temp_directory_path() / ss.str();
    }

    ~TempFile()
    {
      if (std::filesystem::exists(path_))
      {
        std::error_code ec;
        std::filesystem::remove(path_, ec);
      }
    }

    // Non-copyable, movable
    TempFile(const TempFile&)                = delete;
    TempFile& operator=(const TempFile&)     = delete;
    TempFile(TempFile&&) noexcept            = default;
    TempFile& operator=(TempFile&&) noexcept = default;

    std::string string() const
    {
      return path_.string();
    }
    const char* c_str() const
    {
      return path_.c_str();
    }
    bool exists() const
    {
      return std::filesystem::exists(path_);
    }

  private:
    std::filesystem::path path_;
  };

  // ====================================================================
  // Binary File Corruption Helper
  // ====================================================================

  /**
   * @brief Overwrite a small region in the middle of a binary file with
   * garbage data, producing a file that is readable but structurally invalid.
   */
  inline void corruptBinaryFile(const std::string& path)
  {
    std::fstream file(path, std::ios::binary | std::ios::in | std::ios::out);
    if (file)
    {
      file.seekp(100);
      file.write("CORRUPTED_DATA", 14);
    }
  }

  // ====================================================================
  // Assertion Helpers
  // ====================================================================

  /**
   * @brief Check if two floating point values are approximately equal.
   */
  inline bool approxEqual(double a, double b, double epsilon = 1e-9)
  {
    if (std::abs(a - b) < epsilon)
      return true;
    double diff    = std::abs(a - b);
    double largest = std::max(std::abs(a), std::abs(b));
    return diff < largest * epsilon;
  }

  /**
   * @brief Check if a quaternion represents a valid rotation (unit quaternion).
   */
  inline bool isUnitQuaternion(const Quaternion& q, double epsilon = 1e-6)
  {
    double magnitude = std::sqrt(q.w * q.w + q.x * q.x + q.y * q.y + q.z * q.z);
    return approxEqual(magnitude, 1.0, epsilon);
  }

  // ====================================================================
  // Error Checking Helper
  // ====================================================================

  /**
   * @brief Return true if calling func() throws E57Exception with the given error code.
   */
  template <typename Func>
  bool throwsErrorCode(ErrorCode expectedCode, Func func)
  {
    try
    {
      func();
      return false;
    }
    catch (const E57Exception& e)
    {
      return e.errorCode() == expectedCode;
    }
    catch (...)
    {
      return false;
    }
  }

  // ====================================================================
  // Test Configuration
  // ====================================================================

  /**
   * @brief Common test configuration constants.
   */
  struct TestConfig
  {
    static constexpr size_t   SMALL_POINT_COUNT    = 10;
    static constexpr size_t   MEDIUM_POINT_COUNT   = 100;
    static constexpr size_t   LARGE_POINT_COUNT    = 1000;
    static constexpr double   COORDINATE_TOLERANCE = 1e-6;
    static constexpr double   QUATERNION_TOLERANCE = 1e-6;
    static constexpr unsigned RANDOM_SEED          = 42;
  };

} // namespace test
} // namespace e57

#endif // OPENE57_TEST_UTILS_H
