/*
 * xml_traits.hpp - XML abstraction layer traits interface
 *
 * Copyright (c) 2026 openE57 Contributors
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#pragma once

#include <memory>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>

namespace e57::xml
{

/// XML error codes for operations
enum class XmlErrorCode
{
  OK = 0,
  PARSE_ERROR,
  FILE_NOT_FOUND,
  OUT_OF_MEMORY,
  INVALID_ENCODING,
  UNEXPECTED_ELEMENT,
  MISSING_ATTRIBUTE,
  INTERNAL_ERROR,
  XML_PARSER_INIT
};

/// Common XML exception class
class XmlException : public std::runtime_error
{
public:
  XmlException(XmlErrorCode code, std::string message, std::string systemId = "", int line = -1, int column = -1)
  : std::runtime_error(std::move(message)), code_(code), systemId_(std::move(systemId)), line_(line), column_(column)
  {}

  XmlErrorCode code() const noexcept
  {
    return code_;
  }
  const std::string& systemId() const noexcept
  {
    return systemId_;
  }
  int line() const noexcept
  {
    return line_;
  }
  int column() const noexcept
  {
    return column_;
  }

private:
  XmlErrorCode code_;
  std::string  systemId_;
  int          line_;
  int          column_;
};

/// Each backend specializes AttributeList<std::string> for its native attribute type.
template <typename StringT>
class AttributeList;

/// Primary template for XML traits — triggers a clear error if used with an unsupported backend.
/// Each backend must provide a full specialization of this struct that implements:
///   - initialize() / terminate()  — library lifecycle
///   - createParser()              — returns std::unique_ptr<ParserType>
///   - parseMemory(parser, data, size, handler)
///
/// The handler passed to parse* methods must expose SAX-style callbacks:
///   startDocument(), endDocument(), startElement(...), endElement(...),
///   characters(...), warning(...), error(...), fatalError(...)
template <typename Backend>
struct XmlTraits
{
  static_assert(sizeof(Backend) == 0, "XmlTraits must be fully specialized for the chosen XML backend");
};

} // namespace e57::xml
