/*
 * xml_backend.hpp - Auto-select XML backend based on CMake configuration
 *
 * Copyright (c) 2026 openE57 Contributors
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#pragma once

#if defined(E57_XML_BACKEND_XERCES)
#  include "backends/xerces_traits.hpp"
namespace e57::xml
{
using DefaultBackend = XercesBackend;
}
#elif defined(E57_XML_BACKEND_LIBXML2)
#  include "backends/libxml2_traits.hpp"
namespace e57::xml
{
using DefaultBackend = Libxml2Backend;
}
#elif defined(E57_XML_BACKEND_PUGIXML)
#  include "backends/pugi_traits.hpp"
namespace e57::xml
{
using DefaultBackend = PugiBackend;
}
#else
#  error "No XML backend defined. Set E57_XML_BACKEND in CMake to 'auto', 'xerces', 'libxml2', or 'pugixml'"
#endif
