find_package(Threads REQUIRED)

# Find the Xerces libraries
if(NOT EXISTS ${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
  set(Xerces_USE_STATIC_LIBS On)
  find_package(Xerces 3.2 REQUIRED)

  set(XML_LIBRARIES ${Xerces_LIBRARY})
  set(XML_INCLUDE_DIRS ${Xerces_INCLUDE_DIR})
  list(APPEND compiler_definitions XERCES_STATIC_LIBRARY)
else()
    set(XML_LIBRARIES CONAN_PKG::xerces-c)
    set(XML_INCLUDE_DIRS ${CONAN_INCLUDE_DIRS_XERCES-C})
endif()
  
if(${CMAKE_SYSTEM_NAME} STREQUAL "Linux")
  list(APPEND compiler_definitions LINUX)
  if(NOT EXISTS ${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
    find_package(ICU 67.1 REQUIRED)
    set(XML_LIBRARIES ${XML_LIBRARIES} ${ICU_LIBRARIES})
    set(XML_INCLUDE_DIRS ${XML_INCLUDE_DIRS} ${ICU_INCLUDE_DIRS})
  else()
    set(XML_LIBRARIES ${XML_LIBRARIES} CONAN_PKG::icu)
    set(XML_INCLUDE_DIRS ${XML_INCLUDE_DIRS} ${CONAN_INCLUDE_DIRS_ICU})
  endif()
elseif(${CMAKE_SYSTEM_NAME} STREQUAL "Windows")
 list(APPEND compiler_definitions WINDOWS)
endif()
