/*
 * libxml2_traits.hpp - libxml2 XML backend implementation
 *
 * Copyright (c) 2026 openE57 Contributors
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#pragma once

#include "../xml_traits.hpp"

#include <libxml/parser.h>
#include <libxml/tree.h>
#include <libxml/xmlerror.h>

#include <cstdarg>
#include <cstring>
#include <limits>
#include <memory>
#include <mutex>
#include <sstream>
#include <string>
#include <vector>

namespace e57::xml
{

struct Libxml2Backend
{};

/// Adapter class that bridges libxml2 SAX2 callbacks to our SaxHandler interface.
/// Uses the libxml2 SAX2 API (startElementNs/endElementNs) for namespace-aware parsing.
template <typename HandlerT>
class Libxml2SaxBridge
{
public:
  explicit Libxml2SaxBridge(HandlerT& handler) : handler_(handler) {}

  /// Populate an xmlSAXHandler struct with all callbacks wired to this bridge.
  void populateSaxHandler(xmlSAXHandler& sax)
  {
    memset(&sax, 0, sizeof(xmlSAXHandler));
    sax.initialized           = XML_SAX2_MAGIC;
    sax.startDocument         = &Libxml2SaxBridge::startDocumentCb;
    sax.endDocument           = &Libxml2SaxBridge::endDocumentCb;
    sax.startElementNs        = &Libxml2SaxBridge::startElementNsCb;
    sax.endElementNs          = &Libxml2SaxBridge::endElementNsCb;
    sax.characters            = &Libxml2SaxBridge::charactersCb;
    sax.cdataBlock            = &Libxml2SaxBridge::charactersCb;
    sax.processingInstruction = &Libxml2SaxBridge::processingInstructionCb;
    sax.warning               = &Libxml2SaxBridge::warningCb;
    sax.error                 = &Libxml2SaxBridge::errorCb;
    sax.fatalError            = &Libxml2SaxBridge::fatalErrorCb;
  }

private:
  static Libxml2SaxBridge* self(void* user_data)
  {
    return static_cast<Libxml2SaxBridge*>(user_data);
  }

  static std::string xmlStr(const xmlChar* str)
  {
    if (!str)
      return "";
    return std::string(reinterpret_cast<const char*>(str));
  }

  // --- Static callbacks (called by libxml2) ---

  static void startDocumentCb(void* user_data)
  {
    self(user_data)->handler_.startDocument();
  }

  static void endDocumentCb(void* user_data)
  {
    self(user_data)->handler_.endDocument();
  }

  static void startElementNsCb(void* user_data, const xmlChar* localname, const xmlChar* /*prefix*/, const xmlChar* URI, int nb_namespaces,
                                const xmlChar** namespaces, int nb_attributes, int /*nb_defaulted*/, const xmlChar** attributes)
  {
    std::string localName = xmlStr(localname);
    std::string nsUri     = xmlStr(URI);

    // In libxml2 SAX2 mode, namespace declarations (xmlns, xmlns:prefix) are reported
    // via the separate namespaces parameter, NOT in the attributes array. We must
    // inject them as pseudo-attributes so the E57 parser can find them.
    std::vector<std::pair<std::string, std::string>> attrs;
    attrs.reserve(static_cast<size_t>(nb_namespaces + nb_attributes));

    // Inject namespace declarations as attributes (xmlns="..." and xmlns:prefix="...")
    for (int i = 0; i < nb_namespaces; ++i)
    {
      const xmlChar* prefix = namespaces[2 * i];
      const xmlChar* uri    = namespaces[2 * i + 1];
      std::string    name   = prefix ? ("xmlns:" + xmlStr(prefix)) : "xmlns";
      attrs.emplace_back(std::move(name), xmlStr(uri));
    }

    // SAX2 attributes: 5 entries per attribute [localname, prefix, URI, value, end]
    for (int i = 0; i < nb_attributes; ++i)
    {
      std::string    name = xmlStr(attributes[5 * i]);
      std::string    value;
      const xmlChar* valStart = attributes[5 * i + 3];
      const xmlChar* valEnd   = attributes[5 * i + 4];
      if (valStart && valEnd && valEnd > valStart)
      {
        value = std::string(reinterpret_cast<const char*>(valStart), static_cast<size_t>(valEnd - valStart));
      }
      attrs.emplace_back(std::move(name), std::move(value));
    }

    self(user_data)->handler_.startElement(nsUri, localName, localName, attrs);
  }

  static void endElementNsCb(void* user_data, const xmlChar* localname, const xmlChar* /*prefix*/, const xmlChar* URI)
  {
    std::string localName = xmlStr(localname);
    std::string nsUri     = xmlStr(URI);
    self(user_data)->handler_.endElement(nsUri, localName, localName);
  }

  static void charactersCb(void* user_data, const xmlChar* ch, int len)
  {
    std::string text(reinterpret_cast<const char*>(ch), static_cast<size_t>(len));
    self(user_data)->handler_.characters(text);
  }

  static void processingInstructionCb(void* user_data, const xmlChar* target, const xmlChar* data)
  {
    self(user_data)->handler_.processingInstruction(xmlStr(target), xmlStr(data));
  }

  static void warningCb(void* user_data, const char* msg, ...)
  {
    char    buffer[1024];
    va_list ap;
    va_start(ap, msg);
    vsnprintf(buffer, sizeof(buffer), msg, ap);
    va_end(ap);

    XmlException ex(XmlErrorCode::PARSE_ERROR, std::string(buffer));
    self(user_data)->handler_.warning(ex);
  }

  static void errorCb(void* user_data, const char* msg, ...)
  {
    char    buffer[1024];
    va_list ap;
    va_start(ap, msg);
    vsnprintf(buffer, sizeof(buffer), msg, ap);
    va_end(ap);

    XmlException ex(XmlErrorCode::PARSE_ERROR, std::string(buffer));
    self(user_data)->handler_.error(ex);
  }

  static void fatalErrorCb(void* user_data, const char* msg, ...)
  {
    char    buffer[1024];
    va_list ap;
    va_start(ap, msg);
    vsnprintf(buffer, sizeof(buffer), msg, ap);
    va_end(ap);

    XmlException ex(XmlErrorCode::PARSE_ERROR, std::string(buffer));
    self(user_data)->handler_.fatalError(ex);
  }

  HandlerT& handler_;
};

template <>
struct XmlTraits<Libxml2Backend>
{
  using StringType       = std::string;
  using NativeStringType = const xmlChar*;
  using ParserType       = xmlSAXHandler;
  using InputSourceType  = std::string;

  static void initialize()
  {
    static std::once_flag flag;
    std::call_once(flag, []() { xmlInitParser(); });
  }

  /// xmlCleanupParser() is NOT thread-safe and must only be called at process exit.
  static void terminate() {}

  static std::unique_ptr<ParserType> createParser()
  {
    auto sax = std::make_unique<ParserType>();
    memset(sax.get(), 0, sizeof(xmlSAXHandler));
    sax->initialized = XML_SAX2_MAGIC;
    return sax;
  }

  template <typename HandlerT>
  static void parseMemory(ParserType& sax, const char* data, size_t size, HandlerT& handler)
  {
    if (size > static_cast<size_t>(std::numeric_limits<int>::max()))
      throw XmlException(XmlErrorCode::OUT_OF_MEMORY, "XML content too large for libxml2 chunk parser");

    Libxml2SaxBridge<HandlerT> bridge(handler);
    bridge.populateSaxHandler(sax);

    xmlParserCtxtPtr ctxt = xmlCreatePushParserCtxt(&sax, &bridge, nullptr, 0, nullptr);
    if (!ctxt)
    {
      throw XmlException(XmlErrorCode::PARSE_ERROR, "libxml2: failed to create parser context");
    }

    xmlCtxtUseOptions(ctxt, XML_PARSE_RECOVER);

    int             parseResult = xmlParseChunk(ctxt, data, static_cast<int>(size), 1);
    const xmlError* err         = xmlCtxtGetLastError(ctxt);
    xmlFreeParserCtxt(ctxt);

    if (parseResult != XML_ERR_OK || (err && err->level >= XML_ERR_ERROR))
    {
      std::string msg = err ? (err->message ? err->message : "parsing failed") : "parsing failed";
      throw XmlException(XmlErrorCode::PARSE_ERROR, "libxml2: " + msg);
    }
  }

  static std::string toStdString(NativeStringType str)
  {
    if (!str)
      return "";
    return std::string(reinterpret_cast<const char*>(str));
  }

};

} // namespace e57::xml
