/*
 * pugi_traits.hpp - Pugixml XML backend implementation
 *
 * Copyright (c) 2026 openE57 Contributors
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#pragma once

#include "../xml_traits.hpp"

#include <pugixml.hpp>

#include <memory>
#include <optional>
#include <string>
#include <vector>

namespace e57::xml
{

struct PugiBackend
{};

template <>
class AttributeList<std::string> final
{
public:
  explicit AttributeList(pugi::xml_node node) : node_(node) {}

  size_t length() const
  {
    return static_cast<size_t>(std::distance(node_.attributes_begin(), node_.attributes_end()));
  }

  bool hasAttribute(const std::string& name) const
  {
    return static_cast<bool>(node_.attribute(name.c_str()));
  }

  std::string getValue(const std::string& name) const
  {
    auto value = tryGetValue(name);
    if (!value)
    {
      throw XmlException(XmlErrorCode::MISSING_ATTRIBUTE, "Attribute not found: " + name);
    }
    return *value;
  }

  std::optional<std::string> tryGetValue(const std::string& name) const
  {
    pugi::xml_attribute attr = node_.attribute(name.c_str());
    if (!attr)
      return std::nullopt;
    return std::string(attr.value());
  }

  std::string getValue(size_t index) const
  {
    size_t i = 0;
    for (pugi::xml_attribute attr : node_.attributes())
    {
      if (i++ == index)
        return attr.value();
    }
    throw std::out_of_range("Attribute index out of range");
  }

  std::string getName(size_t index) const
  {
    size_t i = 0;
    for (pugi::xml_attribute attr : node_.attributes())
    {
      if (i++ == index)
        return attr.name();
    }
    throw std::out_of_range("Attribute index out of range");
  }

  std::string getUri(size_t /*index*/) const
  {
    return "";
  }

  std::vector<std::pair<std::string, std::string>> toVector() const
  {
    std::vector<std::pair<std::string, std::string>> result;
    result.reserve(length());
    for (pugi::xml_attribute attr : node_.attributes())
    {
      result.emplace_back(attr.name(), attr.value());
    }
    return result;
  }

private:
  pugi::xml_node node_;
};

template <typename HandlerT>
class PugiSaxWalker
{
public:
  explicit PugiSaxWalker(HandlerT& handler) : handler_(handler) {}

  void walk(pugi::xml_document& doc)
  {
    handler_.startDocument();

    for (pugi::xml_node child : doc.children())
    {
      walkNode(child);
    }

    handler_.endDocument();
  }

private:
  void walkNode(pugi::xml_node node)
  {
    switch (node.type())
    {
    case pugi::node_element: {
      AttributeList<std::string> attrs(node);
      handler_.startElement("", node.name(), node.name(), attrs.toVector());

      for (pugi::xml_node child : node.children())
      {
        walkNode(child);
      }

      handler_.endElement("", node.name(), node.name());
      break;
    }

    case pugi::node_pcdata:
    case pugi::node_cdata:
      handler_.characters(node.value());
      break;

    case pugi::node_pi:
      handler_.processingInstruction(node.name(), node.value());
      break;

    default:
      break;
    }
  }

  HandlerT& handler_;
};

template <>
struct XmlTraits<PugiBackend>
{
  using StringType       = std::string;
  using NativeStringType = const char*;
  using ParserType       = pugi::xml_document;
  using InputSourceType  = std::string;

  static void initialize() {}
  static void terminate() {}

  static std::unique_ptr<ParserType> createParser()
  {
    return std::make_unique<ParserType>();
  }

  template <typename HandlerT>
  static void parseMemory(ParserType& doc, const char* data, size_t size, HandlerT& handler)
  {
    pugi::xml_parse_result result = doc.load_buffer(data, size);

    if (!result)
    {
      throw XmlException(XmlErrorCode::PARSE_ERROR, result.description(), "", static_cast<int>(result.offset));
    }

    PugiSaxWalker<HandlerT> walker(handler);
    walker.walk(doc);
  }

  static std::string toStdString(NativeStringType str)
  {
    return str ? std::string(str) : std::string();
  }

};

} // namespace e57::xml
