/*
 * xerces_traits.hpp - Xerces-C XML backend implementation
 *
 * Copyright (c) 2026 openE57 Contributors
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#pragma once

#include "../xml_traits.hpp"

#include <xercesc/framework/LocalFileInputSource.hpp>
#include <xercesc/framework/MemBufInputSource.hpp>
#include <xercesc/sax2/Attributes.hpp>
#include <xercesc/sax2/DefaultHandler.hpp>
#include <xercesc/sax2/SAX2XMLReader.hpp>
#include <xercesc/sax2/XMLReaderFactory.hpp>
#include <xercesc/util/PlatformUtils.hpp>
#include <xercesc/util/TransService.hpp>
#include <xercesc/util/XMLString.hpp>
#include <xercesc/util/XMLUni.hpp>

#include <cstring>
#include <memory>
#include <mutex>
#include <optional>

XERCES_CPP_NAMESPACE_USE

namespace e57::xml
{

struct XercesBackend
{};

template <>
class AttributeList<std::string> final
{
public:
  explicit AttributeList(const Attributes& attrs) : attrs_(attrs) {}

  size_t length() const
  {
    return static_cast<size_t>(attrs_.getLength());
  }

  bool hasAttribute(const std::string& name) const
  {
    XMLCh*    xmlName = XMLString::transcode(name.c_str());
    XMLSize_t index;
    bool      found = attrs_.getIndex(xmlName, index);
    XMLString::release(&xmlName);
    return found;
  }

  std::string getValue(const std::string& name) const
  {
    auto value = tryGetValue(name);
    if (!value)
    {
      throw XmlException(XmlErrorCode::MISSING_ATTRIBUTE, "Attribute not found: " + name);
    }
    return *value;
  }

  std::optional<std::string> tryGetValue(const std::string& name) const
  {
    XMLCh*    xmlName = XMLString::transcode(name.c_str());
    XMLSize_t index;
    bool      found = attrs_.getIndex(xmlName, index);
    XMLString::release(&xmlName);

    if (!found)
      return std::nullopt;
    return transcode(attrs_.getValue(index));
  }

  std::string getValue(size_t index) const
  {
    return transcode(attrs_.getValue(static_cast<XMLSize_t>(index)));
  }

  std::string getName(size_t index) const
  {
    return transcode(attrs_.getQName(static_cast<XMLSize_t>(index)));
  }

  std::string getUri(size_t index) const
  {
    return transcode(attrs_.getURI(static_cast<XMLSize_t>(index)));
  }

  std::vector<std::pair<std::string, std::string>> toVector() const
  {
    std::vector<std::pair<std::string, std::string>> result;
    result.reserve(length());
    for (size_t i = 0; i < length(); ++i)
    {
      result.emplace_back(getName(i), getValue(i));
    }
    return result;
  }

private:
  static std::string transcode(const XMLCh* str)
  {
    if (!str || !*str)
      return "";
    char*       native = XMLString::transcode(str);
    std::string result(native);
    XMLString::release(&native);
    return result;
  }

  const Attributes& attrs_;
};

template <typename HandlerT>
class XercesHandlerBridge : public DefaultHandler
{
public:
  explicit XercesHandlerBridge(HandlerT& handler) : handler_(handler) {}

  void startDocument() override
  {
    handler_.startDocument();
  }

  void endDocument() override
  {
    handler_.endDocument();
  }

  void startElement(const XMLCh* const uri, const XMLCh* const localName, const XMLCh* const qName, const Attributes& attrs) override
  {
    AttributeList<std::string> attrList(attrs);
    handler_.startElement(transcode(uri), transcode(localName), transcode(qName), attrList.toVector());
  }

  void endElement(const XMLCh* const uri, const XMLCh* const localName, const XMLCh* const qName) override
  {
    handler_.endElement(transcode(uri), transcode(localName), transcode(qName));
  }

  void characters(const XMLCh* const chars, const XMLSize_t /*length*/) override
  {
    handler_.characters(transcode(chars));
  }

  void processingInstruction(const XMLCh* const target, const XMLCh* const data) override
  {
    handler_.processingInstruction(transcode(target), transcode(data));
  }

  void warning(const SAXParseException& ex) override
  {
    handler_.warning(makeException(XmlErrorCode::PARSE_ERROR, ex));
  }

  void error(const SAXParseException& ex) override
  {
    handler_.error(makeException(XmlErrorCode::PARSE_ERROR, ex));
  }

  void fatalError(const SAXParseException& ex) override
  {
    handler_.fatalError(makeException(XmlErrorCode::PARSE_ERROR, ex));
  }

private:
  static std::string transcode(const XMLCh* str)
  {
    if (!str || !*str)
      return "";
    char*       native = XMLString::transcode(str);
    std::string result(native);
    XMLString::release(&native);
    return result;
  }

  static XmlException makeException(XmlErrorCode code, const SAXParseException& ex)
  {
    return XmlException(code, transcode(ex.getMessage()), transcode(ex.getSystemId()), static_cast<int>(ex.getLineNumber()),
                        static_cast<int>(ex.getColumnNumber()));
  }

  HandlerT& handler_;
};

template <>
struct XmlTraits<XercesBackend>
{
  using StringType       = std::string;
  using NativeStringType = const XMLCh*;
  using ParserType       = SAX2XMLReader;
  using InputSourceType  = InputSource;

  static void initialize()
  {
    static std::once_flag flag;
    std::call_once(flag, []()
    {
      try
      {
        XMLPlatformUtils::Initialize();
      }
      catch (const XMLException& ex)
      {
        char*       msg = XMLString::transcode(ex.getMessage());
        std::string msgStr(msg);
        XMLString::release(&msg);
        throw XmlException(XmlErrorCode::XML_PARSER_INIT, "Xerces initialization failed: " + msgStr);
      }
    });
  }

  /// Thread-safe: terminate is a no-op. Xerces Terminate() is not thread-safe and
  /// must never be called while parsers are active. Cleanup is left to process exit.
  static void terminate() {}

  static std::unique_ptr<ParserType> createParser()
  {
    auto parser = std::unique_ptr<ParserType>(XMLReaderFactory::createXMLReader());

    parser->setFeature(XMLUni::fgSAX2CoreValidation, true);
    parser->setFeature(XMLUni::fgXercesDynamic, true);
    parser->setFeature(XMLUni::fgSAX2CoreNameSpaces, true);
    parser->setFeature(XMLUni::fgXercesSchema, true);
    parser->setFeature(XMLUni::fgXercesSchemaFullChecking, true);
    parser->setFeature(XMLUni::fgSAX2CoreNameSpacePrefixes, true);

    return parser;
  }

  template <typename HandlerT>
  static void parse(ParserType& parser, InputSourceType& source, HandlerT& handler)
  {
    XercesHandlerBridge<HandlerT> bridge(handler);
    parser.setContentHandler(&bridge);
    parser.setErrorHandler(&bridge);
    parser.parse(source);
  }

  template <typename HandlerT>
  static void parseMemory(ParserType& parser, const char* data, size_t size, HandlerT& handler)
  {
    MemBufInputSource source(reinterpret_cast<const XMLByte*>(data), size, "memory_buffer");
    parse(parser, source, handler);
  }

  static std::string toStdString(NativeStringType str)
  {
    if (!str || !*str)
      return "";
    char*       native = XMLString::transcode(str);
    std::string result(native);
    XMLString::release(&native);
    return result;
  }

};

} // namespace e57::xml
