name: openE57

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-latest]
        build_type: [Debug, Release]

    runs-on: ${{ matrix.os }}
    
    env:
      CONAN_USER_HOME: "${{ github.workspace }}/release"
      CONAN_USER_HOME_SHORT: "${{ github.workspace }}/release/short"
      INSTALL_DIR: ${{ github.workspace }}/install/
      
    steps:
      - name: Perform checkout
        uses: actions/checkout@v2
        
      - name: Install Python environment 
        uses: actions/setup-python@v2
        
      - name: Install conan
        run: |
            pip install conan --upgrade
            conan profile detect --force
            conan profile update settings.build_type=${{ matrix.build_type }} default
                    
      - name: Linux build
        if: matrix.os == 'ubuntu-20.04'
        run: |
            conan profile update settings.compiler.libcxx=libstdc++11 default
            conan create . -o openE57:with_tools=True --build=missing
            
      - name: Mac build
        if: matrix.os == 'macos-latest'
        run: |
            conan create . --build=missing
            
