name: gcc build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: install-conan
        run: pip install conan
      - name: build library
        run: |
            mkdir -p build && cd build
            conan install ../.. --build=missing
            cmake ../.. -DBUILD_EXAMPLES=ON -DBUILD_TOOLS=ON -DCMAKE_BUILD_TYPE=Release
            conan --build .
  
