name: gcc build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: conanio/gcc10:latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir -p build && cd build
    - name: init dependencies
      run: conan install ../.. --build=missing
    - name: cmake configure
      run: cmake ../.. -DBUILD_EXAMPLES=ON -DBUILD_TOOLS=ON -DCMAKE_BUILD_TYPE=Release
    - name: make
      run: make
